### ISSUE TITLE
Typo "deleteing" in Identity UI Scaffolder DeletePersonalData.cshtml.cs

### ISSUE THREAD

**Issue by jlchavez** [aspnet/Scaffolding#1046]
This line was fixed in Issue 1907 from old asp.net core repository:
Old Issue: https://github.com/aspnet/Identity/issues/1907
Old Line Fix: https://github.com/Gordon-Beeming/Identity/commit/3624da47ae932d00b157be854593763375df76d9

But on the scaffolder files for Identity UI the same error still exists.

**Comment by vijayrkn** [comment]
@HaoK

**Comment by HaoK** [comment]
This appears already fixed by one of the earlier merges in 3.0 https://github.com/aspnet/Scaffolding/blob/master/src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Manage/Account.Manage.DeletePersonalData.cs.cshtml#L91
