### ISSUE TITLE
Using C#8 features causes error while scaffolding razorpage

### ISSUE THREAD

**Issue by tg73** [aspnet/Scaffolding#1055]
## Steps to reproduce:
Follow [this series of tutorials](https://docs.microsoft.com/en-gb/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.0&tabs=visual-studio) up to and including [this step](https://docs.microsoft.com/en-gb/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-3.0&tabs=visual-studio-code#scaffold-course-pages).

Also logged here: https://github.com/aspnet/AspNetCore.Docs/issues/14044

*Update:*

This issue was originally demonstrated with a C#8 `switch` *expression* (as opposed to a traditional `switch` *statement*). @jessicah then reported the issue with C#8 `using` *declaration* (as opposed to a traditional `using` *statement*). It seems likely that this issue is related to using C#8 features in general, so I have updated the title accordingly.

*Update:*

I had forgotten that I had applied a VS analyzer code change suggestion to convert a `switch` _statement_ to a `switch` _expression_. After following the tutorials as noted above, at `Pages/Students/Index.cshtml.cs` line 52, change as follows to reproduce the problem:

Before:
```
switch (sortOrder)
            {
                case "name_desc":
                    studentsIQ = studentsIQ.OrderByDescending(s => s.LastName);
                    break;
                case "Date":
                    studentsIQ = studentsIQ.OrderBy(s => s.EnrollmentDate);
                    break;
                case "date_desc":
                    studentsIQ = studentsIQ.OrderByDescending(s => s.EnrollmentDate);
                    break;
                default:
                    studentsIQ = studentsIQ.OrderBy(s => s.LastName);
                    break;
            }
```

After:

```
            studentsIQ = sortOrder switch
            {
                "name_desc" => studentsIQ.OrderByDescending(s => s.LastName),
                "Date" => studentsIQ.OrderBy(s => s.EnrollmentDate),
                "date_desc" => studentsIQ.OrderByDescending(s => s.EnrollmentDate),
                _ => studentsIQ.OrderBy(s => s.LastName),
            };
```

Without the `switch` expression, scaffolding works. I have updated the title of this issue accordingly.

## Expected behavior:
The Courses folder is successfully scaffolded.

## Actual behavior:

From `dotnet cli`:
```console
PS> dotnet aspnet-codegenerator razorpage -m Course -dc SchoolContext -udl -outDir Pages\Courses --referenceScriptLibraries
Building project ...
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
Attempting to compile the application in memory.
Could not get the reflection type for DbContext : ContosoUniversity.Data.SchoolContext
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:08.47
```
In VS 2019 16.3.0 Preview 2.0:
![image](https://user-images.githubusercontent.com/1101693/63789246-e3bb8600-c8ee-11e9-85f3-4d03d0f6996b.png)

Could be related to #430 and #682. I've tried adding explicit ref to `Microsoft.CodeAnalysis.CSharp.Workspaces` as suggested in those issues, full rebuild of project, reload of VS etc, but it does not help.

### Target framework(s):
.NET Core 3.0
### Package version of Microsoft.AspNetCore.App or Microsoft.AspNetCore.All (if applicable):
3.0.0-preview8.19405.7
### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:
3.0.0-preview8-19413-06

**Comment by jessicah** [comment]
This also happens with new forms of C# 8 using declarations as well.

**Comment by tg73** [comment]
It seems likely that this issue is related to using C#8 features in general, so I have updated the title accordingly.

**Comment by vijayrkn** [comment]
This should be fixed in the latest rc1 versions.
