### ISSUE TITLE
Scaffolding using beta6

### ISSUE THREAD

**Issue by NicoJuicy** [aspnet/Scaffolding#107]
dnx . gen controller --controllerName CityController --model City --dataContext databaseContext

Contents of databaseContext:

    public class databaseContext : IdentityDbContext<ApplicationUser>
    {
        private  string _connectionString;

        //public DbSet<City> Cities { get; set; }
        //public DbSet<Event> Events { get; set; }
        //public DbSet<Tag> Tags { get; set; }
        //public DbSet<POI> POIs { get; set; }
        //public DbSet<OpeningPeriod> OpeningPeriods { get; set; }
        //public DbSet<VacationPeriod> VacationPeriods { get; set; }
        //public DbSet<Incident> Incidents { get; set; }

        protected override void OnModelCreating(ModelBuilder builder)
        {

            //   builder.Entity<City>().Key(p => p.id);

            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            _connectionString = "Server=(localdb)\\mssqllocaldb;Database=aspnet5-CityGuide.Web-a6a24e31-045f-4018-88a1-e5bf1962103c;Trusted_Connection=True;MultipleActiveResultSets=true";
            optionsBuilder.UseSqlServer(_connectionString);
        }
 

This is in my package manager console

     dnx . gen controller --controllerName CityController --model City --dataContext databaseContext
    Finding the generator 'controller'...
    Running the generator 'controller'...
    Attempting to figure out the EntityFramework metadata for the model and DbContext
    There was an error creating the DbContext instance to get the model: System.Reflection.TargetInvocationException: Het doel van een aanroep heeft een uitzondering veroorzaakt. ---> System.TypeLoadException: De methode Dispose in het type Microsoft.Framework.Log
    ging.LoggerFactory uit de assembly Microsoft.Framework.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null heeft geen implementatie.
       bij Microsoft.Framework.DependencyInjection.EntityFrameworkServiceCollectionExtensions.AddEntityFramework(IServiceCollection serviceCollection)
       bij Microsoft.Data.Entity.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options)
       bij Microsoft.Data.Entity.DbContext.InitializeSets(IServiceProvider serviceProvider, DbContextOptions options)
       bij Microsoft.Data.Entity.DbContext.Initialize(IServiceProvider serviceProvider, DbContextOptions options)
       bij Microsoft.AspNet.Identity.EntityFramework.IdentityDbContext`1..ctor()
       bij CityGuide.Web.Models.databaseContext..ctor()
       --- Einde van intern uitzonderingsstackpad ---
       bij System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
       bij System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
       bij System.Activator.CreateInstance(Type type, Boolean nonPublic)
       bij System.Activator.CreateInstance(Type type)
       bij Microsoft.Framework.CodeGeneration.EntityFramework.EntityFrameworkServices.GetModelMetadata(Type dbContextType, Type modelType)

project.json

       {
      "webroot": "wwwroot",
      "userSecretsId": "aspnet5-CityGuide.Web-a6a24e31-045f-4018-88a1-e5bf1962103c",
      "version": "1.0.0-*",
    
      "dependencies": {
        "EntityFramework.Commands": "7.0.0-beta6",
        "EntityFramework.Core": "7.0.0-beta6",
        "EntityFramework.SqlServer": "7.0.0-beta6",
        "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta6",
        "Microsoft.AspNet.Authentication.Facebook": "1.0.0-beta6",
        "Microsoft.AspNet.Authentication.Google": "1.0.0-beta6",
        "Microsoft.AspNet.Authentication.MicrosoftAccount": "1.0.0-beta6",
        "Microsoft.AspNet.Authentication.Twitter": "1.0.0-beta6",
        "Microsoft.AspNet.Diagnostics": "1.0.0-beta6",
        "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta6",
        "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta6",
        "Microsoft.AspNet.Mvc": "6.0.0-beta6",
        "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta6",
        "Microsoft.AspNet.Server.IIS": "1.0.0-beta6",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-beta6",
        "Microsoft.AspNet.StaticFiles": "1.0.0-beta6",
        "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta6",
        "Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-beta6",
        "Microsoft.Framework.Configuration.Abstractions": "1.0.0-beta6",
        "Microsoft.Framework.Configuration.Json": "1.0.0-beta6",
        "Microsoft.Framework.Configuration.UserSecrets": "1.0.0-beta6",
        "Microsoft.Framework.Logging": "1.0.0-beta6",
        "Microsoft.Framework.Logging.Console": "1.0.0-beta6",
        "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta6",
        "Microsoft.AspNet.Mvc.Core": "6.0.0-beta6",
        "EntityFramework.Relational": "7.0.0-beta6"
      },
    
      "commands": {
        "web": "Microsoft.AspNet.Hosting --config hosting.ini",
        "ef": "EntityFramework.Commands",
        "gen": "Microsoft.Framework.CodeGeneration"
      },
    
      "frameworks": {
        "dnx451": {
          "dependencies": {
            "EntityFramework.Core": "7.0.0-beta6",
            "EntityFramework.Relational": "7.0.0-beta6"
          }
        },
        "dnxcore50": { }
      },
    
      "exclude": [
        "wwwroot",
        "node_modules",
        "bower_components"
      ],
      "publishExclude": [
        "node_modules",
        "bower_components",
        "**.xproj",
        "**.user",
        "**.vspscc"
      ],
      "scripts": {
        "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
      }
    }
    
    
Any thoughts?

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232574&fullScreen=false&_a=edit">232574</a>

**Comment by sayedihashimi** [comment]
@NicoJuicy sorry for the delay here. I'm going to close this because we've made a lot of updates and command line scaffolding is no longer "supported".
