### ISSUE TITLE
Delete Student from two Browsers

### ISSUE THREAD

**Issue by MBongi81** [aspnet/Scaffolding#1070]
Tried the Toutorial 2 - 8 , when i want to test the changes on the Delete Logic i had the idea to use two Browser, both on Studentpages and then delete a student from the first and then the other. Expected to get the Error - instead i got 404 Page not found. 

Has anywone an idea?

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by Rick-Anderson** [comment]
@danroth27 @vijayrkn I recommend you close this. The complaint is the instructions are not adequate on [Razor Pages with EF Core in ASP.NET Core - Concurrency ](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-3.0&tabs=visual-studio)

**Comment by danroth27** [comment]
The behavior seems expected. Once the student has been deleted, the resource is gone.
