### ISSUE TITLE
For the blazor project scaffolder generates Razor Identity pages

### ISSUE THREAD

**Issue by ichensky** [aspnet/Scaffolding#1079]
For the blazor server side project scaffolder generates Razor Identity pages instead of Blazor Identity pages. 

--
Package version of Microsoft.AspNetCore.App: 3.0.0-rc1.19457.4
Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design: 3.0.0-rc1-19462-10

**Comment by vijayrkn** [comment]
@danroth27 @mkArtakMSFT

**Comment by danroth27** [comment]
@ichensky Thanks for reporting this feedback! We only maintain a Razor Pages version of the default Identity UI and scaffolded Identity code, so the behavior you are seeing is expected. Blazor is intended to be use in conjunction with MVC & Razor Pages to handle your client-side UI needs. For example, we use Razor Pages to handle prerendering for Blazor apps, and you can use Blazor components in pages and views.
