### ISSUE TITLE
Identity scaffolded item: default password validation 

### ISSUE THREAD

**Issue by ichensky** [aspnet/Scaffolding#1080]
Default password validation doesn't allow to use letters from other languages.

Try to use password like: 

паРоЛь999%=*

There will be an error: 

```
Passwords must have at least one lowercase ('a'-'z').
Passwords must have at least one uppercase ('A'-'Z').
```

Package version of Microsoft.AspNetCore.App: 3.0.0-rc1.19457.4
Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design: 3.0.0-rc1-19462-10

**Comment by HaoK** [comment]
@blowdart this is by design I think right?

**Comment by blowdart** [comment]
Feels like it yes. You can always replace it.
