### ISSUE TITLE
Identity scaffolded item: confirm email message

### ISSUE THREAD

**Issue by ichensky** [aspnet/Scaffolding#1081]
Steps to reproduce: 
1. Register a new user.
2. Open confirmation link, you'll see the message: 
"Thank you for confirming your email."
3. Close message by close button `x`.
4. Refresh page with confirming email.
Actual result: the is a confirm email message.
Expected result: message like: "You already confirmed email."

5. Open user profile page. 
Actual result: 
There is a message in the profile page:"Thank you for confirming your email."
Expected result: No messages. 

Package version of Microsoft.AspNetCore.App: 3.0.0-rc1.19457.4
Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design: 3.0.0-rc1-19462-10

**Comment by HaoK** [comment]
@blowdart not sure this is something important enough to fix, if so can you move this to aspnet core for tracking

**Comment by blowdart** [comment]
It's not, it's one of those things where, like invalid username or password we don't want to give much away.
