### ISSUE TITLE
The new version of Microsoft.VisualStudio.Web.CodeGeneration.Design isn't compatible with dotnet core 3

### ISSUE THREAD

**Issue by AhmedMKamal** [aspnet/Scaffolding#1185]
I just updated the `Microsoft.VisualStudio.Web.CodeGeneration.Design` package from `3.0.0` to `3.1.0` and the visual studio started showing the following warning message.

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1701	Package 'Microsoft.VisualStudio.Web.CodeGeneration.Design 3.1.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.	NewsPass.Api	E:\WorkSpace\Projects\NewsPass\newspass-web-api\src\NewsPass.Api\NewsPass.Api.csproj	1	
```

should I downgrade to `3.0.0`?

**Comment by ibirite** [comment]
I had the same problem here.

Downgrading it was the only solution I was able to do. And it worked fine.

**Comment by deepchoudhery** [comment]
Is your project netcoreapp 3.1?

**Comment by AhmedMKamal** [comment]
yes

**Comment by ratanparai** [comment]
Facing the same issue. Downgrading to `3.0.0` is the only option for now to solve it.

**Comment by AhmedMKamal** [comment]
If someone else still facing this issue (which isn't an issue) here's how I solve it

- Upgrade the dotnet core SDK to [3.1.100](https://dotnet.microsoft.com/download/dotnet-core/3.1)
- Update the target framework of your project to `netcoreapp3.1` instead of `netcoreapp3.0`

to upgrade the target framework through VS Properties -> Application -> Target Framework and select .Net Core 3.1 from the dropdown menu or modify the `csproj` file directly and set `<TargetFramework>netcoreapp3.0</TargetFramework>` to `<TargetFramework>netcoreapp3.1</TargetFramework>`

**Comment by ratanparai** [comment]
Can confirm. It was mistake. This error only occurs if you do not update the target framework version to 3.1. 

This issue can be closed 🍻

**Comment by deepchoudhery** [comment]
Yes, the expectation is that the tfm, and the package version match. We are looking potential workarounds or updating docs accordingly. 

Thanks.
