### ISSUE TITLE
Template processing failed with "The explicit expression block is missing a closing ")" character."

### ISSUE THREAD

**Issue by gvidinski** [aspnet/Scaffolding#1189]
https://github.com/aspnet/Scaffolding/blob/490b73570adfa270b11f4d340a6d871e5137ab25/src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.ConfirmEmailChange.cs.cshtml#L37

https://github.com/aspnet/Scaffolding/blob/490b73570adfa270b11f4d340a6d871e5137ab25/src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.ConfirmEmailChange.cs.cshtml#L39

Trying to Add Scaffolded Item -> Identity through the following error:  
**Template processing failed with"The explicit expression block is missing a closing ")" character.**

Missing closing ")" on both rows for the class <@(Model.UserClass)>

**Comment by deepchoudhery** [comment]
It's fixed for 5.0. Thanks

**Comment by deepchoudhery** [comment]
Fixed for the next release(5.0)

**Comment by Frank94co** [comment]
When we can have this bug fix? (where I say when, I'm referring about _release date_ ) 

I just created an Identity Server project but had got the same error:

"There was an error running the template C:\Users\\***\\.nuget\packages\microsoft.visualstudio.web.codegenerators.mvc\3.1.0\Templates\Identity_Versioned\Bootstrap3\Pages\Account\Account.ConfirmEmailChange.cs.cshtml: Template Processing Failed:The explicit expression block is missing a closing ")" character.  Make sure you have a matching ")" character for all the "(" characters within this block, and that none of the ")" characters are being interpreted as markup.
The explicit expression block is missing a closing ")" character.  Make sure you have a matching ")" character for all the "(" characters within this block, and that none of the ")" characters are being interpreted as markup."

Thank you in advance.
