### ISSUE TITLE
Unreachable code with non existing onException & userId

### ISSUE THREAD

**Issue by gvidinski** [aspnet/Scaffolding#1190]
I suppose this part of line 87:
`onException($"Unexpected error occurred removing external login for user with ID '{userId}'.");`
was commented out at some point in time?
Otherwise please fix it with intended behavior.  

https://github.com/aspnet/Scaffolding/blob/490b73570adfa270b11f4d340a6d871e5137ab25/src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Manage/Account.Manage.ExternalLogins.cs.cshtml#L81

**Comment by deepchoudhery** [comment]
yep that needs to be deleted. will fix in master.

**Comment by deepchoudhery** [comment]
fix made for next release. Thanks.

**Comment by plioi** [comment]
@deepchoudhery This happened today when scaffolding Identity. It did not happen about a week ago when performing the same steps.
