### ISSUE TITLE
Scaffolding Full Identity Fails in NET Core 3.1 - Error Running the Selected Code Generator

### ISSUE THREAD

**Issue by robinwilson16** [aspnet/Scaffolding#1213]
When attempting to scaffold all identity pages in a .NET Core 3.1 Web Application with in-app accounts, this fails with the following error message and the process fails:
![2019-12-31](https://user-images.githubusercontent.com/9021962/71633389-d51e0c00-2c0b-11ea-9cae-c9579fbed786.png)

If I unselect the `ConfirmEmailChange` page then it works so it seems the error is in the template for this particular page only.

**Comment by robinwilson16** [comment]
Just tested on a NET Core 3.0 project and same issue happens on that too except the template used is different (e.g. path above is 3.0.0 not 3.1.0)

**Comment by deepchoudhery** [comment]
We have a fix coming for this issue in January.
