### ISSUE TITLE
Add support to scaffold using Sqlite

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Scaffolding#1231]
When scaffolding EF based content it always uses LocalDB as the database provider. LocalDB is Windows specific. We need this support to get scaffolding to work correctly in Visual Studio for Mac. Currently when a user scaffolds an using EF the connecting points to LocalDB and the user gets a runtime error.

We would like to have an additional parameter to indicate that Sqlite should be used instead of LocalDb. From what I can tell there are three differences when using Sqlite.

1. Add Sqlite package to the project
1. Configure connection string in appSettings.json to use Sqlite
1. Update startup.cs to use Sqlite instead of SqlServer

@vijayrkn @rodrmoya

**Comment by Rick-Anderson** [comment]
Dup of #677

**Comment by deepchoudhery** [comment]
release/3.1 with the fix. will be released as part of a servicing update soon. #1234
