### ISSUE TITLE
 ScaffoldingReadMe.txt file for Identity is out of date

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Scaffolding#1237]
Copy from @aaron-kruse [AspNetCore.Docs/issues/16614](https://github.com/aspnet/AspNetCore.Docs/issues/16614#issuecomment-578224337)

>Also worth mentioning the ScaffoldingReadMe.txt file that gets created appears to be outdated as well, or at least inconsistent. It says to call `services.AddMvc() ` from `ConfigureServices()`, whereas the documentation here and the scaffolded code uses `AddControllersWithViews()` and `AddRazorPages()`.

> I realize `AddMvc()` still works, but it's simply a wrapper to call these other functions and it's confusing to see all of the different variations of things (ex. the documentation here that states it's for 3.1, and some of it is for 3.1 but as this issue points out some of it is not, meanwhile the ScaffoldingReadMe.txt also hints at a mix of both and doesn't match the code that was generated by the same run of scaffolding).

@Rick-Anderson  recommends *ScaffoldingReadMe.txt* should contain only a fwlink to https://docs.microsoft.com/aspnet/core/security/authentication/scaffold-identity

I keep that article updated.

I'll be happy to PR this if you'll outline what I need to change.

**Comment by deepchoudhery** [comment]
I'll create an fwlink to this link and then create a PR

**Comment by deepchoudhery** [comment]
fixed #1241
