### ISSUE TITLE
Add support for .NET Core 3.0 on --version 3.1.1

### ISSUE THREAD

**Issue by rmed1na** [aspnet/Scaffolding#1246]

**Comment by deepchoudhery** [comment]
We expect the version of the code generation package to match the project tfm. You may install the 3.0.0 using --version 3.0.0

**Comment by rmed1na** [comment]
> We expect the version of the code generation package to match the project tfm. You may install the 3.0.0 using --version 3.0.0

Already did. Version 3.0.0 doesn't work either.

**Comment by deepchoudhery** [comment]
I see. What is the version of your global tool?

**Comment by rmed1na** [comment]
You mean dotnet --version? It was on 3.0. Upgraded yesterday to 3.1.101

**Comment by deepchoudhery** [comment]
Are you using the cli tool or on VS?
