### ISSUE TITLE
"Scaffold the movie model" fails on macOS

### ISSUE THREAD

**Issue by tskardal** [aspnet/Scaffolding#1247]
Following the tutorial on Razor pages, this step failed for me. (I even added the sqlite flag that wasn't even mentioned in the tutorial)

## Steps to reproduce:
```
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries --useSqlite
```

## Expected behavior:
Something was scaffolded

## Actual behavior:
Error message:
> To scaffold controllers and views using models please install Entity Framework core packages and try again: Microsoft.EntityFrameworkCore.Design, Microsoft.EntityFrameworkCore.SqlServer

### Target framework(s):

```
❯ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.2.402 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SQLite" Version="3.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <UseAppHost>false</UseAppHost> <!-- this is a workaround needed to be able to run on macOS -->
  </PropertyGroup>

</Project>
```

**Comment by deepchoudhery** [comment]
This is a bug. One of sqlite or sqlserver dependency should be fulfilled(sqlite only in the case of mac). Does it function if you install the sqlserver package? 
Also can you point me to aforementioned tutorial(needs to be updated).

**Comment by tskardal** [comment]
The tutorial: https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-code#scaffold-the-movie-model-1

When I added Microsoft.EntityFrameworkCore.SqlServer I got past the error!

**Comment by Rick-Anderson** [comment]
@tskardal it has you add 

```
dotnet add package Microsoft.EntityFrameworkCore.SQLite
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet add package Microsoft.EntityFrameworkCore.Design
```

**Comment by tskardal** [comment]
@Rick-Anderson Yes, and I did. I only got it working after adding the sqlserver dependency as suggested.

**Comment by Rick-Anderson** [comment]
@tskardal  you should have opened a bug on the doc page, not the scaffolder. Can you close this issue. If you're sure you need to add that NuGet package, open this bug on the doc page.

**Comment by Rick-Anderson** [comment]
@tskardal never mind, @deepchoudhery  says this is a bug.

I haven't seen this reported before. Can you try reproducing this issue in a new project.

**Comment by deepchoudhery** [comment]
yes both dependencies should be required. we're aiming for a fix in one of the 5.0.0 preview packages.

**Comment by Rick-Anderson** [comment]
@tskardal  looks like you were using the CLI instructions

> (I even added the sqlite flag that wasn't even mentioned in the tutorial)

The CLI instructions have you add `Microsoft.EntityFrameworkCore.SqlServer`

https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#add-nuget-packages-and-ef-tools

```
dotnet tool install --global dotnet-ef
dotnet tool install --global dotnet-aspnet-codegenerator
dotnet add package Microsoft.EntityFrameworkCore.SQLite
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet add package Microsoft.EntityFrameworkCore.SqlServer
```

**Comment by tskardal** [comment]
You're right! I see now that I have been following an old tutorial (notice `?view=aspnetcore-2.2`).

Sorry for that!
