### ISSUE TITLE
RequireConfirmedAccount for Identity doesn't send an email.

### ISSUE THREAD

**Issue by serpent5** [aspnet/Scaffolding#1253]
In the Razor Page code file for Identity's External Login process, an account confirmation email is only sent if account confirmation isn't required. Here's part of the [source](https://github.com/aspnet/Scaffolding/blob/master/src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.ExternalLogin.cs.cshtml#L153-L170) in question:

```csharp
if (_userManager.Options.SignIn.RequireConfirmedAccount)
{
    return RedirectToPage("./RegisterConfirmation", new { Email = Input.Email });
}

// -snip-

await _emailSender.SendEmailAsync(Input.Email, "Confirm your email",
    $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");
```

This can be verified by checking against the source for the RCL version, [here](https://github.com/dotnet/aspnetcore/blob/master/src/Identity/UI/src/Areas/Identity/Pages/V3/Account/ExternalLogin.cshtml.cs#L209-L218). I think the order just needs to change to match that.

I can provide a PR for this, if it gets confirmed as a real issue. @HaoK Could you verify what I've stated here, please? I just spotted this when looking through the code, so I might have missed something.

**Comment by HaoK** [comment]
Sure you can submit a PR, this is a change we took for servicing and it hasn't been ported yet, so that'd be great thanks @serpent5
