### ISSUE TITLE
Localize console output and help message 

### ISSUE THREAD

**Issue by abpiskunov** [aspnet/Scaffolding#127]
Help message now comes form attributes which have hardcoded text for descriptions, we need to think how to localize it.

**Comment by robbert229** [comment]
Is using the aspnet localization project a good idea?

**Comment by abpiskunov** [comment]
Yes, looks like we need to use it.

**Comment by robbert229** [comment]
After looking at it it appears to be specifically for the web, am I wrong?

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232577&fullScreen=false&_a=edit">232577</a>

**Comment by Eilon** [comment]
Removing from milestone because this milestone already shipped.
