### ISSUE TITLE
Scaffolding controller fails without SQL Server package

### ISSUE THREAD

**Issue by anuraj** [aspnet/Scaffolding#1276]
## Steps to reproduce:

Follow [Create a Web API with ASP.NET Core docs with VS Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio-code) 

* Create an ASP.NET Core Web API project.
* Add a TodoItem model class
* Add a TodoContext class.
* Register the database context
* Add the nuget packages `Microsoft.VisualStudio.Web.CodeGeneration.Design` and `Microsoft.EntityFrameworkCore.Design` 
* Run the scaffold controller command. - `dotnet aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers`

Getting an error like this.

![image](https://user-images.githubusercontent.com/276411/76477486-853d9b80-642b-11ea-97e5-92901094de1b.png)

I am using InMemory provider not Sql Server provider.

Once I install the SqlServer package - `Microsoft.EntityFrameworkCore.SqlServer` it is working properly.

## Expected behavior:

Instead of showing the error - it should scaffold a controller.

## Actual behavior:

Generator is showing an error.

### Target framework(s):
netcoreapp3.1
### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:
3.1.1

**Comment by deepchoudhery** [comment]
Currently the sqlserver package is required to use any entityframework scaffolders.

**Comment by deepchoudhery** [comment]
We will look into adding support for non sql server providers for future releases.
