### ISSUE TITLE
Community idea: command line scaffolding

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Scaffolding#139]
A few weeks ago I posted a [an issue](https://github.com/aspnet/Scaffolding/issues/135) which stated that the ASP.NET team is going to focus on scaffolding in Visual Studio for the short term, and then at a later time we would circle back to the command line case. This was not because we don't feel that command line scaffolding is not important, but instead just a prioritization decision. We want both an in Visual Studio experience as well as a command line story, but we don't have the resources to work on both at the same time. Since I posted that, several people contacted me indicating that they are interested in working on a command line story. I'm also personally interested in a command line story as well and would like to be involved.

I'd like to see if we (_the community_) can put together a command line scaffolding story, while the ASP.NET team works on the Visual Studio support. The way that we will make sure that these experiences generate the same content is by using the same underlying code when scaffolding. Even though the ASP.NET team has paused the command line support for a bit, all of the scaffolding code will still be in the [Scaffolding](https://github.com/aspnet/Scaffolding) repo and in the same NuGet packages that are used today.

The idea is that the community can focus on the command line user experience while calling into the same NuGet packages/assemblies that Visual Studio is calling to ensure that the same content is created. If we make good progress on this project, and get good usage and feedback then hopefully we can get the ASP.NET team to consider this new commnunity effort as ***the command line story*** for scaffolding (_no guarantees there of course_).

## Previous command line scaffolding experience

In previous releases the ASP.NET team has had a command line scaffolding experience. For more info on that experience see the blog posts below.

 - http://blogs.msdn.com/b/webdev/archive/2014/08/21/command-line-scaffolding-for-asp-net-vnext.aspx
 - http://blogs.msdn.com/b/webdev/archive/2014/08/23/how-to-customize-scaffolding-templates-for-asp-net-vnext.aspx

The code for the entry point (i.e. Program/Main) for the command line scaffolding can be found at https://github.com/aspnet/Scaffolding/blob/dev/src/Microsoft.Extensions.CodeGeneration/Program.cs 

## Visual Studio scaffolding

For more info on the existing Visual Studio scaffolding story see https://docs.asp.net/en/latest/tutorials/your-first-aspnet-application.html?highlight=scaffolding#create-a-data-model-and-scaffolding. The current experience is not very broad, we still have a lot of work to do to support more scenarios.

## Proposal

I'm hoping that we can identify a few individual who are passionate about command line scaffolding and who have some time to devote to working on this. We can let the ASP.NET team do most of the hard work in the core scaffolding infrastructure and we can piggy back that to create a command line story. As the ASP.NET team enables more VS scaffolding scenarios we can enable those same scenarios on the command line. We could also make contributions back to the scaffolding core when it makes sense.

I was thinking that it would make sense to start with (_or at least take inspiration from_) https://github.com/aspnet/Scaffolding/blob/dev/src/Microsoft.Extensions.CodeGeneration/Program.cs. But I'm not sure.

If the project is successful I think we can extend it further to cover even more scenarios. This is all speculative but I can envision something like the following happening if things go well.

 1. Create a command line scaffolding experience which matches all scenarios covered by VS. Hopefully by the time that ASP.NET 5 is at RTM VS will cover the same scenarios as ASP.NET 4 scaffolding did.
 1. Extend scaffolding to enable users to get started with new projects or files. We can do this by integrating this with the experience we have in [generator-aspnet](https://github.com/OmniSharp/generator-aspnet/) aka `yo aspnet`. 
 1. Have Visual Studio replace the File->New Project experience to invoke the command line scaffolders created here. We can't invoke `yo aspnet` in the same way because it has too many dependeinces (some of which likely have license issues for Visual Studio).

## Next steps

This is where I get a bit fuzzy as to how to get started. I wanted to see if we could do a online video call with all interested parties, but unfortunately (_from this perspective_) I won't be able to do that for a few weeks because I'm out of office traveling. At least we can use this so that everyone is aware of who is interested, and what efforts are happening.

## Interested parties

The following people have expressed interest in working on this to me.

 - @Muchiachio - he even started on his own command line scaffolder at https://github.com/Muchiachio/DNX.Genny 
 - @dmccaffery
 - @erichexter
 - @ChrisKlug
 - @robrich
 - @henriksen
 - @KvdM
 - @MaximRouiller

So where do we go from here? :)

cc `generator-aspnet` folks @peterblazejewicz @spboyer @Spinarooni
cc @shanselman

**Comment by Muchiachio** [comment]
Hi, thanks for update @sayedihashimi,

At first I actually wanted to contribute to scaffolding repo and continue working on that, but it felt like it has a lot of unnecessary code for scaffolding default templates (maybe it's just me :sob:). What I would like to see is something similar and easy to extend as [this](http://blog.stevensanderson.com/2011/04/07/mvcscaffolding-creating-custom-scaffolders/). With a support to use it outside it's scaffolding structure like [this](https://github.com/Muchiachio/DNX.Genny/blob/master/src/Dnx.Genny/Scaffolding/IGennyScaffolder.cs#L7), for rendering views to string (for emails and stuff). Which seems to be demanded by the community too https://github.com/aspnet/Mvc/issues/3091, https://github.com/aspnet/Mvc/issues/3199.

I don't know how hard it is to integrate any command line tool into VS, maybe someone could shed some light here. But I believe that command line tooling has to come first :+1:

**Comment by erichexter** [comment]
@sayedihashimi <https://github.com/sayedihashimi> totally excited to help
here..

As for next steps, I am assuming we should flesh out the scenarios covered
in bullet number 1, and probably define the command line parameters from a
design perspective. keeping in mind we want to support numbers 2 & 3.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by sayedihashimi** [comment]
>At first I actually wanted to contribute to scaffolding repo and continue working on that, but it felt like it has a lot of unnecessary code for scaffolding default templates

That's one reason why I wasn't sure about the existing code. I think it would be better to have something that is more easily understood and extended.

>As for next steps, I am assuming we should flesh out the scenarios covered in bullet number 1, and probably define the command line parameters from a design perspective. keeping in mind we want to support numbers 2 & 3.

Sounds good.

So where do we want to collaborate on this? I see the following options.

 - Use https://github.com/Muchiachio/DNX.Genny
 - Create new repo in the [OmniSharp org](https://github.com/OmniSharp)
 - Create a new org and repo

Thoughts?

**Comment by MaximRouiller** [comment]
I do not see it as part of Omnisharp. 

DNX.Genny has history (commit-wise). Would we start from this project? If no, it's not the good place to start.

Either we create a new repo under your Github/NonFactors or another org (not really important).

**Comment by sayedihashimi** [comment]
>I do not see it as part of Omnisharp. 

Why not? `generator-aspnet` is already there and the Atom extension invokes `generator-aspnet` as well.

I am fine staring in `DNX.Genny` as well, but I think it would be better to put this in some org where we can manage permissions better and what not.

**Comment by Muchiachio** [comment]
I see two options here:
- Create/move to a community org/repo, by using existing [DNX.Genny](https://github.com/Muchiachio/DNX.Genny) or a fresh repo (can rename repo, and/or move to [NonFactors](https://github.com/NonFactors) or other org, but not the OmniSharp one, somehow it doesn't fit there)
- Create/move to a MS based org/repo ([aspnet](https://github.com/aspnet)/MS~ one, if MS team wants to have most of the control over it and will support it now and to the end)

I'm for going with a first option, based on your comments on how this should be a collab from community and MS.

**Comment by sayedihashimi** [comment]
Yes the first option is better MSFT will be a member of the community in much the same was as OmniSharp but wont have "control"

**Comment by erichexter** [comment]
I am not sure I understand the push against the  omnisharp org.

**Comment by MaximRouiller** [comment]
Didn't see the `generator-aspnet` and `generator-csharp` there. 

Whatever happens, this need to be under an org ;-) It's purely based on preferences at that point. 

I'll let @sayedihashimi pick one. NonFactors or Omnisharp could both fit the bill.

**Comment by Muchiachio** [comment]
> I am not sure I understand the push against the  omnisharp org.

I don't know myself, OmniSharp just feels to be something with cross plat C# editors~~
Either way, it's not like we won't be able to merge/change orgs if we need to :ok_hand:

**Comment by shanselman** [comment]
Given that OmniSharp is about: "OmniSharp is a family of Open Source projects, each with one goal: To enable a great .NET experience in YOUR editor of choice" (I know because I wrote the website) then one needs to make a new project in order to use their editor, right? I think the OmniSharp *organization* is a decent place for a scaffolder/generator as it enables the next step, a good experience in the editor.

**Comment by MaximRouiller** [comment]
Sold for me :+1:

**Comment by Muchiachio** [comment]
:+1:

**Comment by sayedihashimi** [comment]
Ok so I can create the repo and grant access. Do we want to start with DNX.Genny sources?

**Comment by dmccaffery** [comment]
I'm fine starting from DNX.Genny. The only thing I'd want is to ensure the following:

1) We keep in line with Microsofts goals for scaffolding and enable all the scenarios that VS will enable at launch (even if we lag behind)

2) We enable some form of extensibility so folks can easily create their own scaffolding "templates" based on the engine

**Comment by dmccaffery** [comment]
Oh, and 3) @shanselman does a dramatic zoom out in our honor when we release 1.0. :)

**Comment by dmccaffery** [comment]
Actually; the more I am looking at it, the more I think we should fork [Scaffolding](https://github.com/OmniSharp/generator-aspnet/) instead of starting from DNX.Genny. Only because of the stated goal of relying on the scaffolding APIs that VS itself will be using. DNX.Genny goes down a different route of relying on a custom razor view engine host to enable scaffolding.

I like the idea of enabling some form of templating, such as the razor view host idea, in the future, but I think we should start by lighting up the same scaffolding that VS will enable @ the command line.

**Comment by dmccaffery** [comment]
I vote for OmniSharp as the org, by the way -- makes sense to one day extend the cmd-line into tooling hooks for editors, which is exactly what OmniSharp is all about.

**Comment by dmccaffery** [comment]
... and I've changed my mind again. Sorry. @Muchiachio has something real, here, with DNX.Genny ... if we light up the same scenarios with a simplified approach, this has a much better chance of getting off the ground in a community project.

**Comment by itomek** [comment]
I'd like to help (time permitting)!

**Comment by henriksen** [comment]
I'd like to contribute as well. +1 for OmniSharp, seems like the best place. Also, I like the thought of being able to piggy back on the efforts of the VS team. Will that be possible if we start with DNX.Genny (haven't studied the code yet, still on a phone today)?

**Comment by sayedihashimi** [comment]
I haven't looked at the code either, I was hoping it just replaced the cli and calls into the existing NuGet pkgs.

**Comment by dmccaffery** [comment]
It doesn't. It replaces the RazorViewHost with its own implementation from stem to stern. Forking the existing repo created by MS is probably the best solution. I know I keep going back and forth in this, but I studied both repositories at this point and we'd definitely need most of what is in the existing Infrastructure anyway.

The other alternative is to just start with a fresh repo and pull in the scaffolding infrastructure dependencies via NuGet.

**Comment by sayedihashimi** [comment]
Ok I see. Scaffolding gets hairy really quick when EF models are involved. I don't think we want to take that on, especially since my team is already working on it. Instead the idea is to just create a new UX (cli). We can also see if we can add unique value where it makes sense.

**Comment by dmccaffery** [comment]
Agreed. +1: So, next step is to get OmniSharp org folks on board, right? Have we decided on that, at least? :)

**Comment by dmccaffery** [comment]
emote fail. :+1:

**Comment by sayedihashimi** [comment]
I can make the repo in OmniSharp as I'm an owner. What name? I think we can start with a clone of scaffolding but I think we just need CodeGeneration project and then use NuGet pkg references for other projects.

**Comment by Muchiachio** [comment]
I'm fine either way :smiley:

**Comment by dmccaffery** [comment]
Well, aren't you special, Mr. Owner; lol.

Names not important to me; whatever OmniSharp conventions are:

omnisharp-scaffolding?

**Comment by dmccaffery** [comment]
Also, agreed on the dependencies; use NuGet for whatever is possible. Since the main Scaffolding project is OSS, we can always submit pull requests to it if there is a bug or missing feature we would somehow find or need; which is better than duplicating effort.

**Comment by sayedihashimi** [comment]
@dmccaffery @Muchiachio ok great, I have created https://github.com/OmniSharp/omnisharp-scaffolding and invited you both to be admins. Welcome to OmniSharp :)

>Also, agreed on the dependencies; use NuGet for whatever is possible. Since the main Scaffolding project is OSS, we can always submit pull requests to it if there is a bug or missing feature we would somehow find or need; which is better than duplicating effort.

Yes and if we need to debug sources we can add a source path to `global.json` that can be used to load the latest sources.

**Comment by sayedihashimi** [comment]
Also see https://github.com/OmniSharp/omnisharp-scaffolding/issues/1

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232579&fullScreen=false&_a=edit">232579</a>

**Comment by mlorbetske** [comment]
Closing per @sayedihashimi
