### ISSUE TITLE
Error occurs using classes from another class project while scaffolding with rc1-final

### ISSUE THREAD

**Issue by gokalpi** [aspnet/Scaffolding#140]
When I try to add a new scaffolded item from context menu inside Visual Studio Community Edition, I get an error saying "There was an error running the selected code generator: 'Value cannot be null. Parameter name: oldTree'".

I am trying to get model and context information from another class project inside the same solution.
![addcontroller](https://cloud.githubusercontent.com/assets/7867997/11302502/8855f960-8fa6-11e5-8042-dae9a07299ee.JPG)
![addcontrollererror](https://cloud.githubusercontent.com/assets/7867997/11302503/886d8ab2-8fa6-11e5-844c-cb476ecb960c.JPG)

**Comment by daviatorstorm** [comment]
Have the same problem.

**Comment by gokalpi** [comment]
I found a work around for this, but it's not a good one. You create a copy of your DbContext class inside the web application project and select data context class as this one. No error occurs and controller and related views are created. Then in controller class code change DbContext namespace to entities class namespace.

**Comment by daviatorstorm** [comment]
I just created a controller just with my hands. But its not curring the problem. The main question is, why vs 2015 cannot create a controller through ui?

**Comment by herruzojm** [comment]
I had the same problem; solved after adding a DbSet in my DbContext.

**Comment by olliholliday** [comment]
Thanks @herruzojm 

The scaffolder needs a public DbSet<T> {get;set;} on the context for the type you're scaffolding

**Comment by ovidiaconescu** [comment]
Thanks @herruzojm, this solved the problem.

**Comment by barrytang** [comment]
We need to add a work item to support dbContext in classlib.

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232580&fullScreen=false&_a=edit">232580</a>

**Comment by Eilon** [comment]
Approved for 1.0.0-preview2-update1.
