### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by mattfraley1** [aspnet/Scaffolding#145]
I see there are lots of changes happening right now, a change of direction and a separate project spinning off. However the recent update seems to indicate this should still work. Maybe we just need updated instructions? 

I am using the following dependency from myget. 
"Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-rc1-15776"

Then added the command
"gen": "Microsoft.Framework.CodeGeneration"

When trying to run dnx gen commands, I get the following error:
Unable to resolve service for type 'Microsoft.Dnx.Runtime.ILibraryManager' while attempting to activate 'Microsoft.Framework.CodeGeneration.DefaultCodeGeneratorAssemblyProvider'.

Should this work, or do we need to wait for whatever comes next, or am I doing something wrong?

**Comment by sayedihashimi** [comment]
Hi @mattfraley1 see my comments at https://github.com/aspnet/Scaffolding/issues/135.

I'm not sure if the command line `gen` command will work or not. We are removing the command line scaffolding support but we will circle back to it later.

For future reference it's better to open issues relating to VS tooling for ASP.NET 5 in the https://github.com/aspnet/Tooling repo. I'll close this issue now, but we can discuss more in the tooling repo if you like.
