### ISSUE TITLE
DropDownListFor problem

### ISSUE THREAD

**Issue by antonioapostoliu** [aspnet/Scaffolding#146]
I start one new project with Visual Studio 2015 with Update 1 RC and ASPNET 5 RC1 and add models from page
http://ef.readthedocs.org/en/latest/modeling/relational/fk-constraints.html
I saved and build .(without errors)
Also I run from command line:

dnvm use 1.0.0-rc1-final
dnx ef migrations add First
dnx ef database update

After scaffold operations, blogs pages works. I create 2 blogs entries.
Also list view from posts works.
The problem is in create new post page. The combo box blog reference list is empty. I expected to find the 2 blogs entries from previous action.

In controller (thanks scaffold !) I found:

// GET: Post/Create
        public IActionResult Create()
        {
            ViewData["BlogId"] = new SelectList(_context.Blog, "BlogId", "Blog");
            return View();
        }

In view I add line(s):

@Html.DropDownListFor(n=>n.BlogId,ViewData["BlogId"],
				"Choose...",new { @class = "form-control"  })

After navigate to localhost:5000/Post/Create I receive Error message
In the Kestrel log I receive following lines

An unhandled exception has occurred: One or more compilation failures occurred:
 /Views/Post/Create.cshtml(26,40): DNX,Version=v4.5.1 error CS1503: Argument 2: cannot convert from 'object' to 'System.Collections.Generic.IEnumerable<Microsoft.AspNet.Mvc.Rendering.SelectListItem>'

Please tell me where I wrong.

Best regards

**Comment by dougbu** [comment]
Since you've changed the scaffolded code, this issue does not belong here. Either way, the `Exception` informs you of the problem: Need to cast `ViewData["BlogId"]` to `IEnumerable<SelectListItem>` or `SelectList`. That will match the `Html.DropDownListFor()` parameter type.

Probably easier to pass `null` and let the HTML helper look up the select list in `ViewData`:
``` c#
    @Html.DropDownListFor(
        n => n.BlogId,
        selectList: null,
        optionLabel: "Choose...",
        htmlAttributes: new { @class = "form-control" })
```
