### ISSUE TITLE
DataType.MultilineText does not generate textarea

### ISSUE THREAD

**Issue by madmunsterdaddy** [aspnet/Scaffolding#147]
Cross post from https://github.com/aspnet/Mvc/issues/3651

In MVC5 you could do this:

public class ApplicationUser : IdentityUser
{
    [DataType(DataType.MultilineText)]
    public string Bio { get; set; }
}

That would generate a textarea tag to make it multi-line. Not working in MVC6 (rc1). The generated input control is not multi line.

**Comment by dougbu** [comment]
As [mentioned](https://github.com/aspnet/Mvc/issues/3651#issuecomment-160050906) in the original MVC issue: The generated view uses `<input asp-for="Bio" class="form-control" />`. Scaffolding should instead generate a `<textarea/>` element or use the more-general `@Html.EditorFor()` HTML helper.

The workaround is to use
``` c#
@Html.EditorFor(m => m.Bio, additionalViewData: new { htmlAttributes = new { @class = "form-control" }})
```
or
``` html
    <textarea asp-for="Bio" class="form-control"></textarea>
```

**Comment by sayedihashimi** [comment]
Moved it to https://github.com/aspnet/Tooling/issues/319 closing this
