### ISSUE TITLE
MVC Scaffolding SelectList (RC1)

### ISSUE THREAD

**Issue by bartekkois** [aspnet/Scaffolding#149]
After running scaffolding in RC1 on simple classes like below I got the follwing code in Book controller and Book View:

        // GET: Books/Create
        public IActionResult Create()
        {
            ViewData["Authors"] = new SelectList(_context.Authors, "AuthorID", "Author");
            return View();
        }

        <div class="form-group">
            <label asp-for="Genre" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="AuthorID" class ="form-control"></select>
            </div>
        </div>

I assume that there is an asp-items directive missing in that code.

 public class Book
    {
        public int BookID { get; set; }

        [Required()]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Display(Name = "Release Year")]
        public int Year { get; set; }

        [Display(Name = "Price")]
        public decimal Price { get; set; }

        [Display(Name = "Genre")]
        public string Genre { get; set; }

        public int AuthorID { get; set; }

        // Navigation property
        public virtual Author Author { get; set; }
    }

    public class Author
    {
        public int AuthorID { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "First Name")]
        public string FirstMidName { get; set; }

        public virtual ICollection<Book> Books { get; set; }
    }

**Comment by dougbu** [comment]
@bartekkois you're correct that the generated code is incorrect. The `<select>` tag helper does not use a "magic" `ViewData` entry to find an `IEnumerable<SelectListItem>`. Best approach is to create an `AuthorViewModel` class containing an `IEnumerable<SelectListItem> Authors` property and then add `asp-items="Model.Authors"`. With the `ViewData` approach, you need
```
@{ var authors = (IEnumerable<SelectListItem>)ViewData["Authors"]; }
<select asp-for="AuthorID" asp-items="authors" class="form-control"></select>
```

Separately the `<label>` references the wrong field. Should be
``` html
<label asp-for="AuthorId" class="col-md-2 control-label"></label>
```

**Comment by bartekkois** [comment]
I've tried ViewData approach from your comment however I still got an Exception while opening /Book/Create. While debugging authors is filled with data about Authors.

System.NullReferenceException: Object reference not set to an instance of an object
   w Microsoft.AspNet.Mvc.Rendering.MultiSelectList.Eval(Object container, String expression)
   w Microsoft.AspNet.Mvc.Rendering.MultiSelectList.<>c__DisplayClass28_0.<GetListItemsWithValueField>b__2(<>f__AnonymousType6`2 <>h__TransparentIdentifier0)
   w System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   w System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w Microsoft.AspNet.Mvc.Rendering.MultiSelectList.GetListItemsWithValueField()
   w Microsoft.AspNet.Mvc.Rendering.MultiSelectList.GetListItems()
   w Microsoft.AspNet.Mvc.Rendering.MultiSelectList.GetEnumerator()
   w System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   w System.Linq.GroupedEnumerable`3.GetEnumerator()
   w Microsoft.AspNet.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateGroupsAndOptions(String optionLabel, IEnumerable`1 selectList)
   w Microsoft.AspNet.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateSelect(ViewContext viewContext, ModelExplorer modelExplorer, String optionLabel, String expression, IEnumerable`1 selectList, IReadOnlyCollection`1 currentValues, Boolean allowMultiple, Object htmlAttributes)
   w Microsoft.AspNet.Mvc.TagHelpers.SelectTagHelper.Process(TagHelperContext context, TagHelperOutput output)
   w Microsoft.AspNet.Razor.TagHelpers.TagHelper.<ProcessAsync>d__5.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w Microsoft.AspNet.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w Asp.ASPV__Views_Books_Create_cshtml.<>c__DisplayClass30_0.<<ExecuteAsync>b__0>d.MoveNext() w /Views/Books/Create.cshtml:wiersz 19
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w Microsoft.AspNet.Razor.Runtime.TagHelpers.TagHelperExecutionContext.<GetChildContentAsync>d__38.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w Microsoft.AspNet.Mvc.TagHelpers.RenderAtEndOfFormTagHelper.<ProcessAsync>d__7.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w Microsoft.AspNet.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w Asp.ASPV__Views_Books_Create_cshtml.<ExecuteAsync>d__30.MoveNext() w /Views/Books/Create.cshtml:wiersz 6
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w Microsoft.AspNet.Mvc.Razor.RazorView.<RenderPageAsync>d__17.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w Microsoft.AspNet.Mvc.Razor.RazorView.<RenderAsync>d__16.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w Microsoft.AspNet.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__14.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w Microsoft.AspNet.Mvc.ViewResult.<ExecuteResultAsync>d__24.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResultAsync>d__56.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResultFilterAsync>d__55.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAllResultFiltersAsync>d__54.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResourceFilterAsync>d__49.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__44.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__27.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__8.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

**Comment by dougbu** [comment]
The stack trace above points to code inside the `MultiSelectList` you've passed to the `<select>` tag helper. How are you creating that instance?

**Comment by bartekkois** [comment]
Controller:

        // GET: Books/Create
        public IActionResult Create()
        {
            ViewData["AuthorID"] = new SelectList(_context.Authors, "AuthorID", "Author");
            return View();
        }


View:

@{
    var authors = (IEnumerable<SelectListItem>)ViewData["AuthorID"];
    ViewData["Title"] = "Create";
}

        <div class="form-group">
            <label asp-for="Genre" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="AuthorID" asp-items="authors" class ="form-control"></select>
            </div>
        </div>

**Comment by dougbu** [comment]
@bartekkois the problem happens when `MultiSelectList` tries to evaluate the "Author" or "AuthorId" property of a `_context.Authors` entry. Does `_context.Authors` contain one or more `null` entries?

**Comment by bartekkois** [comment]
In my database I've got two records (AuthorID=1, FirstMidName="aa", LastName="bb") (AuthorID=2, FirstMidName="cc", LastName="dd").
Below you can see how it looks like in view while I'am debugging.
![pic](https://cloud.githubusercontent.com/assets/16276688/11817892/5a1aa7b6-a357-11e5-8ebf-5e73405794a1.png)

**Comment by dougbu** [comment]
Ah but neither element has an `Author` property. `new SelectList(_context.Authors, "AuthorID", "Author")` means "`_context.Authors` is a collection of objects with "AuthorID" and "Author" properties, get the item's value from the first property and the text to display from the second.

Suggest `new SelectList(_context.Authors, "AuthorID", "LastName")`.

**Comment by bartekkois** [comment]
My bad. Now it works perfectly.

**Comment by adgerrits** [comment]
Thanks Dougbu.Was facing the same problem and searching for an answer your hints were the most usefull ;)

**Comment by bdelaney** [comment]
Trying to work with this for a partial view and not able to populate my viewmodel with the selectlistitems, thus getting null reference in asp-items. Should I pass in the viewmodel with Html.Partial? And if so, how to populate the selectlistitem within that viewmodel. Since I'm not using a controller, unclear about how to code an instance of the viewmodel to get SelectList populated. Should I do this in the constructor of the viewmodel?

**Comment by dougbu** [comment]
@bdelaney please clarify your scenario. How are you creating the `SelectListItem`s? Are you using RC1 bits? How are you invoking the view if you're not using a controller? What exactly are your view model and the relevant parts of the partial view?

**Comment by bdelaney** [comment]
Using RC1, basic MVC app. I am calling a partial from within a view, using Html.Partial. The partial view has a model based on a viewmodel for a many:many entity. In the viewmodel I create a selectlist in the getter of my selectlist like this:
```
(from item in _context.People
                select new SelectListItem()
                {
                    Text = item.ID.ToString(),
                    Value = item.Name.ToString()
                }).ToList();
```
I am only supplying the name of the partial view to Html.Partial right now. I realize this is my issue as I have not even populated the selectlist when the partial is rendered with it's empty viewmodel. What I'm really asking is what is a best practice for delivering a selectlist with the model so that the taghelper may use it. I've seen examples of asp-items="@Html.DropDownListFor..." and it just does not seem right to me.

**Comment by bdelaney** [comment]
I resolved this by building the model in the controller and passing it view ViewBag into the parent view and then passing it as parameter to Html.Partial. The syntax of taghelpers is new to me and the lack of documentation on asp-items had me thinking of all the Html helper design patterns. Clearly that is not what is intended. While making good use of ViewComponents, I had to fall back to Partial views for this use case. Sorry about appropriating this thread, but it is one of the few places I've found helpful information about this taghelper function.

**Comment by dougbu** [comment]
Glad you got everything working. If you encounter further issues, don't hesitate to open a new issue.

> I've seen examples of `asp-items="@Html.DropDownListFor..."` and it just does not seem right to me.

You're correct. That's horribad and should lead to a compiler error because the `asp-items` value must be an `IEnumerable<SelectListItem>`, not an `IHtmlContent`.

But there's no reason creating the select list in the view (partial or otherwise) shouldn't just work. The rest of the code should look like
```
@{
    var selectList = (from item in _context.People
                select new SelectListItem()
                {
                    Text = item.ID.ToString(),
                    Value = item.Name.ToString()
                }).ToList();
}
<select asp-for="Property" asp-items="selectList"></select>
```

**Comment by dougbu** [comment]
@rustd has this issue been addressed in the latest round of scaffolding changes? That is does the code now generate the following? Hoping we can close this issue now.
```
@{ var authors = (IEnumerable<SelectListItem>)ViewData["Authors"]; }
<select asp-for="AuthorID" asp-items="authors" class="form-control"></select>
```

**Comment by rustd** [comment]
I don't know. @sayedihashimi owns scaffolding so adding him

**Comment by bdelaney** [comment]
One helpful suggestion I have for the documentation/scaffolding team is to offer more vigorous examples of using the taghelpers. I'm still stuck on using the ugly syntax like this `asp-items="Html.GetEnumSelectList<roletype>()"`
for enums. The scaffolding stuff has got to be really hard, but the docs could at least take into account some of the most common cases. With EF7, the scaffolding must be even more difficult. As I've been working with the tooling since beta4, and spent a lot of time on Github following both teams, the docs have gotten better and better. but things like enums and many:many are not corner cases and really deserve clarification.

**Comment by markramel** [comment]
thank you for this post!!!

**Comment by s4sanjoy** [comment]
# Try This
**Controller:**
//ViewData["BankId"] = new SelectList(_context.Bank, "BankId", "Bank");
//ViewData["UnitId"] = new SelectList(_context.Unit, "UnitId", "Unit");
ViewData["BankId"] = new SelectList(_context.Set<Bank>(), "BankId", "BankName");
ViewData["UnitId"] = new SelectList(_context.Set<Unit>(), "UnitId", "UnitName");
**View:**
<select class="form-control"
                        asp-for="UnitId"
                        asp-items="ViewBag.UnitId"></select>
                <select class ="form-control" 
                        asp-for="BankId" 
                        asp-items="ViewBag.BankId"></select>

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232581&fullScreen=false&_a=edit">232581</a>

**Comment by prafullbhosale** [comment]
This should be fixed as part of: 
https://github.com/aspnet/Scaffolding/issues/232
