### ISSUE TITLE
Losing special characters and accents

### ISSUE THREAD

**Issue by rustd** [aspnet/Scaffolding#151]
Porting from Templates https://github.com/aspnet/Templates/issues/335

Here are the repro steps.
I've installed the latest version of VS2015 and ASP.NET WEB tools
I created a ASPNET5 Default Template Project.

I just follow this tutorial https://docs.asp.net/en/latest/tutorials/your-first-aspnet-application.html

When i add a new "Add Scaffold " controller in option "MVC 6 Controller with views, using Entity Framework", then all added files (controller and views) are in ASCII enconding.

**Comment by prafullbhosale** [comment]
I tried creating a controller that had accent characters in the name and it seems to work fine with the current bits. 

There are a few issues with dotnet cli that people have noticed around this: 
dotnet/cli/issues/2590  

I tried with cli version `1.0.0-rc2-002543` and didn't see the cli issue. 

Closing this. Please feel free to reopen if you the issue happening again.
