### ISSUE TITLE
MVC6 Controllers have wrong namespace

### ISSUE THREAD

**Issue by esargent** [aspnet/Scaffolding#155]
When you generate an MVC6 controller it uses the project name as the root namespace rather than the project's default namespace specified in the project file.

I see there is a review comment in the code already to this issue about the difference between behavior in Visual Studio vs. command line, but I'm not sure that matters to those of us using Visual Studio who have gone to the trouble of defining a specific default root namespace. From a VS user's perspective this is a bug, even if there are other scenarios where you can't access the project file setting.

(Just thinking aloud - for cmd line, and pre-acknowledging that I don't understand all the scenarios that cmd line applies to - but why couldn't you look for the xproj file, even climbing parent directories until you find one? Then if one still doesn't exist go ahead and use existing logic. Wouldn't that allow for greater consistency between the two scenarios? )

**Comment by prafullbhosale** [comment]
This should now be fixed. 
The Codegenerator will accept a `--controllerNameSpace` parameter. In absence of the parameter, the defaulting logic will be based on ApplicationName + Directory in which the controller is added. 

Related #229
