### ISSUE TITLE
views in wrong place when using areas

### ISSUE THREAD

**Issue by esargent** [aspnet/Scaffolding#156]
I have areas setup for my site. I add the folder /Areas/Admin/Views/Locations, right-click "add scaffolding" on that folder and run the "MVC6 Controller with views, using Entity Framework" scaffolding.

Result: While the LocationsController.cs is created in that folder as expected, the views show up in the root /Views/ in a new Locations folder rather than under my /Areas with the controller.

Expected Result - everything would show up in the /areas folder structure.

In case it helps, routes are defined in Startup.Configure as

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "areaRoute",
                    template: "{area:exists}/{controller}/{action}",
                    defaults: new { controller = "Admin", action = "Index" });

                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

**Comment by esargent** [comment]
The other thing I noticed is that the controller could be decorated with the proper "area" attribute to make things really smooth. I think all the information needed is in the folder structure - as long as people are using the standard conventions

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232582&fullScreen=false&_a=edit">232582</a>

**Comment by prafullbhosale** [comment]
Fixed by https://github.com/aspnet/Scaffolding/pull/295
