### ISSUE TITLE
Change to build to use dotnet

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Scaffolding#161]
We're migrating all the repos using dnx to dotnet. This repo is part of that migration.

At a minimum, you have to upgrade a few scripts and project.json files just like here: aspnet/Configuration@9cfd22f

The big umbrella bug tracking the migration is here: https://github.com/aspnet/Universe/issues/324

**Comment by victorhurdugaci** [comment]
Assigning this to you @prafullbhosale because I believe you're the owner of this repo. If not, please assign to the appropriate owner.

**Comment by prafullbhosale** [comment]
@victorhurdugaci  Is there any recent change to this build process? 
I was able to build till today morning, but the build is failing to restore packages now.

**Comment by victorhurdugaci** [comment]
We just updated dotnet restore to use the new nuget code and everything is failing. @anurse is looking into this

**Comment by prafullbhosale** [comment]
Any updates on this?

**Comment by victorhurdugaci** [comment]
The world is still broken...



On Tue, Jan 19, 2016 at 4:52 PM -0800, "prafullbhosale" <notifications@github.com<mailto:notifications@github.com>> wrote:


Any updates on this?

-

**Comment by prafullbhosale** [comment]
Am able to build now. Thanks!

**Comment by victorhurdugaci** [comment]
How's this going? Are you blocked on anything?

**Comment by prafullbhosale** [comment]
I have got the build working with the exception that it doesn't run the tests. 
I have made the changes in [this](https://github.com/aspnet/Scaffolding/commits/pb/363-2) branch.
There are still a few more tests that need fixing as there's been quite a few changes.

**Comment by victorhurdugaci** [comment]
Is this ready? Can it be merged?

**Comment by prafullbhosale** [comment]
All the changes are in (#167) , just waiting on aspnet/Universe#362, as I still cannot build if I remove the CLI, xunit and nugetbuild feeds from the nuget.config

**Comment by victorhurdugaci** [comment]
That's done actually

**Comment by prafullbhosale** [comment]
Just saw it, will check now and merge if it builds without additional feeds.

**Comment by prafullbhosale** [comment]
Local build looks good. I have merged the changes to dev. 
Closing this issue as done.
