### ISSUE TITLE
bug: rc2 ValidationSummary

### ISSUE THREAD

**Issue by esargent** [aspnet/Scaffolding#162]
RC2 changed the syntax for ValidationSummary 

        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>

to 

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

.

**Comment by Rick-Anderson** [comment]
@prafullbhosale will this be fixed for RC2?
To repro - scaffold a model. This bug is found in the create and edit razor files.

**Comment by Rick-Anderson** [comment]
related #209
