### ISSUE TITLE
Unhandled exception in async controller actions.

### ISSUE THREAD

**Issue by madmunsterdaddy** [aspnet/Scaffolding#165]
I generated a controller for a model with async actions. It generates an Edit action like the one below.
The issue is, if you pass in an id that does not exist SingleAsync will throw rather than return null and eventually reach the HttpNotFound result. So that code will never execute.

Should these generate with SingleOrDefaultAsync?

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            WebMessage webMessage = await _context.WebMessages.SingleAsync(m => m.Id == id);
            if (webMessage == null)
            {
                return HttpNotFound();
            }
            return View(webMessage);
        }

**Comment by madmunsterdaddy** [comment]
this is an issue with RC1 by the way... sorry I left that out.

**Comment by prafullbhosale** [comment]
> Should these generate with SingleOrDefaultAsync?

@madmunsterdaddy you are correct. 
This is addressed in https://github.com/aspnet/Scaffolding/pull/157
