### ISSUE TITLE
Can not debug

### ISSUE THREAD

**Issue by reezonew** [aspnet/Scaffolding#170]
Hi all
I got this exception when debugging, which stopped at line 66 by calling the method "OnProjectAdded(projectInfo);", in the ProjectJsonWorkspace class, under the Utils project.

Excetpion:
The type initializer for 'Microsoft.CodeAnalysis.CSharp.CSharpCompilationFactoryService' threw an exception.

Inner exception:
Method not found: 'Void Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions..ctor(Microsoft.CodeAnalysis.OutputKind, Boolean, System.String, System.String, System.String, System.Collections.Generic.IEnumerable`1<System.String>, Microsoft.CodeAnalysis.OptimizationLevel, Boolean, Boolean, System.String, System.String, System.Collections.Immutable.ImmutableArray`1<Byte>, System.Nullable`1<Boolean>, Microsoft.CodeAnalysis.Platform, Microsoft.CodeAnalysis.ReportDiagnostic, Int32, System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,Microsoft.CodeAnalysis.ReportDiagnostic>>, Boolean, Boolean, Microsoft.CodeAnalysis.XmlReferenceResolver, Microsoft.CodeAnalysis.SourceReferenceResolver, Microsoft.CodeAnalysis.MetadataReferenceResolver, Microsoft.CodeAnalysis.AssemblyIdentityComparer, Microsoft.CodeAnalysis.StrongNameProvider, Boolean)'.

**Comment by barrytang** [comment]
This doesn't seem to be related to scaffolding.
