### ISSUE TITLE
Controller w/ Actions using EF - Scaffolder not working

### ISSUE THREAD

**Issue by Cnordbo** [aspnet/Scaffolding#171]
I created a detailed post about it here: 

http://stackoverflow.com/questions/35187813/azure-web-api-scaffolding-generator-not-found

Error: 
There was an error running the selected code generator: 
There was an error getting the type "failtest.Models.TestModelClass". 
Try rebuilding the project.

Expected: 
New controller with actions, new DbContext, Updated Web.config

**Comment by prafullbhosale** [comment]
@Cnordbo Based on your post, it looks like the issue was specific to your machine setup. 
Closing this issue. 
Feel free to re-open this if that is not the case.
