### ISSUE TITLE
Remove ProjectModel.Workspace related code from Utils project

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#174]
Currently this code is duplicated from dotnet/cli repo because of a bug that caused restore to failed if both ProjectModel and ProjectModel.Workspaces were added as dependencies.

**Comment by prafullbhosale** [comment]
Moving to RC2 as this is needed with the new Roslyn packages `Microsoft.CodeAnalysis.CSharp.Workspaces	     v1.3.0-beta1-20160425-01`

cc @barrytang @Eilon

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232585&fullScreen=false&_a=edit">232585</a>
