### ISSUE TITLE
Test failure under Release configuration

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Scaffolding#175]
The issue here is that the library exporter is hard coded to use the `Debug` configuration https://github.com/aspnet/Scaffolding/blob/27f910e111e3c176acdf904079053d2b9264cbf3/src/Microsoft.Extensions.CodeGeneration.Utils/DotNet/LibraryExporter.cs#L29. 

On our CI, we test using the `Release` configuration which will cause failures when the test try to look for libraries built with `Debug` e.g. " Could not find a part of the path 'C:\gh\Scaffolding\test\TestApps\ModelTypesLocatorTestClassLibrary\bin\ __Debug__ \dnxcore50\ModelTypesLocatorTestClassLibrary.dll'"

I made a temporary fix in https://github.com/aspnet/Scaffolding/commit/243fd3c37c158ec096dcc25e7322e5fbb032b564 to unblock Universe Test but I'm not sure if it's the right fix.

cc @dougbu @kichalla

**Comment by dougbu** [comment]
Sorry I don't have context to answer "right fix" questions here. I suggest involving someone more familiar with the `LibraryExporter`s and this repo.

**Comment by JunTaoLuo** [comment]
Thanks @dougbu, I wanted to keep the build buddies updated. cc @PradeepKadubandi @prafullbhosale   can you guys take a look at this issue?

**Comment by prafullbhosale** [comment]
I will look into this.

**Comment by prafullbhosale** [comment]
Most of the times for scaffolding the configuration would need to be "Debug". 
But the right way to handle it would be to let the invoker (VS) decide the configuration and assume a reasonable default if unspecified.
