### ISSUE TITLE
Update Roslyn packages

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Scaffolding#190]
Currently, the roslyn packages are pinned to old versions https://github.com/aspnet/Scaffolding/blob/dev/src/Microsoft.Extensions.CodeGeneration.Utils/project.json#L7-L9. These need to be updated now that we have newer versions of these packages on our feeds.

This also seems to have resolved the test failures that I saw in https://github.com/aspnet/Coherence-Signed/issues/230.

**Comment by prafullbhosale** [comment]
Closing this as this has been resolved in https://github.com/aspnet/Scaffolding/pull/192
