### ISSUE TITLE
Scaffolding a controller using entity framework fails if the user project has services.AddMvc

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#196]
If the user project has 
`services.AddMvc();`
or 
```
app.UseMvc( ...
);
```

scaffolding an ef based controller fails. 

The reason for the failure is that these methods try to load the project's assembly to find out the parts of the assembly to use for MVC. 

Scaffolding code loads the project in memory and then modifies the startup.cs and creates a new in-memory assembly with a different name. 
So when the code tries to invoke the startup type, the mvc code tries to load the 'newName' assembly, which cannot be found.

**Comment by prafullbhosale** [comment]
Tagging aspnet/Release#4

**Comment by sayedihashimi** [comment]
+1
