### ISSUE TITLE
Scaffolding Error when working with EF Fluent API

### ISSUE THREAD

**Issue by Eilon** [aspnet/Scaffolding#199]
Move from https://github.com/aspnet/Mvc/issues/4336, opened by @hernandemczuk

=========

I have a **Data Acces Logic (Entity Framework)** project, a **Model** project with my POCOs classes and a last one with the **MVC Application**. In my DAL project, I configure some validations on my Model and its schema information on the database using **Fluent API**. That means that I use the following method in order to add these configurations:

`protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Configurations.Add(new Model1Configuration());
        }
`

When I try to add a new controller to my MVC application I select the option **MVC Controller with views, using Entity Framework**, which leads me to pick a **Data Context Class** and a **Model Class**. I mark **Generate Views** and write a **Controller Name** to finally click on **Add...**

Then the following alert shows up:

![error](https://cloud.githubusercontent.com/assets/4275069/14003095/05c05a5a-f12f-11e5-8da1-a7f94c7a1ec5.png)

I know it has something to do with the Fluent API, because if I comment out the previuos method I mentioned I can scaffold without any problem.

I'm using MVC v5.2.3 , Entity Framework v6.1.3

**Comment by Eilon** [comment]
@prafullbhosale

**Comment by narulasrinivas** [comment]
When is the planned release for this bug?

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232590&fullScreen=false&_a=edit">232590</a>

**Comment by barrytang** [comment]
This is fixed for the upcoming Dev14 release.
