### ISSUE TITLE
Scaffolding tool should not be shipped to nuget...

### ISSUE THREAD

**Issue by muratg** [aspnet/Scaffolding#200]
Per a discussion today with @DamianEdwards and @rustd, this tool would only live in WTE, and not be uploaded to nuget.org.

We need to change this: https://github.com/aspnet/Coherence/blob/dev/packages/packages.csv#L10, but also make it possible to sign it.

cc @Eilon @pranavkm

**Comment by rustd** [comment]
@sayedihashimi FYI.

**Comment by Eilon** [comment]
Is there any change to make in this repo? Or is the only change in packages.csv and setup? Does WTE itself need to change to adapt to this change?

**Comment by Eilon** [comment]
cc @barrytang as well.

**Comment by muratg** [comment]
@Eilon I believe there's no change in this repo, though we'll need to figure out how to sign the tool... 

Also, I assume `M.E.CodeGeneration.*` ([these lines](https://github.com/aspnet/Coherence/blob/dev/packages/packages.csv#L141-L146)) will also need to be changed.

**Comment by barrytang** [comment]
I talked to @danroth27 and I think we need to ship the scaffolding package on nuget otherwise people opening a project created in VS won't be able to restore it on a machine without VS.

**Comment by prafullbhosale** [comment]
Tagging aspnet/Release/issues/4

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232589&fullScreen=false&_a=edit">232589</a>

**Comment by sayedihashimi** [comment]
From previous discussions we do not have the ability to remove this package. If we wanted to do that we would need some proposed solution from the runtime team.
I don't personally see any value in doing this and I'd rather the team be focused on important deliverables. If the runtime team is still interested in this please come back with a specific technical proposal and then we can evaluate it. Closing for now.
