### ISSUE TITLE
Microsoft.Extensions.CodeGenerators.Mvc package

### ISSUE THREAD

**Issue by rustd** [aspnet/Scaffolding#205]
With the new .NET CLI tools we should not be needing this package anymore.
https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/project.json#L29

Look at how razor-tools are registered. EF will be doing the same. We should ensure that Scaffolding does this too.
This is required for RC2

**Comment by rustd** [comment]
@prafullbhosale @sayedihashimi can you please triage this for RC2

**Comment by sayedihashimi** [comment]
Is there a tfs bug for this?

**Comment by rustd** [comment]
Not sure. Please open one if there isn't

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232591&fullScreen=false&_a=edit">232591</a>

**Comment by prafullbhosale** [comment]
Closing this. 

Currently we have a `Microsoft.VisualStudio.Web.CodeGeneration.Design` package in the templates that is needed for scaffolding.
