### ISSUE TITLE
Cannot scaffold on ApplicationDbContext

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Scaffolding#211]
If you create a new web app with **Individual User Accounts**, you can't use ApplicationDbContext to scaffold a model.

**Comment by prafullbhosale** [comment]
@Rick-Anderson, I tried this with version `1.0.0-rc2-20778` and it works. 
Can you try with this version and see if it works for you?

**Comment by prafullbhosale** [comment]
Closing this for now. 
Please re-open if you continue to see this issue.

**Comment by Rick-Anderson** [comment]
@prafullbhosale  I'll test it this week and let you know if I have any problems.
