### ISSUE TITLE
Scaffolding requires Individual User Accounts

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Scaffolding#212]
It would help our Intro to MVC tutorial if we didn't need all the code from **Individual User Accounts**

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232592&fullScreen=false&_a=edit">232592</a>

**Comment by barrytang** [comment]
This is intentional and we will remove that requirement in future releases.
