### ISSUE TITLE
Support code generators whose assembly name is different from the package name

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Scaffolding#216]
Currently DefaultCodeGeneratorAssemblyProvider uses the package id as the name of the assembly (https://github.com/aspnet/Scaffolding/blob/55a33bc1eb94ab7bbc3dd53a343bdc883bff4200/src/Microsoft.Extensions.CodeGeneration.Core/DefaultCodeGeneratorAssemblyProvider.cs#L61) meaning that if the assembly has a different name than the package things break badly. We should use the actual assembly name when we create the `AssemblyName` of the assembly that we want to load.

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232593&fullScreen=false&_a=edit">232593</a>

**Comment by mlorbetske** [comment]
There hasn't really been much demand for writing custom code generators & this is an easy enough guideline to set for the time being. Longer term, more of the model of how scaffolding interacts with  the project will change, making this not necessary.
