### ISSUE TITLE
Guid requires System namespace

### ISSUE THREAD

**Issue by mrcha0s** [aspnet/Scaffolding#217]
Hello,

This is a minor issue. Scaffolding does not add System namespace when you are using Guid as unique identifier.

Thanks

**Comment by prafullbhosale** [comment]
Hi @mrcha0s! 
Can you provide which version of the packages are you using? 
This was fixed a while back https://github.com/aspnet/Scaffolding/commit/bf9e2eb805278657746cc9990f347df95db59110

**Comment by mrcha0s** [comment]
sorry my bad I did not update the latest one. I'm using rc1-final and ASP.NET and Web Tools 2015 (RC1 Update 1)
