### ISSUE TITLE
Create template markup should match the templates

### ISSUE THREAD

**Issue by rustd** [aspnet/Scaffolding#223]
When you scaffold a controller with EF, the create view generates the following:
```html
 <div asp-validation-summary="ModelOnly" class="text-danger"></div>
```
It should be
```html
 <div asp-validation-summary="All" class="text-danger"></div>
```
Please make a pass at the markup generated by the views and ensure that it matches with what the templates have.

**Comment by dougbu** [comment]
@rustd if the templates also use `<span asp-validation-for="..."></span>` for the properties, `asp-validation-summary="All"` is just redundant. `ModelOnly` eliminates that redundancy.

**Comment by rustd** [comment]
They don't use asp-validation-summary="All", This is what we have today https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Views/Account/Register.cshtml

So are we recommending the following markup to use?
```html
 <span asp-validation-for="Email" class="text-danger" asp-validation-summary="All"></span>
```

**Comment by dougbu** [comment]
No, you're mixing attributes for the summary at the top (the `<div>`) with validations for individual properties (the `<span>`s).

The `Register.cshtml` file you linked mostly looks fine but should use `<div asp-validation-summary="ModelOnly" class="text-danger"></div>`.

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232595&fullScreen=false&_a=edit">232595</a>

**Comment by barrytang** [comment]
@sayedihashimi @rustd, should we use all or not? :)

**Comment by NTaylorMullen** [comment]
@rustd why'd you think this should be validation-summary="all"?

**Comment by Bartmax** [comment]
please keep `ValidationSummary="ModelOnly"` All will just show the model state errors twice for properties.
