### ISSUE TITLE
Scaffolded views should have valid span tag

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Scaffolding#227]
When a view is scaffolded the `span` for validation is generated as a self-closing tag. This should be a valid `<span>..</span>` tag.

Expected:
`<span asp-validation-for="Title" class="text-danger"></span>`

Actual:
`<span asp-validation-for="Title" class="text-danger" />`

**Comment by DamianEdwards** [comment]
This actually breaks the validators showing server-side validation. If you disable client-side validation (just don't render the javascript) then it's immediately apparent when trying to post an invalid form.

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232598&fullScreen=false&_a=edit">232598</a>

**Comment by prafullbhosale** [comment]
https://github.com/aspnet/Scaffolding/commit/85a473beca62e3eeb93f4493037be286ead12b80

**Comment by Eilon** [comment]
Approved for 1.0.0-preview2-update1.
