### ISSUE TITLE
No newline between using statements and namespace declaration

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Scaffolding#228]
In `MVC Controller with read/write actions` and `API Controller with read/write actions` the generated code does not have a new line between using statements and namespace declaration.

Example:
``` c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
namespace WebApplication1.Controllers
{
```

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232597&fullScreen=false&_a=edit">232597</a>
