### ISSUE TITLE
Scaffolding API Controller with EntityFramework does not use var in some places

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Scaffolding#230]
Example:

Scaffold a controller using `API Controller with actions, using Entity Framework` with `Book` as model class. The generated code will have the below line in two places.
`Book book = await _context.Book.SingleOrDefaultAsync(m => m.ID == id);`

Expected:
`var book = await _context.Book.SingleOrDefaultAsync(m => m.ID == id);`

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232596&fullScreen=false&_a=edit">232596</a>

**Comment by prafullbhosale** [comment]
https://github.com/aspnet/Scaffolding/commit/f7c6297b2cf716f498c5e52582a6b60cc5e94466
