### ISSUE TITLE
Edit does not scaffold Id field

### ISSUE THREAD

**Issue by phenning** [aspnet/Scaffolding#243]
//cc: @dvdobrovolskiy

(Ported from https://github.com/aspnet/Templates/issues/584)

[HttpPost]
 [ValidateAntiForgeryToken]
 public async Task Edit(int id, [Bind("RSOTimeToResponce,RiseToRSO,Title,UKOTimeToResponce,ZayavkaReasonType,ZayavkaType,ZayavkaAskTime")] Reason reason)

No Id field in Bind("...") so it cannot update row

**Comment by prafullbhosale** [comment]
@dvdobrovolskiy Can you share your model? 

When I try with a simple model like 
```
    public class Product
    {
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }

        public double Price { get; set; }
    }
```
The Edit method looks like this

```
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Price")] Product product)
```

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232603&fullScreen=false&_a=edit">232603</a>

**Comment by barrytang** [comment]
@dvdobrovolskiy, haven't heard back from you. Closing for now.
