### ISSUE TITLE
Fix build warnings

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Scaffolding#244]
* [x] Scaffolding\src\Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore\project.json(30,19): warning DOTNET1015: The 'packInclude' option is deprecated. Use 'files' in 'packOptions' instead.
* [x] Scaffolding\src\Microsoft.VisualStudio.Web.CodeGenerators.Mvc\project.json(23,19): warning DOTNET1015: The 'packInclude' option is deprecated. Use 'files' in 'packOptions' instead.

**Comment by pranavkm** [comment]
cc @prafullbhosale

**Comment by prafullbhosale** [comment]
Fixed by 0e459d735ffa04883f95c2e7bc36fb2a50d435ae
