### ISSUE TITLE
Error multiple types matching the name while Scaffolding ASP.NET Core MVC RC2

### ISSUE THREAD

**Issue by ar27111994** [aspnet/Scaffolding#249]
I'm developing a web app in Asp.Net Core RC2 according to n-layered architecture.

![f](https://cloud.githubusercontent.com/assets/13036687/15938117/385b07aa-2e8b-11e6-8272-9ff5f33a88b6.PNG)

When I try to use scaffolding to generate CRUD Controller and Views, I get the following error.

![e](https://cloud.githubusercontent.com/assets/13036687/15938191/8eb5847c-2e8b-11e6-9f7a-c3540228e356.PNG)

I have separated my Models/ViewModels and Context/Repository Classes into Business Logic Layer and Data Access Layer respectively. I'm referencing both these layers in OpenBiz project as nuget packages. But cannot perform scaffolding as seen above. Is there an issue with my architecture or am I missing something here?

**Comment by ar27111994** [comment]
Any Help?!

**Comment by prafullbhosale** [comment]
@ar27111994 Can you provide your model structure?

**Comment by ar27111994** [comment]
[https://drive.google.com/folderview?id=0B3UaNHYpTyWrYkVqWVpZZEhnbHM&usp=sharing](Schema link) @prafullbhosale sorry couldn't generate a class diagram but instead generated schema in html files. Hope this helps. Thanks!

**Comment by prafullbhosale** [comment]
@ar27111994 Do your projects OpenBizBLL and OpenBizDal both contain the type `OpenBizBLL.Entities.Inventory.Brand`? 

If that is the case, then please rename one of them (move to a different namespace)

Also currently there is an issue with scaffolding, that it doesn't support model classes outside of the current project properly. 

As a workaround, you can add the model temporarily to your web project and then move it to the BLL/ DAL projects after scaffolding. 

I have filed an issue for the supporting model classes outside of the current project [here.](https://github.com/aspnet/Scaffolding/issues/251)

**Comment by ar27111994** [comment]
@prafullbhosale No, there is no duplication. Yep, even after moving my DAL Classes into my OpenBiz project I encountered the `No model type returned for type: <class name>` error. But with three layers I encounter the `Error multiple types matching the name <class name>` error. Thanks!

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232616&fullScreen=false&_a=edit">232616</a>

**Comment by gdoron** [comment]
@barrytang  @prafullbhosale 
Any update on this one? 
I tried with the latest bits and still happening. 
> dotnet --version
1.0.0-preview3-003180

It's like this for months and cause the entire scaffolding to be unusable if your project is bigger than one assembly!

**Comment by Eilon** [comment]
Approved for 1.0.0-preview2-update1.
