### ISSUE TITLE
Remove unnecessary imports

### ISSUE THREAD

**Issue by javiercn** [aspnet/Scaffolding#250]
Currently blocked on Microsoft.Composition

Errors in C:\work\Universe\Scaffolding\src\Microsoft.VisualStudio.Web.CodeGeneration.Templating\project.json
    Package Microsoft.Composition 1.0.27 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0
,Profile=Profile259)
    One or more packages are incompatible with .NETStandard,Version=v1.6.

**Comment by javiercn** [comment]
https://github.com/dotnet/corefx/issues/6598

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232606&fullScreen=false&_a=edit">232606</a>

**Comment by mlorbetske** [comment]
Dup of #272
