### ISSUE TITLE
Scaffolding an empty mvc controller returns an undefined view

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Scaffolding#256]
Scaffolding an empty MVC controller adds:
```
    public class MusicController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
```

This returns a View, but there is no view defined so it fails with:
```
InvalidOperationException: The view 'Index' was not found. The following locations were searched:
 /Views/Music/Index.cshtml
 /Views/Shared/Index.cshtml
```

What's the point of scaffolding an incomplete set? It should either include a view or not try to return one by default.

**Comment by Tratcher** [comment]
Adding "MVC Controller with read/write actions" has the same problem.

**Comment by prafullbhosale** [comment]
These are by design. 
The Empty and Read Write Actions scaffolders are not meant to provide "fully working" controllers. 
They are just to provide a starting point for further development. 
cc @sayedihashimi

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=233434&fullScreen=false&_a=edit">233434</a>

**Comment by barrytang** [comment]
By design.
