### ISSUE TITLE
Compiler error while scaffolding an MVC controller

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Scaffolding#258]
I get this VS popup sporadically when trying to scaffold a new controller:
```
---------------------------
Microsoft Visual Studio
---------------------------
Error

There was an error running the selected code generator:

'Project WebApplication6 (.NETCoreApp,Version=v1.0) will be compiled because project is not safe for incremental compilation. Use --build-profile flag for more information.
Compiling WebApplication6 for .NETCoreApp,Version=v1.0
Running with configuration from C:\temp\WebApplication6\src\WebApplication6\bundleconfig.json
Processing wwwroot/css/site.min.css
  Bundled
  Minified
Processing wwwroot/js/site.min.js
Compilation failed.
    0 Warning(s)
    1 Error(s)
Time elapsed 00:00:05.9348301'
---------------------------
OK   
---------------------------
```

Repro:
- Right-click on Controllers and Add -> Controller
- Select MVC Controller - Empty
- Set the controller name and click Add

Sometimes you get the above error and when pressing OK it goes back to the controller name window.  Still not sure what triggers the error.

**Comment by Tratcher** [comment]
I have also seen this error trying to add a view.

**Comment by Tratcher** [comment]
And a new API controller. This seems to be a general issue.

**Comment by Tratcher** [comment]
After the error you end up back at the controller name window. Clicking Add again succeeds.

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=233432&fullScreen=false&_a=edit">233432</a>

**Comment by prafullbhosale** [comment]
Closing this. 
Now if the compilation fails, it will display the reason for the compilation failure. 
Will re-open this if the compilation error is caused due to scaffolding itself.
