### ISSUE TITLE
Add a --no-build flag to dotnet-aspnet-codegenerator

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#261]
Currently for every invocation, scaffolding always calls `dotnet build`. 
There should be a way to make this optional. 
One example of scenario where this might be useful is the user is running the project in IIS express, running `dotnet build` would cause failures if the project is `not safe for incremental compilation`
This will cause scaffolding to fail.

**Comment by barrytang** [comment]
TFS Bug#235743
