### ISSUE TITLE
Navigation properties are not displayed in List (Index), Details, or Delete

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Scaffolding#262]
For generated views, navigation properties are displayed in Create and Edit, but not List (Index), Details, or Delete.

Sample models:
```
    public class Director
    {
        public int DirectorID { get; set; }
        public string Name { get; set; }
    }
    public class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set; }
        public decimal Price { get; set; }

        public int DirectorID { get; set; }
        public virtual Director Director { get; set; }
    }
```

Also, is there any way to attribute either model so that the scaffold knew which field(s) from Director to display? Right now Create and Edit default to:
```
ViewData["DirectorID"] = new SelectList(_context.Set<Director>(), "DirectorID", "DirectorID");
```
When I'd rather have it generate:
```
ViewData["DirectorID"] = new SelectList(_context.Set<Director>(), "DirectorID", "Name");
```

**Comment by prafullbhosale** [comment]
> Also, is there any way to attribute either model so that the scaffold knew which field(s) from Director to display? Right now Create and Edit default to:
> 
> ViewData["DirectorID"] = new SelectList(_context.Set<Director>(), "DirectorID", "DirectorID");
> When I'd rather have it generate:
> ViewData["DirectorID"] = new SelectList(_context.Set<Director>(), "DirectorID", "Name");

Yes, scaffolding looks for a `[Required]` string property in the navigation. If none is found, then it uses the primary key. 
This is because a non required string property may end up having empty entries in the select list.

**Comment by Tratcher** [comment]
Thanks, that worked.

**Comment by barrytang** [comment]
TFS Bug#235742
