### ISSUE TITLE
readme have very old samples.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Scaffolding#265]
I don't find documentation for `Microsoft.VisualStudio.Web.CodeGeneration.Tools` anywhere.

dotnet `.... what ? .... ` should be used here?

tools became very dark on last updates where the command is no longer discoverable via project.json.

**Comment by barrytang** [comment]
TFS Bug#235741

**Comment by harlyd** [comment]
You can use "dotnet aspnet-codegenerator controller -?"

**Comment by prafullbhosale** [comment]
You can also try: 
`dotnet aspnet-codegenerator -h`

Controller options
`dotnet aspnet-codegenerator --project <path-to-project> controller -h`

View options
`dotnet aspnet-codegenerator --project <path-to-project> view -h`

**Comment by Bartmax** [comment]
thank you!

**Comment by prafullbhosale** [comment]
closing this as readme was updated recently by @sayedihashimi
