### ISSUE TITLE
Failed to restore packages for tool 'Microsoft.VisualStudio.Web.CodeGeneration.Tools' 

### ISSUE THREAD

**Issue by xatabhk** [aspnet/Scaffolding#268]
log  : Restoring packages for tool 'Microsoft.VisualStudio.Web.CodeGeneration.Tools' in C:\downloads\web\projects\ZaxiTechCore\src\ZaxiTechCore\project.json...
error: Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.
log  : Lock file has not changed. Skipping lock file write. Path: C:\downloads\web\projects\ZaxiTechCore\src\ZaxiTechCore\project.lock.json
log  : C:\downloads\web\projects\ZaxiTechCore\src\ZaxiTechCore\project.json
log  : Restore failed in 16501ms.

**Comment by prafullbhosale** [comment]
@xatabhk can you share your `project.json` ?

**Comment by xatabhk** [comment]
@prafullbhosale 

[project.txt](https://github.com/aspnet/Scaffolding/files/347184/project.txt)

**Comment by prafullbhosale** [comment]
@xatabhk in your tools section you need to add an import `portable-net45+win8` for the `VisualStudio.Web.CodeGeneration.Tools`


```
    "tools": {
        "BundlerMinifier.Core": "2.1.258",
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-*",
        "Microsoft.AspNetCore.Razor.Tools": "1.0.0-*",
        "Microsoft.EntityFrameworkCore.Tools": "1.0.0-*",
        "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
            "version": "1.0.0-*",
            "imports": "portable-net45+win8"
         }
    }
```
This is currently needed because of 
https://github.com/aspnet/Scaffolding/issues/250

**Comment by mlorbetske** [comment]
TFS Bug#241352

**Comment by prafullbhosale** [comment]
Closing this as we are tracking it in another bug #272
