### ISSUE TITLE
View Scaffolding with DbContext based on IdentityDbContext fails

### ISSUE THREAD

**Issue by barrytang** [aspnet/Scaffolding#270]
Attempts to generate a view produce this error:

![image](https://cloud.githubusercontent.com/assets/1648865/16607514/9cb3c348-42f6-11e6-8284-d0b1381196f1.png)

I do not find any mechanism to create an EF Core 1.0 DbContext with a "parameterless constructor".

The only constructor I have is

 public LynxJournalDbContext(DbContextOptions<LynxJournalDbContext> options) : base(options) { }

**Comment by barrytang** [comment]
Opened on behalf of @jwdavidson.

**Comment by prafullbhosale** [comment]
@jwdavidson Can you share your project?
Is the DbContext registered in the Startup.cs?

**Comment by jwdavidson** [comment]
After issues in other areas I uninstalled and then reinstalled Preview2 of the Tooling and re-arranged the project.json entries that existed from Preview1. It is now working.

I would recommend that someone post a best practices project.json file for Preview2 as it is easy to find incorrect configuration information that works for some instances, especially for projects that were start in RC1 and have been migrating as changes occurred through to RTM.

Issue may be closed. Thank you

**Comment by mlorbetske** [comment]
TFS Bug#241354

**Comment by jwdavidson** [comment]
Error was corrected after uninstalling Dotnet Core and doing a
reinstallation.

Thank you
