### ISSUE TITLE
New Scaffolding Files not appearing in the project.

### ISSUE THREAD

**Issue by barrytang** [aspnet/Scaffolding#271]
Steps 
1. Created new 1.0 website 
2. Added to GitHub private repo 
3. Add class in Models 
4. Right click on Controllers and Select Add Controller to create new controller and views based off of class created in step 3. 
5. Files not present in the project. Checking Output window shows the files are created. Checking file system the files have been created. 

In my case closing and then reopening the project makes the files finally appear. But doing this after every scaffolding attempt is cumbersome and would be confusing for a new user. 

Thanks
 AJ

**Comment by barrytang** [comment]
Opened on behalf of @ArieJones.

**Comment by barrytang** [comment]
@prafullbhosale, can you take a look?

**Comment by prafullbhosale** [comment]
@ArieJones can you share your project? 
Also can you provide more information on the visual studio version installed?

**Comment by ArieJones** [comment]
Visual Studio Information is below ..... 

Microsoft Visual Studio Enterprise 2015
Version 14.0.25421.03 Update 3
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA394
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-80000-00000-AA394
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA394
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA394
Microsoft Visual C++ 2015

.NET Portability Analyzer   1.1.10808.0
API portability analyzer.

Application Insights Tools for Visual Studio Package   7.0.20622.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.20624.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9.1   14.0.20519.0
Azure App Service Tools v2.9.1

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.0.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

CodeRush for Visual Studio   16.1.4.0
CodeRush for Visual Studio

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DataFactoryProject   1.0
Microsoft Data Factory Package

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Image Optimizer   3.6.89
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JustDecompile Tools   1.0
Makes JustDecompile functionality available in VIsual Studio. Requires JustDecompile installation.

Microsoft .NET Core Tools (Preview 2)   14.1.20624.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Data Factory Node Node   1.0
Azure Data Factory extension for Visual Studio Server Explorer.

Microsoft Azure HDInsight HQL Service   2.0.6000.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40518.2

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

NuProjPackage   1.0
NuGet Package Project System

Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
Microsoft Office Developer Tools for Visual Studio 2015 ENU

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Analysis Services   13.0.900.80
Microsoft SQL Server Analysis Services Designer 
Version 13.0.900.80

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 13.0.900.80

SQL Server Reporting Services   13.0.900.80
Microsoft SQL Server Reporting Services Designers 
Version 13.0.900.80

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Telerik ASP.NET AJAX VSExtensions   2016.2.603.0
Telerik UI for ASP.NET AJAX VSExtensions

Telerik ASP.NET MVC VSExtensions   2016.2.603.0
Telerik UI for ASP.NET MVC VSExtensions

Telerik DataAccess VSExtensions   2016.1.111.0
Telerik DataAccess VSExtensions

Telerik Silverlight VSExtensions   2016.2.603.0
Telerik UI for Silverlight VSExtensions

Telerik Windows Phone VSExtensions   2016.2.427.0
Telerik UI for Windows Phone VSExtensions

Telerik WinForms Converter   2016.2.603.0
Telerik UI for WinForms Converter VSExtensions

Telerik WinForms VSExtensions   2016.2.603.0
Telerik UI for WinForms VSExtensions

Telerik WPF VSExtensions   2016.2.603.0
Telerik UI for WPF VSExtensions

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   1.8.34.0
TypeScript tools for Visual Studio

Visual Studio Tools for Universal Windows Apps   14.0.25420.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by ArieJones** [comment]
Is there somewhere that I can send you a zip file of the base project other than attaching a zip to GitHub? 
I think this is really not associated with the project ... it is just that Visual Studio is not updating the files in the Solution Explorer view once they are created... as I put in my post.. I am just creating a pretty generic RTM web solution.... adding in a model (shown below) and then trying to have it generate the scaffolding for me... it is creating the files....it is just not showing them in Solution Explorer....regardless if I have "show all files" on or not... they do not appear until I close the solution and then reopen it. 

```
   public class Client
    {
        [Key]
        public int ID {get;set; }
        public string FormalName {get;set; }
        public string Street1 {get;set; }
        public string Street2 {get;set; }
        public string City {get;set; }
        public string State {get;set; }
        public string ZipCode {get;set; }

    }
```

**Comment by prafullbhosale** [comment]
Thanks @ArieJones ! Based on your description, it doesn't look like project specific. 
I will look into it based on the above information and get back to you.

**Comment by mlorbetske** [comment]
TFS Bug#241353

**Comment by Eilon** [comment]
Removing from milestone because this milestone already shipped.

**Comment by vijayrkn** [comment]
This is fixed.
