### ISSUE TITLE
Remove portable imports once we update to post RTM build of Microsoft.Composition

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Scaffolding#272]
React to https://github.com/dotnet/corefx/issues/9300

**Comment by mlorbetske** [comment]
TFS Bug#241355

**Comment by prafullbhosale** [comment]
Blocked by: https://github.com/dotnet/roslyn/issues/16040

**Comment by Eilon** [comment]
Removing from milestone because this milestone already shipped.

**Comment by prafullbhosale** [comment]
This is already fixed in 2.0.0. Closing.
