### ISSUE TITLE
[Build break] Scaffolding generates Windows NewLines on Unix

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Scaffolding#280]
Scaffolding just added several functional tests that pass on Windows and fail on Unix. They are failing because the scaffold generates Windows line endings (`\r\n`) on unix, but the baseline files are checked out with unix line endings ('\n`).

If the tools is meant to be run on unix it should emit the correct line endings there. If it's not meant to be run on unix then the new tests should be excluded.

@prafullbhosale

**Comment by prafullbhosale** [comment]
Disabled the base line comparison for the test on non windows for now. 
The build should be fixed by this. 
Will keep the issue open to fix the line endings issue. 
https://github.com/aspnet/Scaffolding/commit/9b18790ea460991ed696cf8e852dc20a1be77e31

**Comment by Eilon** [comment]
Removing from milestone because this milestone already shipped.
