### ISSUE TITLE
Adapt to new project model 

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#281]
Need to find alternatives to APIs provided by `Microsoft.DotNet.ProjectModel` and `Microsoft.DotNet.ProjectModel.Workspaces`

Scaffolding uses the above for the following information/ actions:
- References of the project
- Build path
- Target frameworks
- Project compilation
- Modifying project compilation
- Updating source code files

**Comment by prafullbhosale** [comment]
Related aspnet/EntityFramework#6139

**Comment by mlorbetske** [comment]
Duplicate of #298
