### ISSUE TITLE
[DatabaseGenerated(DatabaseGeneratedOption.None)] should scaffold

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Scaffolding#282]
In ASP.NET 4 the scaffolder is intelligent enough to know that if you define a key as `[DatabaseGenerated(DatabaseGeneratedOption.None)]` it should scaffold a field in the Create view – now it doesn’t.

cc @tdykstra

**Comment by mlorbetske** [comment]
TFS Bug#248116

**Comment by prafullbhosale** [comment]
This is fixed in `dev`
