### ISSUE TITLE
Scaffold engine adds check ID == ID

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Scaffolding#287]
To repro, scaffold a simple model:

```
  public class Contact
 {
        public int Id{ get; set; }
        public string Name { get; set; }
}
```

The following code is generated:

```
public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Contact contact)
        {
            if (id != contact.Id)
            {
                return NotFound();
            }
```

id and contact.id are the same from binding.

Now change the model to use ContactID in lieu of ID.

```
 {
        public int ContactId{ get; set; }
        public string Name { get; set; }
}
```

And the following code is generated:

```
 if (id != contact.ContactId)
            {
                return NotFound();
            }
```

In this case id is the ambient route parameter, but this check provides no real value.

**Comment by prafullbhosale** [comment]
@rynowak Does MVC guarantee that the route value `id` will always match the value from the model's `ID`? 

The generated code is taking a conservative approach by adding a restriction in the Edit method. 

cc @sayedihashimi

**Comment by HADB** [comment]
What's meaning of checking Id==model.Id? 🤔

**Comment by vijayrkn** [comment]
Closing since the issue does not have any functional impact.
