### ISSUE TITLE
Fields with [NotMapped] do not scaffold even with [ScaffoldColumn(true)]

### ISSUE THREAD

**Issue by shobman** [aspnet/Scaffolding#289]
I have fields in the UI that don't make it to the DB and I would like to scaffold them out in my views even though they are marked with [NotMapped]. I tried adding [ScaffoldColumn(true)] but they still won't scaffold.  Is there a way to do this?  IMO fields marked with [NotMapped] should still scaffold by default. Or at least, I should be able to get them to scaffold with [ScaffoldColumn(true)].

**Comment by vijayrkn** [comment]
Setting ScaffoldColumn to true should fix this. If that doesn’t work please reopen with a sample. Thanks for the report.
