### ISSUE TITLE
Msbuildify tools

### ISSUE THREAD

**Issue by muratg** [aspnet/Scaffolding#298]
### Microsoft.VisualStudio.Web.CodeGeneration.Tools
- Expect to run in the IDE (via MSBuild in order to get project context)
- Needs Roslyn Workspace (ugh)
### TODO
- Fork tools repos to `rel/1.0.0-preview3` branches for "October" release. Dev branches will continue to be used for 1.1 release.
- Use desktop msbuild to start our work until the new msbuild is ready for   consumption
### Notes
- [This](https://github.com/aspnet/Coherence-Signed/issues/375) tracks the work across the tools repos.
- [This](https://github.com/aspnet/specs/blob/master/notes/Tools.md) is the previous discussion on the topic.

**Comment by prafullbhosale** [comment]
Related #281
