### ISSUE TITLE
Switch to use Find[Async]() instead of First[OrDefault][Async]() or Single[OrDefault][Async]() as appropriate

### ISSUE THREAD

**Issue by divega** [aspnet/Scaffolding#300]
`Find()` (added to EF Core in 1.1) can return objects already in memory without performing a database roundtrip. We are also unnecessarily using `SingleOrDefault()` in some cases in comparisons by key which would never return more than one row.

**Comment by Eilon** [comment]
Removing from milestone because this milestone already shipped.
