### ISSUE TITLE
CodeGeneration project has a 1.0.0 version but depends on 1.1.0 packages 

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/Scaffolding#304]
https://github.com/aspnet/Scaffolding/blob/dev/src/Microsoft.VisualStudio.Web.CodeGeneration/project.json must either itself be a 1.1.x package or only depend on 1.0.x packages

**Comment by natemcmaster** [comment]
Does the 1.0.x rule also apply to Roslyn (and it's dependency on Microsoft.Composition)?

**Comment by mlorbetske** [comment]
@natemcmaster I believe so - assuming that Microsoft.Composition is part of the "trains" model

**Comment by prafullbhosale** [comment]
The versioning is fixed now. We have both 1.0.0-* and 1.1.0-* packages for scaffolding.
