### ISSUE TITLE
Remove use of Microsoft.DotNet.InternalAbstractions from 1.1.0

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#311]
Introduced by https://github.com/aspnet/Scaffolding/pull/310

**Comment by Eilon** [comment]
Yes, please 😄

**Comment by Tratcher** [comment]
Is this happening for 1.1? The change from #310 isn't there in the 1.1 branch, but I get this error:
![image](https://cloud.githubusercontent.com/assets/1821173/20225963/e2101d10-a7fa-11e6-8005-7a2c3eaed5e6.png)

**Comment by Tratcher** [comment]
Manually adding the `"Microsoft.DotNet.InternalAbstractions": "1.0.0",` dependency to my app works around the issue.

**Comment by Tratcher** [comment]
Repro steps: Right-click Controllers, Add, Controller

**Comment by prafullbhosale** [comment]
Closing this.
