### ISSUE TITLE
Possible to generate just Views (Create, Delete, Details etc)?

### ISSUE THREAD

**Issue by mcquiggd** [aspnet/Scaffolding#319]
At present, there is no option to generate all Views (without the scaffolder also creating a Controller, Context, registering it in Startup.cs etc), and it is rather painful to have to create each View by scaffolding it individually.

Are there any plans to offer this?

Or, for example, the ability to create a template that can call 'create other templates' (which would offer most flexibility).. ?

**Comment by vijayrkn** [comment]
Create view scaffolders are available now. Closing.
