### ISSUE TITLE
MsBuild: Verifier issues

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Scaffolding#322]
EXEC : error : ASSEMBLY_DESCRIPTION @ lib/net46/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild.dll: The managed assembly 'lib/net46/Microsoft.VisualStudio.Web.CodeGeneration.Msbuild.dll' in this package is missing the 'AssemblyDescription' attribute.

**Comment by prafullbhosale** [comment]
Fixed in #324
