### ISSUE TITLE
Add DotNetCliTool Package type to CodeGeneration.Tools package

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#330]
This will enable NuGet to install this package as a CLI tool to the project.

**Comment by natemcmaster** [comment]
Since dotnet-pack for PJ doesn't support this yet, our other tools do this with .nuspec + nuget.exe.

**Comment by prafullbhosale** [comment]
https://github.com/aspnet/Scaffolding/commit/a5b65f47c88873c93f70a9e698a71d7bb001d56d
