### ISSUE TITLE
Scaffolding MVC controller using EF crashes for 1.1

### ISSUE THREAD

**Issue by smitpatel** [aspnet/Scaffolding#342]
Repro steps:
1. Create new web application using individual accounts. (I am using .Net Core Preview 2 tooling).
This will generate template web app using 1.0.0 packages.
2. Update all packages to 1.1.0/1.1.0-preview4-final as applicable.
3. Add new class Post.cs under models. (any properties are fine).
4. Right click controllers folder, Add->Controller, MVC controller with views, using Entity Framework.
5. Give model class as Post.cs and Data context class as ApplicationDbContext.

Nothing happens. Doing same controller add actions in 1.0.0 adds a new controller & views in the solution.
Trying to execute the command manually (taken from output window)
`dotnet aspnet-codegenerator --project "c:\users\smpatel\documents\visual studio 2015\Projects\WebApplication2\src\WebApplication2" controller --force --controllerName PostsController --model WebApplication2.Models.Post --dataContext WebApplication2.Data.ApplicationDbContext --relativeFolderPath Controllers --controllerNamespace WebApplication2.Controllers --referenceScriptLibraries --useDefaultLayout`
shows aspnet-codegenerator.exe has crashed.

**Comment by prafullbhosale** [comment]
@smitpatel Could you provide the error message as well? 

I tried it with the configuration you mentioned.
I did not hit any issues while scaffolding.
The only additional step I did was to install the [.Net Core 1.1](https://www.microsoft.com/net/download/core)

**Comment by smitpatel** [comment]
While using VS dialogue box, the controller was not created. Running command as shown up, brings up system dialogue box of program failure.

**Comment by prafullbhosale** [comment]
I see, can you provide more information regarding the OS and dotnet cli version?

**Comment by smitpatel** [comment]
Following is the dotnet by default from `global.json`
```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```
I also tried using newer dotnet
```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by wstaelens** [comment]
same problem. can't add a controller now.
My config:
```
{
  "userSecretsId": "aspnet-:-)",

  "dependencies": {
    "BundlerMinifier.Core": "2.2.306",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.NETCore.App": "1.1.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": "1.1.0-preview4-final",
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.1.0-preview4-final"
  },

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final"
  },

  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },
  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },
  "runtimes": {
    "win10-x64": {}
  }
}
```

**Comment by prafullbhosale** [comment]
@wstaelens ,looks like your project.json is missing the `Microsoft.VisualStudio.Web.CodeGeneration.Tools` package in the `tools` section.

Can you try to add the below to the tools section and see if it works? 

```json
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.1.0-preview4-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    }
```

**Comment by wstaelens** [comment]
Thanks @prafullbhosale I also had to reinstall the runtime https://www.microsoft.com/net/download/core#/current/runtime
