### ISSUE TITLE
[Feature] Scaffold ViewComponent

### ISSUE THREAD

**Issue by Eilon** [aspnet/Scaffolding#360]
_From @RandyBuchholz on December 14, 2016 16:48_

This may be in the works. I didn't see an item for it, so I thought I would add one. In Visual Studio it would be nice to have -> Add New Item -> .Net Core -> ASP.NET -> MVC ViewComponent that would add a folder, ViewComponent Class, and .cshtml page for us. 

_Copied from original issue: aspnet/Mvc#5616_

**Comment by mlorbetske** [comment]
@sayedihashimi thoughts?

**Comment by vijayrkn** [comment]
We do have razor pages and razor views item templates. Closing.
