### ISSUE TITLE
[Tracking] Deprecate DotnetToolDispatcher sources package.

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#362]
This is a tracking issue to deprecate the DotNetToolDispatcher sources package once the feature/msbuild branch of scaffolding is merged to dev.

cc @natemcmaster

**Comment by natemcmaster** [comment]
We can do this now, right?

**Comment by prafullbhosale** [comment]
Yes, dev branch is now up-to date with the msbuild changes.
