### ISSUE TITLE
Re-enable tests in the dev branch once shared runtime version is sorted

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Scaffolding#371]
This might not be relevant once we merge the msbuild branch in to dev, but tests are broken due to https://github.com/dotnet/corefx/issues/14696. Disabling these to unblock the build.

**Comment by prafullbhosale** [comment]
@pranavkm Closing this now. 
Tests are running on the dev branch. 
Feel free to reopen if I am missing something here.
