### ISSUE TITLE
Errors creating new Api Controller

### ISSUE THREAD

**Issue by Eilon** [aspnet/Scaffolding#372]
_From @MartinMason on December 30, 2016 23:31_

Creating a new AspNetCore project in Visual Studio 2015, add a new class, try to create a new scaffolded Api Controller, this error is received. I can reproduce everything stated in this post. Have tried every solution produced and nothing works. Creating an empty Api controller succeeds. Tooling preview 2 is dire need of an update.

http://stackoverflow.com/questions/41022748/asp-net-core-adding-controller-using-entity-framework

_Copied from original issue: aspnet/Mvc#5647_

**Comment by MartinMason** [comment]
I'm not exactly sure what I did to resolve this issue as it's now gone away. The following steps were executed.

- Deleted files in the ComponentModelCache folder and let VS rebuild them: C:\Users\{UserName}\AppData\Local\Microsoft\VisualStudio\14.0\ComponentModelCache

- Updated tooling from this link: https://www.microsoft.com/net/download/core

- Properly configured DbContext following this link. Verified that DI for DbContext working properly in another controller and realized that had fat fingered appsettings file (Don't think this was the only problem as a new file using Ind. Account Authentication failed initially.)

Now everything is working. Please close issue.

**Comment by Eilon** [comment]
Ok!
