### ISSUE TITLE
Scaffolding fails System.IO.FileTooLongException

### ISSUE THREAD

**Issue by pholly** [aspnet/Scaffolding#377]
Visual Studio 2015
ASP.NET core 1.1
.NET framework 4.6.2

If there are nested folders in your project that exceed max file/path length scaffolding will fail on the Build step. I used Visual Studio to try to scaffold a Entity Framework Controller. I had a `node_modules` folder that had folders nested way too deep.

Verified that when I deleted the `node_modules` folder I was able to add a EF controller. 

Excluding `node_modules` from my `project.json` didn't change anything.

I now realize I can call `dotnet aspnet-codegenerator` with a `--no-build` flag. I didn't try it but because I get the error in a build step I'm pretty sure that would solve my problem.

**Comment by mlorbetske** [comment]
Thanks for the heads up, passing `--no-build` in this situation (after having otherwise built your application) is the appropriate course of action
