### ISSUE TITLE
Solution crashes VS 2017 RC3

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Scaffolding#381]
I updated the `feature/msbuild` branch in my fork of the repo. I then opened the solution in VS 2017 RC3 and opened file `src\Microsoft.VisualStudio.Web.CodeGenerators.Mvc\Templates\ViewGenerator\Edit.cshtml`. About 5 seconds later, the IDE crashed and restarted:

![scaffolding_crash](https://cloud.githubusercontent.com/assets/10702007/22053287/8da848da-dd04-11e6-8290-170f21a2a895.png)

@prafullbhosale

**Comment by natemcmaster** [comment]
feature/msbuild is currently only compatible with RC.2. We are working to upgrade to RC.3 but have run into blocking issues in RC.3, such as https://github.com/NuGet/Home/issues/4321

**Comment by scottaddie** [comment]
Confirmed that this was fixed by https://github.com/aspnet/Scaffolding/pull/387
