### ISSUE TITLE
Visual Studio can't find dotnet-aspnet-codegenerator-design

### ISSUE THREAD

**Issue by jamesqo** [aspnet/Scaffolding#402]
Hi, I'm currently learning ASP.NET. I have been following the tutorials at https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model. When I try to create a Controller as described in the tutorial, I run into this error:

![aspnet](https://cloud.githubusercontent.com/assets/9159214/22859050/c7a91328-f09d-11e6-8e24-7a7862e0dd54.PNG)

I have googled about this and found [this SO question](http://stackoverflow.com/q/41450148/4077294), but the suggestions didn't seem to work. I also tried creating a new VS project.

**Additional info:** I'm using Visual Studio 2017 with a .csproj project file. My project targets .NET Core 1.0.

**Comment by prafullbhosale** [comment]
@jamesqo, for `csproj` based project system, you need to have the below in your project:

```xml
<ItemGroup>
  <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.0.0-msbuild3-final" />
  <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0-msbuild3-final" />
</ItemGroup>
```

Also make sure that the below packages are not referenced in the project as `PackageReferences`:

`Microsoft.VisualStudio.Web.CodeGenerators.Mvc`
`Microsoft.VisualStudio.Web.CodeGeneration.Tools`

Let me know if this helps.

**Comment by jamesqo** [comment]
@prafullbhosale Thank you very much for your help. I followed your advice and this error isn't occurring anymore. However, now I'm getting a different stack trace:

![stacktrace](https://cloud.githubusercontent.com/assets/9159214/23090075/e05d5266-f562-11e6-8cdb-dbb2a305180b.PNG)

**Comment by jamiewest** [comment]
Here is what I had to do to get this library working using .csproj. using VS Code with cli 1.0.0-rc4-004771.

1. Add @prafullbhosale example for adding the design package.
2. Add the following to fix the "Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.0" error I was receiving. @jamesqo I am not sure if this step will help in VS but who knows...

```xml
<PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <PackageTargetFallback>portable-net45;win8;wp8;wpa81</PackageTargetFallback>
  </PropertyGroup>
```
My final product looked like this for a basic Mvc app:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <PackageTargetFallback>portable-net45;win8;wp8;wpa81</PackageTargetFallback>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.0" />
  </ItemGroup>
  <ItemGroup>
      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.0.0-msbuild3-final" />
      <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0-msbuild3-final" />
  </ItemGroup>
</Project>

**Comment by SahadatHHredoy** [comment]
dotnet tool install --global dotnet-aspnet-codegenerator --version 3.1.2
