### ISSUE TITLE
Possible to use on Mac?

### ISSUE THREAD

**Issue by martinalderson** [aspnet/Scaffolding#409]
Either with VSCode or VSMac?

**Comment by prafullbhosale** [comment]
@martinalderson Currently VSCode and VSMac do not have the feature to use scaffolding. 
But scaffolding can be done using command line.

From the project folder run the below commands: 
`dotnet aspnet-codegenerator --project <projectname>.csproj -h`
#### For scaffolding controllers
`dotnet aspnet-codegenerator --project <projectname>.csrproj controller -h`
#### For scaffolding views
`dotnet aspnet-codegenerator --project <projectname>.csrproj view -h`

**Comment by martinalderson** [comment]
Can this be done on an entity by entity basis on the command line?

**Comment by prafullbhosale** [comment]
Not sure if I understood your question correctly, but you can scaffold controllers/ views based on EF models.

**Comment by prafullbhosale** [comment]
Closing this. Feel free to re-open if there are any more questions.

**Comment by JaapWeijland** [comment]
When I use 

`dotnet aspnet-codegenerator`

It says:

`No executable found matching command "dotnet-aspnet-codegenerator"`

I am running it on my mac. I've already installed dotnet on my machine but the generator won't work.

**Comment by mtcantero** [comment]
Same issue here

**Comment by prafullbhosale** [comment]
@JaapWeijland, @mtcantero, can you confirm if the `csproj` file of your project contains the following

```xml
<ItemGroup>
  <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.1" />
</ItemGroup>
```

**Comment by mtcantero** [comment]
I can confirm I have it, here is part of my csproj file

```
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="1.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.1.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Msbuild" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.1" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
  </ItemGroup>
```

**Comment by prafullbhosale** [comment]
@mtcantero, Can you try a few more things as below: 

1. Run `dotnet restore` on the csproj file and see if there are any errors. 
2. Check in the local nuget package cache folder if a `.tools` folder exists and has a folder named `microsoft.visualstudio.web.codegeneration.tools`
3. Run `dotnet ef -h` to see if it fails with a similar error.

**Comment by mtcantero** [comment]
@prafullbhosale I think we are getting close, I don´t have the `.tools` folder, should I just create it and run again `dotnet restore`

3. It fails with a very similar error

**Comment by prafullbhosale** [comment]
>  I don´t have the .tools folder, should I just create it and run again dotnet restore

`dotnet restore` should create that folder for you. 
Can you paste the output of running `dotnet restore` here? 
Also the output of `dotnet --info` ?

**Comment by mtcantero** [comment]
output of `dotnet --info`

```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4
```

And output of dotnet restore
```
  Restoring packages for /Users/user/Projects/Taskato/Xamarin and Core Approach/Taskato/TaskatoWebAPI/TaskatoWebAPI.csproj...
  Restoring packages for /Users/user/Projects/Taskato/Xamarin and Core Approach/Taskato/TaskatoWebAPI/TaskatoWebAPI.csproj...
  Restoring packages for /Users/user/Projects/Taskato/Xamarin and Core Approach/Taskato/TaskatoWebAPI/TaskatoWebAPI.csproj...
  Restore completed in 885.58 ms for /Users/user/Projects/Taskato/Xamarin and Core Approach/Taskato/TaskatoWebAPI/TaskatoWebAPI.csproj.
  Restore completed in 932.62 ms for /Users/user/Projects/Taskato/Xamarin and Core Approach/Taskato/TaskatoWebAPI/TaskatoWebAPI.csproj.
  Lock file has not changed. Skipping lock file write. Path: /Users/user/Projects/Taskato/Xamarin and Core Approach/Taskato/TaskatoWebAPI/obj/project.assets.json
  Restore completed in 2.3 sec for /Users/user/Projects/Taskato/Xamarin and Core Approach/Taskato/TaskatoWebAPI/TaskatoWebAPI.csproj.
```
  
  NuGet Config files used:
      /Users/user/.nuget/NuGet/NuGet.Config
  
  Feeds used:
      https://api.nuget.org/v3/index.json

**Comment by prafullbhosale** [comment]
Ah, sorry, forgot to mention, you need to delete the `obj` folder under your project before running `dotnet restore`.

**Comment by mtcantero** [comment]
My fault sorry forgot to do it

Here is the output now

```
Restoring packages for /Users/user/Projects/Taskato/Xamarin and Core Approach/Taskato/TaskatoWebAPI/TaskatoWebAPI.csproj...
  Restoring packages for /Users/user/Projects/Taskato/Xamarin and Core Approach/Taskato/TaskatoWebAPI/TaskatoWebAPI.csproj...
  Restoring packages for /Users/user/Projects/Taskato/Xamarin and Core Approach/Taskato/TaskatoWebAPI/TaskatoWebAPI.csproj...
  Restore completed in 829.11 ms for /Users/user/Projects/Taskato/Xamarin and Core Approach/Taskato/TaskatoWebAPI/TaskatoWebAPI.csproj.
  Restore completed in 806.15 ms for /Users/user/Projects/Taskato/Xamarin and Core Approach/Taskato/TaskatoWebAPI/TaskatoWebAPI.csproj.
  Generating MSBuild file /Users/user/Projects/Taskato/Xamarin and Core Approach/Taskato/TaskatoWebAPI/obj/TaskatoWebAPI.csproj.nuget.g.props.
  Generating MSBuild file /Users/user/Projects/Taskato/Xamarin and Core Approach/Taskato/TaskatoWebAPI/obj/TaskatoWebAPI.csproj.nuget.g.targets.
  Writing lock file to disk. Path: /Users/user/Projects/Taskato/Xamarin and Core Approach/Taskato/TaskatoWebAPI/obj/project.assets.json
  Restore completed in 2.42 sec for /Users/user/Projects/Taskato/Xamarin and Core Approach/Taskato/TaskatoWebAPI/TaskatoWebAPI.csproj.
  
  NuGet Config files used:
      /Users/mariotrueba/.nuget/NuGet/NuGet.Config
  
  Feeds used:
      https://api.nuget.org/v3/index.json
```

**Comment by LouisLee1983** [comment]
dotnet 2.1 已经没有了这个codegenerator
