### ISSUE TITLE
codegen crashes if out param variable is created in function call

### ISSUE THREAD

**Issue by Eilon** [aspnet/Scaffolding#410]
_From @ghosttie on February 28, 2017 23:46_

If I create an out param variable in the function call:

```
			if (Guid.TryParse(stringValue, out var valueAsGuid)) {
```

I get this exception:

> There was an error running the selected code generator:
> 'There was an error creating a DbContext :C:\Users\jmunro\Dropbox\Work\projects\asp.net\FileVision Application Server\FileVision Application Server\GuidHeaderModelBinder.cs(20,43): error CS1003: Syntax error, ',' expected
> C:\Users\jmunro\Dropbox\Work\projects\asp.net\FileVision Application Server\FileVision Application Server\GuidHeaderModelBinder.cs(20,39): error CS0103: The name 'var' does not exist in the current context
> C:\Users\jmunro\Dropbox\Work\projects\asp.net\FileVision Application Server\FileVision Application Server\GuidHeaderModelBinder.cs(20,43): error CS0103: The name 'valueAsGuid' does not exist in the current context
> C:\Users\jmunro\Dropbox\Work\projects\asp.net\FileVision Application Server\FileVision Application Server\GuidHeaderModelBinder.cs(21,56): error CS0103: The name 'valueAsGuid' does not exist in the current context
>    at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
>    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
>    at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)'

but if I declare the variable separately:

```
			var valueAsGuid = Guid.Empty;
			if (Guid.TryParse(stringValue, out valueAsGuid)) {

```
there's no exception.

_Copied from original issue: aspnet/Mvc#5869_

**Comment by Eilon** [comment]
@ghosttie is this happening while you're running the "Add View" or "Add Controller" scaffolding feature?

**Comment by Eilon** [comment]
_From @ghosttie on March 1, 2017 1:32_

"Add Controller" - sorry, should have specified

**Comment by mlorbetske** [comment]
@sayedihashimi it sounds like this is an issue with attempting to use C# 7 features in projects that scaffolding is dependent on in the case that the project targets something lower than `net46`. Would the appropriate course of action here be to drop support for scaffolding in projects that target a lower full framework than 4.6?

**Comment by jholovacs** [comment]
Still having this problem...
