### ISSUE TITLE
Scaffolding fails with could not load System.Runtime version 4.2.0.0

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/Scaffolding#416]
From @twsouthwick at https://github.com/aspnet/Tooling/issues/1009

After removing the environment variable in #1008, I'm still getting an error, although a different one.

# Steps to reproduce
- Launch VS (I'm using a clean install of 15.0.26228.0)
- Create an ASP.NET Core application (.NET Core App 1.1)
- In project view, right click Controllers ->Add->New Scaffolded Item and then select MVC Controller - Empty
- First time, select "Full dependencies", then repeat and fill in name

## Expected behavior
New controller should be generated

## Actual behavior
Get an error:

```
Error

There was an error running the selected code generator: 'Could not load file or assembly 'System.RUntime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f...'. The system cannot find the file specified at...
```

![image](https://cloud.githubusercontent.com/assets/583206/23524034/d38fade2-ff3d-11e6-9d7a-c29a3576e52d.png)

**Comment by mlorbetske** [comment]
@twsouthwick could you try clearing your NuGet cache please? You can find the button to do this at the bottom of the settings page in `Tools -> Options -> NuGet Package Manager -> General`

**Comment by Sentinent** [comment]
Clearing the cache fixed the problem for me, could you explain why?

**Comment by mlorbetske** [comment]
This comes from a bad copy of the BrowserLink package that made it in to the CLI. When scaffolding runs, it causes a restore and build to be done by the CLI, which causes its first run experience to run, which attempts to put the bad package in the NuGet cache. Scaffolding then attempts to run the app to collect information about the available data contexts that get configured in the app's startup. If the CLI did not find BrowserLink in the cache & placed the bad package, the app gets restored with the bad package & then fails to run due to the .UseBrowserLink() call in the startup generated by the templates. Clearing the NuGet cache via VS ultimately ends up causing VS to place the BrowserLink package in the cache (when the app gets restored the next time), preventing the CLI from putting the bad package there, avoiding the issue.
