### ISSUE TITLE
Page encoding changed automatic

### ISSUE THREAD

**Issue by capadong** [aspnet/Scaffolding#418]
Creating some page by Scaffolding in vs2017.
The page encoding is UTF8  default.
But,it will automatically changed to ANSI  when clicking `ctrl + s` with  Chinese characters.

**Comment by mlorbetske** [comment]
@capadong could you elaborate on the type of page you created and was it added via the "Add Scaffolded Item" gesture? Also, is this a .NET Core project?

**Comment by capadong** [comment]
@mlorbetske  yes,i add the page through "Add Scaffolded Item".And i test another way,select "Add view..." by right click on the action in controller,same result.
 The pictures:
**before**
![image](https://cloud.githubusercontent.com/assets/8233679/24082086/d178c37a-0cfa-11e7-9700-a5fa0df58aa4.png)
**after**
![image](https://cloud.githubusercontent.com/assets/8233679/24082160/ced26418-0cfb-11e7-85b1-4f747ea0292d.png)

**project stucture**
![image](https://cloud.githubusercontent.com/assets/8233679/24082195/69416c60-0cfc-11e7-90e6-f93cc920c5b0.png)

**Comment by vijayrkn** [comment]
Page encoding should be consistent now. Please reopen if the behavior you are seeing is different.
