### ISSUE TITLE
Debugging scaffolding .net core

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#419]
From @ali-raza-iftikhar on https://github.com/prafullbhosale/EmptyControllerAndViewScaffolder/issues/1
What is the way to debug scaffolding?

**Comment by prafullbhosale** [comment]
@ali-raza-iftikhar, the below steps are what I use for debugging.
Let me know if you hit any issues with this. 

#### Steps for debugging
1.	Add the above line of code in a place that is before where you want the first breakpoint. 
```cs
while (!System.Diagnostics.Debugger.IsAttached){ }
```
2.	Build the packages (run ‘build /t:compile’ on the repo)
3.	Create a new web project (or use an existing one).
a.	Add a new NuGet.config file to point to the artifacts\build folder under the repo directory.
b.	Update the version numbers for the scaffolding packages in the project to pick up latest.
4.	Open Scaffolding solution in VS (another instance if project is open in VS) and add a break point. 
5.	Scaffold from VS or command line. 
6.	From scaffolding solution, attach debugger to `dotnet.exe` (there maybe multiple, but ususally this is the one on top of the list). 
a.	Need to figure out if the code is in inside man or the CLI tool and attach accordingly. 
b.	If project is targeting full framework and the break point is in the inside man code, the process name is dotnet-aspnet-codegenerator-design.exe
7.	The break point should hit. 

Some common issues when debugging doesn’t hit the breakpoint: 
- The `dotnet.exe` process to which we attach isn’t correct
    - This typically happens if some other dotnet command is launched after scaffolding was launched (running scaffolding commandline first and then opening scaffolding solution will always cause the topmost dotnet process to be one launched by VS.)
- The version of package in the project isn’t correct. 
  - You can check this by inspecting the project.assets.json of the project and comparing it with the latest package created in the artifacts folder.

**Comment by ali-raza-iftikhar** [comment]
I will try. but thanks in advance for writing detailed explanation.

**Comment by ali-raza-iftikhar** [comment]
I trying to understand the point two getting error. "'build' is not recognized as an internal or external command,". Can you explain it. I am using VS2017. Further help will be appreciated. :-)

**Comment by ali-raza-iftikhar** [comment]
I have just one issue. Which i don't think belongs to you/scaffolding. But hopefully you can help me for that. I am trying to create scaffolding package from VS2017 pack. I want template folder to be included as well. How i can achieve that?

**Comment by prafullbhosale** [comment]
> I want template folder to be included as well. How i can achieve that?

You would need to specify the files to be included as part of the package in the csproj file. 
Take a look at https://github.com/aspnet/Scaffolding/blob/dev/src/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/Microsoft.VisualStudio.Web.CodeGenerators.Mvc.csproj#L13-L15

**Comment by ali-raza-iftikhar** [comment]
Awesome thanks brother 👍

**Comment by prafullbhosale** [comment]
Closing this.
