### ISSUE TITLE
Creating duplicate files on selecting opting "Add MVC Dependencies"?

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#423]
From @nithinbandaru1 on https://github.com/dotnet/core/issues/514

Hi,
When I am trying to create new controller for first time it gives me option to add mvc dependencies with two options as shown in image below.
![full dependencies](https://cloud.githubusercontent.com/assets/25755972/23202805/ce27add4-f905-11e6-8394-4e64745c37e0.PNG)

Now when I select full dependencies option it is adding duplicate files like:
ViewImport.cshtml though there is ViewImports.cshtml
Layout.cshtml though there is _Layout.cshtml
I think It should add those files only if the files are not present.
NOTE: This option doesn't popup when I create using Add -->New item-->Controller. It only happens when I do Add-->Controller(shortcut) .
Looks like a bug for me. Is it?

**Comment by prafullbhosale** [comment]
From @danroth27 https://github.com/dotnet/core/issues/514#issuecomment-285723019
Yeah, this dialog is super confusing when you already have MVC included in a project.
@barrytang @sayedihashimi Please take a look

**Comment by prafullbhosale** [comment]
From @olivier-voutat 

https://github.com/dotnet/core/issues/514#issuecomment-287001601
And why entity framework is in the dependencies? I have a very special scenario where I just cannot use EntityFramework...

https://github.com/dotnet/core/issues/514#issuecomment-287002851
And in the scaffolding file it is written:
Add Scaffolding CLI tool to the project:
<ItemGroup>
<DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
</ItemGroup>
But when I try to do it, it says that is not supported.

https://github.com/dotnet/core/issues/514#issuecomment-287012135
My bad. Now I understood. Add manually to project file... :-P
But when I try to add manually "Microsoft.VisualStudio.Web.CodeGeneration.Design" I get this error.
Restoring packages for C:\Development\CustomerCenter\Assura.CustomerCenter.WebApp\Assura.CustomerCenter.WebApp.csproj...
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETCoreApp,Version=v1.1.
Package restore failed. Rolling back package changes for 'Assura.CustomerCenter.WebApp'.
Time Elapsed: 00:00:00.8155988
========== Finished ==========
But the "Add MVC Dependencies" is able to install it.

**Comment by prafullbhosale** [comment]
@nithinbandaru1 
> Now when I select full dependencies option it is adding duplicate files like:
ViewImport.cshtml though there is ViewImports.cshtml
Layout.cshtml though there is _Layout.cshtml
I think It should add those files only if the files are not present.
NOTE: This option doesn't popup when I create using Add -->New item-->Controller. It only happens when I do Add-->Controller(shortcut) .
Looks like a bug for me. Is it?

Yes, the extra files added (ViewImport.cshtml and Layout.cshtml) is a bug in scaffolding. 

@danroth27 
> Yeah, this dialog is super confusing when you already have MVC included in a project.

We do want to revisit the dialog to improve the experience. Right now the dialog is a shared dependency installer between the Empty web project and MVC/ Web API projects that do not have necessary dependencies for scaffolding to work.

**Comment by prafullbhosale** [comment]
@olivier-voutat
>And why entity framework is in the dependencies? I have a very special scenario where I just cannot use EntityFramework...

The scaffolding packages have a dependency on EnitytFrameworkCore, hence the need for EF package.

> But when I try to add manually "Microsoft.VisualStudio.Web.CodeGeneration.Design" I get this error.

For the Microsoft.VisualStudio.Web.CodeGeneration.Design package, you would need to also add the below to the csproj file manually: 

```xml
<PropertyGroup>
  <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8</PackageTargetFallback>
</PropertyGroup>
```

The Add MVC dependencies adds this property to the csproj file before installing the package

**Comment by scottaddie** [comment]
@prafullbhosale Is this the same issue as described in https://github.com/aspnet/Scaffolding/issues/411?

**Comment by prafullbhosale** [comment]
> Is this the same issue as described in #411?

Yes, that is correct. Closing this as a dupe of #411
