### ISSUE TITLE
Mandatory property in OptionAttribute.

### ISSUE THREAD

**Issue by ali-raza-iftikhar** [aspnet/Scaffolding#431]
Hi I want to add IsMandatory property, to write generic function for model validation on the base of this property value.
I am trying like this but its not working in my custom scaffolding

    public class MyCustomAttribute : OptionAttribute
    {
        public bool IsMandatory { get; set; }
    }

Is their a way to achieve this ? @prafullbhosale

**Comment by prafullbhosale** [comment]
I am not sure I fully understand the question here. Is this attribute going to be used for decorating the properties of the model that will be used for scaffolding? 
If so, there is an existing attribute `[Required]` which specifies the same thing.

**Comment by ali-raza-iftikhar** [comment]
Thanks. It worked.

**Comment by prafullbhosale** [comment]
Closing this.
