### ISSUE TITLE
Create class object from reading .cs model file.

### ISSUE THREAD

**Issue by ali-raza-iftikhar** [aspnet/Scaffolding#432]
I want to read the domain model file, so i can convert it to class object and do further operation for scaffolding. Need help for achieving this. Thanks in advance.

**Comment by ali-raza-iftikhar** [comment]
After working lot of work.  I have been able to read the .cs model file using
"Microsoft.CodeAnalysis.CSharp;"

var synTree = SyntaxFactory.ParseSyntaxTree(classString);
            var root = (CompilationUnitSyntax)synTree.GetRoot();
            var myClass = root.DescendantNodes().OfType<ClassDeclarationSyntax>().FirstOrDefault();

**Comment by prafullbhosale** [comment]
@ali-raza-iftikhar glad you could make it work! 
Closing this issue.
