### ISSUE TITLE
CLI tool package dependencies for 2.0

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#437]
Currently the CLI tool package targets `netcoreapp1.0` and has dependencies on packages from `1.0.x` train.
Given the requirement that the CLI tool must target `netcoreapp1.0` https://github.com/NuGet/Home/issues/4396, should the CLI Tool package dependencies be updated to use the packages from 2.0 runtime? 

cc @Eilon @natemcmaster @mlorbetske @muratg

**Comment by prafullbhosale** [comment]
Related https://github.com/aspnet/DotNetTools/issues/281

**Comment by muratg** [comment]
@prafullbhosale Are we tracking this for 2.0.0-preview1?  @Eilon I assume the blocking bugs are tracked with DJS?

cc @bricelam how about EF tooling?

**Comment by bricelam** [comment]
Haven't checked yet...

**Comment by Eilon** [comment]
We are awaiting guidance from the NuGet & CLI teams on the way to do this. It requires some changes/features that are apparently not yet done, but might be done this week.

**Comment by prafullbhosale** [comment]
Fixed by : https://github.com/aspnet/Scaffolding/pull/460
