### ISSUE TITLE
Injecting my own interface in the code generator class

### ISSUE THREAD

**Issue by ali-raza-iftikhar** [aspnet/Scaffolding#440]
```
  public NovaCore(IServiceProvider serviceProvider,
            IApplicationInfo applicationInfo,
            ICodeGeneratorActionsService codeGeneratorActionsService,
            IProjectContext projectContext,
            ILogger logger, ICommonInterface common)
```
What is the way to do inject ICommonInterface?

Currently getting this error
There was an error creating the code generator instance: for type "ICommonInteface"

**Comment by prafullbhosale** [comment]
The best place to do this right now would be inside the constructor of your CodeGenerator class.

```cs
     ICommonInterface common = ConstructCommon();
     serviceProvider.Add<ICommonInterface>(common);
```
Then it would be available for other components. 

I will look into adding an extension point that will allow custom scaffolders to register any services they would like.
