### ISSUE TITLE
dotnet aspnet-codegenerator  scaffolder should be consistent with VS version

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Scaffolding#441]
`dotnet aspnet-codegenerator` generates views with
```
@{
    Layout = null;
}
```
It should not nuke the layout file.

It should generate the following markup

```
@{
    ViewData["Title"] = "<View/action method name here>";
}
```

At least that should be an option.

**Comment by prafullbhosale** [comment]
@Rick-Anderson, VS invokes the `dotnet aspnet-codegenerator`. 
You would have to compare the command line parameters passed in by VS. 
In this case, `--useDefaultLayout` switch will make what you need happen.

**Comment by prafullbhosale** [comment]
@Rick-Anderson Closing this. Feel free to reopen this if needed.
