### ISSUE TITLE
dotnet aspnet-codegenerator scaffolder should put controller in controllers folder

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Scaffolding#442]
`dotnet aspnet-codegenerator scaffolder` puts the controller in the project directory and the views in the correct location (*Views* folder)

`dotnet aspnet-codegenerator controller -name Controllers/MoviesController  -m Movie -dc MvcMovieContext`

puts the controller in the correct folder, but then the views are in the wrong place.

**Comment by prafullbhosale** [comment]
@Rick-Anderson You would need to pass in `--relativeFolderPath`  option to tell which folder to generate the controller in. 
```
dotnet aspnet-codegenerator controller -name MoviesController -m Movie -dc MvcMovieContext --relativeFolderPath Controllers
```

**Comment by prafullbhosale** [comment]
Closing this.

**Comment by OlfaMKADMINI** [comment]
how can I generate two controllers in the same command !!
