### ISSUE TITLE
Remove references to Microsoft.DotNet.InternalAbstractions

### ISSUE THREAD

**Issue by Eilon** [aspnet/Scaffolding#445]
Microsoft.DotNet.InternalAbstractions was refactored and renamed as part of 1.1 to Microsoft.DotNet.PlatformAbstractions. We should update our code to no longer reference this package:

https://github.com/aspnet/Scaffolding/search?utf8=%E2%9C%93&q=Microsoft.DotNet.InternalAbstractions&type=

**Comment by prafullbhosale** [comment]
This should be fixed with #460
