### ISSUE TITLE
Trim feeds from NuGet.config

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Scaffolding#446]
We shouldn't need all the additional feeds in the NuGet.config. Additional components should be mirrored so any consumer of the package doesn't have to additionally list feeds.

**Comment by Eilon** [comment]
Yeah we should clean up the NuGet.config to use only the minimum references.

@pranavkm - should it have anything but what we use in the other repos, e.g. https://github.com/aspnet/Mvc/blob/dev/NuGet.config ?

**Comment by pranavkm** [comment]
Once we address https://github.com/aspnet/CoreCLR/issues/180, probably not.

**Comment by Eilon** [comment]
@prafullbhosale - any action planned for Preview1 here?

**Comment by prafullbhosale** [comment]
@Eilon, yes. Don't have access aspnet/CoreCLR repo so don't know the status of the issue above. If that's done, I can make changes now.

**Comment by Eilon** [comment]
You should have access now. But no, it wasn't done yet.

**Comment by Eilon** [comment]
Is this something critical for Preview1? Do we risk building against the wrong things if this isn't done?

**Comment by prafullbhosale** [comment]
Potentially, if the additional feeds have higher versions of dependencies than we intend to ship for Preview1.

**Comment by Eilon** [comment]
Ok, @prafullbhosale can you take a look to see what happens if the extra feeds are removed from https://github.com/aspnet/Scaffolding/blob/rel/2.0.0-preview1/NuGet.config ?

Why does it need feeds such as the patch feed?
