### ISSUE TITLE
Add Razor Pages versions of the MVC scaffolders

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Scaffolding#457]
We need to add Razor Pages versions of the existing MVC scaffolders to the MVC scaffolders package.

@mlorbetske @rynowak

**Comment by DamianEdwards** [comment]
BTW I intended for this to be a preview-2 item.

**Comment by prafullbhosale** [comment]
Spec: https://gist.github.com/prafullbhosale/90aa0f7ee3dd09243067112c2f600749

**Comment by DamianEdwards** [comment]
I've moved this to 2.0.0 for now as we're shutting down preview2. Let's sync up on the status so we can determine if it fits in 2.0.0 at all.

**Comment by Eilon** [comment]
Removing from milestone because this milestone already shipped.

**Comment by vijayrkn** [comment]
This is already available in the product. Closing.
