### ISSUE TITLE
"Disable tests that need loading assemblies in insideman"

### ISSUE THREAD

**Issue by reezonew** [aspnet/Scaffolding#458]
"Disable tests that need loading assemblies in insideman", it is the comment in source code.
What does that mean?
How to load assemblies in insideman?

**Comment by prafullbhosale** [comment]
@reezonew, The message "Disable tests that need loading assemblies in insideman" was a `Skip=<Reason>` message for disabled tests. 

> How to load assemblies in insideman?

Could you please elaborate on what is needed here?

**Comment by reezonew** [comment]
@prafullbhosale Sorry about that.
There is a test named TestControllerWithContext() in E2E_Test. I can't run it. I thought there is something to do with the comment. Below is the cod snippet.
`        [Fact (Skip ="Disable tests that need loading assemblies in insideman")]
        public void TestControllerWithContext()
        {
            using (var fileProvider = new TemporaryFileProvider())
            {
                new MsBuildProjectSetupHelper().SetupProjects(fileProvider, Output);
                TestProjectPath = Path.Combine(fileProvider.Root, "Root");
                var args = new string[]
                {
                    "aspnet-codegenerator",
                    "-p",
                    TestProjectPath,
                    "controller",
                    "--controllerName",
                    "CarsController",
                    "--model",
                    "Library1.Models.Car",
                    "--dataContext",
                    "WebApplication1.Models.CarContext",
                    "--noViews"
                };

                Scaffold(args, TestProjectPath);
                var generatedFilePath = Path.Combine(TestProjectPath, "CarsController.cs");
                VerifyFileAndContent(generatedFilePath, "CarsController.txt");
            }
        }
`

**Comment by prafullbhosale** [comment]
Ah, I see. The test was disabled by adding `(Skip ="Disable tests that need loading assemblies in insideman")` to the `Fact` attribute, due to an issue which caused these tests to fail on the CI machines. 

The issue has been fixed and the test is now re-enabled. 
If you sync the latest code from `dev` branch, you should be able to run this test.

**Comment by prafullbhosale** [comment]
Closing this issue now. Feel free to re-open if you face any issues.
