### ISSUE TITLE
React to changes in DbContext discovery in EntityFrameworkCore

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#467]
- Scaffolding should add a `<DbContextClassName>Factory.cs`  to the project while creating a new DbContext.
  - See: dotnet/templating#695 & dotnet/templating#705 for content of the class. 

Related: 
- aspnet/EntityFramework#8314
- aspnet/EntityFramework#8326
- #466 

cc @mlorbetske, @Eilon

**Comment by Eilon** [comment]
@prafullbhosale - is this issue done?

**Comment by prafullbhosale** [comment]
Yes, https://github.com/aspnet/Scaffolding/commit/a6414d24afba24309c099105bd35b3dca4a4f415.
I thought this would have been auto closed when changes got merged to `dev`, but I guess not.
