### ISSUE TITLE
Scaffolding should stop adding IDbContextFactory implementation for 2.0

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#485]
EF plans to change DbContext creation during design time to not require an `IDbContextFactory` implementation. 
When that happens scaffolding needs to stop creating a factory for the newly added DbContext.

Related: https://github.com/aspnet/DependencyInjection/issues/524

cc @bricelam, @mlorbetske

**Comment by bricelam** [comment]
PR aspnet/EntityFramework#8510 is in. Scaffolding can stop adding IDbContextFactory.
