### ISSUE TITLE
Decouple IModelTypesGenerator from roslyn

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Scaffolding#49]
https://github.com/aspnet/Scaffolding/blob/dev/src/Microsoft.Framework.CodeGeneration.Core/IModelTypesLocator.cs#L9

This code needs to be more generic not assuming roslyn anywhere. There should be a POCO type that is used in the interface and a roslyn implementation that can turn ITypeSymbol into the POCO type.

**Comment by borgdylan** [comment]
is this scheduled for a milestone?

**Comment by borgdylan** [comment]
Does this support using reflection for projects that are not compiled with roslyn but with a different compiler?

**Comment by borgdylan** [comment]
Affter examining the commit, I can still see that roslyn is assumed fully in the code (i.e it loads type using teh roslyn compilation object)

**Comment by borgdylan** [comment]
This bug is not really solved. Roslyn's ITypeSymbol is required to load types. So the decoupling is only half done.
