### ISSUE TITLE
Re-enable tests in E2E_Test.MvcControllerTest

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Scaffolding#491]
Some test in E2E_Test.MvcControllerTest were disabled due to flakeyness. Once they're reliable again re-enable them.

**Comment by mikeharder** [comment]
Scaffolding tests were broken by the following chagne:

https://github.com/aspnet/EntityFramework/commit/58185bab7972f895dcdec71dc8250b32c76f6dfc#diff-ab3bc569c936729f7138226d324bb0b7L26

I think Scaffolding just needs to react.

**Comment by prafullbhosale** [comment]
Related: https://github.com/aspnet/EntityFramework/issues/8547

**Comment by bricelam** [comment]
@prafullbhosale `dynamic` issue was fixed by PR aspnet/EntityFramework#8549
