### ISSUE TITLE
Creating View occasionally results in View being errored until its reopened (Miscellaneous Workspace)

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Scaffolding#514]
Try adding a view to the default Mvc template with individual auth. Occasionally you'll get hit with tons of errors since the View was creating in the Miscellaneous Workspace.

**Comment by jbagga** [comment]
![image](https://user-images.githubusercontent.com/6234561/27247250-c0d31452-52ab-11e7-9112-252f5df2dba2.png)

**Comment by vijayrkn** [comment]
Haven't seen this issue repro in the latest versions. Closing.
