### ISSUE TITLE
deps.json error while trying to add new Controller

### ISSUE THREAD

**Issue by Eilon** [aspnet/Scaffolding#522]
_From @RemiGri on June 15, 2017 9:31_

Hello,
I have an error when trying to add new Controller on a brand new fresh project (ASP.NET Core Web Application (.NET Core)). I have tried naming the project with a . in the middle (Test.project) and without (TestProject) as i have read that the spaces in the name could give errors. I am getting the following error when trying to add a new controller:
![capturefdf](https://user-images.githubusercontent.com/6548496/27174830-55ad3096-51b5-11e7-984a-2f5f25888e83.PNG)

It seems to be looking for the deps.json in bin\BPC\Debug\netcoreapp1.1 and ofcourse the file is not in that folder because after build the files get generated to bin\Debug\netcoreapp1.1

when i move the files generated in bin\Debug\netcoreapp1.1 to bin\BPC\Debug\netcoreapp1.1 then everything seems to work (i am able to add the controllers).

Could anyone advise if this is an error with Visual studio 2017? Or am i doing something wrong? and that is the BPC folder for? 

I am using VS 2017 (Version 15.2 (26430.13) Release)

_Copied from original issue: dotnet/core#695_

**Comment by Eilon** [comment]
_From @Petermarcu on June 21, 2017 16:28_

@Eilon @barrytang @mlorbetske can you take a look at suggest which repo may be the best place to move this issue?

**Comment by prafullbhosale** [comment]
@RemiGri Could you please provide the contents of your .csproj file and also the version of dotnet cli by running `dotnet --info`?

**Comment by photoangell** [comment]
I am having a similar issue in that when I create a Razor project (via dotnet new razor) and try to run it, I get a dialog box saying 
![image](https://user-images.githubusercontent.com/3043919/39191288-8af4b2e6-47ce-11e8-9e3f-d443771443c9.png)
However, the dll is created in C:\projects\razor2\bin\**BPC**\Debug\netcoreapp2.0.
If I edit the .vscode/launch.json file so it refers to the correct path, it all works fine. 

But not sure what this "BPC" directory is about???

.csproj file is...
`<Project Sdk="Microsoft.NET.Sdk.Web">  
  <PropertyGroup>  
    <TargetFramework>netcoreapp2.0</TargetFramework>  
  </PropertyGroup>  
  <ItemGroup>  
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.6" />  
  </ItemGroup>  
  <ItemGroup>  
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.3" />  
  </ItemGroup>  
</Project>`

and dotnet --info yields...
`C:\projects\razor2>dotnet --info
.NET Command Line Tools (2.1.104)

Product Information:
 Version:            2.1.104
 Commit SHA-1 hash:  48ec687460

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.104\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
`

**Comment by vijayrkn** [comment]
This shouldnt be an issue in the latest version.
