### ISSUE TITLE
Enable AppVeyor for pull requests

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Scaffolding#537]
AppVeyor is enabled for the `dev` branch, but for some reason it didn't run on my PR.

**Comment by mikeharder** [comment]
@natemcmaster: Any idea why this might be happening?  The `appveyor.yml` looks identical to other repos.

**Comment by natemcmaster** [comment]
Have @Eilon re-authenticate AppVeyor to this project. AppVeyor needs webhooks installed into each project for these triggers to run correclty.

**Comment by Eilon** [comment]
Happy to do it. @prafullbhosale - any concern on enabling AppVeyor to build & run tests on every PR? (This will not block merging PRs - it just shows an extra status check in the PR so you can quickly see red/green status.)

**Comment by prafullbhosale** [comment]
Sounds good to me.

**Comment by Eilon** [comment]
Should be enabled now.
