### ISSUE TITLE
Can not build the solution in VS 2017, How can I build the solution in the IDE?

### ISSUE THREAD

**Issue by WillPhoenixLiu** [aspnet/Scaffolding#550]
The bulid.cmd works fine, but I can't build the solution in VS 2017. I think it is mainly about restore package failed. How can I build the solution in the IDE?
Here is the messages from the output window. 

Restoring NuGet packages...
Detected package downgrade: NETStandard.Library from 2.0.0-preview2-25401-01 to 1.6.1 
 Microsoft.VisualStudio.Web.CodeGeneration.Core (>= 2.0.0-preview2) -> Microsoft.Extensions.DependencyInjection (>= 2.0.0-preview2-final) -> NETStandard.Library (>= 2.0.0-preview2-25401-01) 
 Microsoft.VisualStudio.Web.CodeGeneration.Core (>= 2.0.0-preview2) -> NETStandard.Library (>= 1.6.1)
Detected package downgrade: NETStandard.Library from 2.0.0-preview2-25401-01 to 1.6.1 
 Microsoft.VisualStudio.Web.CodeGeneration.Core (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGeneration.Templating (>= 2.0.0-preview2) -> Microsoft.AspNetCore.Razor.Language (>= 2.0.0-preview2-final) -> NETStandard.Library (>= 2.0.0-preview2-25401-01) 
 Microsoft.VisualStudio.Web.CodeGeneration.Core (>= 2.0.0-preview2) -> NETStandard.Library (>= 1.6.1)
Package Microsoft.Composition 1.0.27 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETStandard,Version=v2.0.
Detected package downgrade: NETStandard.Library from 2.0.0-preview2-25401-01 to 1.6.1 
 Microsoft.VisualStudio.Web.CodeGeneration (>= 2.0.0-preview2) -> Microsoft.Extensions.DependencyInjection (>= 2.0.0-preview2-final) -> NETStandard.Library (>= 2.0.0-preview2-25401-01) 
 Microsoft.VisualStudio.Web.CodeGeneration (>= 2.0.0-preview2) -> NETStandard.Library (>= 1.6.1)
Detected package downgrade: NETStandard.Library from 2.0.0-preview2-25401-01 to 1.6.1 
 Microsoft.VisualStudio.Web.CodeGeneration (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGeneration.Core (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGeneration.Templating (>= 2.0.0-preview2) -> Microsoft.AspNetCore.Razor.Language (>= 2.0.0-preview2-final) -> NETStandard.Library (>= 2.0.0-preview2-25401-01) 
 Microsoft.VisualStudio.Web.CodeGeneration (>= 2.0.0-preview2) -> NETStandard.Library (>= 1.6.1)
Package Microsoft.Composition 1.0.27 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETStandard,Version=v2.0.
Detected package downgrade: NETStandard.Library from 2.0.0-preview2-25401-01 to 1.6.1 
 Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGeneration.Core (>= 2.0.0-preview2) -> Microsoft.Extensions.DependencyInjection (>= 2.0.0-preview2-final) -> NETStandard.Library (>= 2.0.0-preview2-25401-01) 
 Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore (>= 2.0.0-preview2) -> NETStandard.Library (>= 1.6.1)
Detected package downgrade: NETStandard.Library from 2.0.0-preview2-25401-01 to 1.6.1 
 Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGeneration.Core (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGeneration.Templating (>= 2.0.0-preview2) -> Microsoft.AspNetCore.Razor.Language (>= 2.0.0-preview2-final) -> NETStandard.Library (>= 2.0.0-preview2-25401-01) 
 Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore (>= 2.0.0-preview2) -> NETStandard.Library (>= 1.6.1)
Detected package downgrade: NETStandard.Library from 2.0.0-preview2-25401-01 to 1.6.1 
 Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore (>= 2.0.0-preview2) -> Microsoft.EntityFrameworkCore.Design (>= 2.0.0-preview2-final) -> Microsoft.EntityFrameworkCore.Relational (>= 2.0.0-preview2-final) -> Microsoft.Extensions.Configuration.Abstractions (>= 2.0.0-preview2-final) -> NETStandard.Library (>= 2.0.0-preview2-25401-01) 
 Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore (>= 2.0.0-preview2) -> NETStandard.Library (>= 1.6.1)
Detected package downgrade: NETStandard.Library from 2.0.0-preview2-25401-01 to 1.6.1 
 Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore (>= 2.0.0-preview2) -> Microsoft.EntityFrameworkCore.Design (>= 2.0.0-preview2-final) -> Microsoft.EntityFrameworkCore.Relational (>= 2.0.0-preview2-final) -> Microsoft.EntityFrameworkCore (>= 2.0.0-preview2-final) -> Microsoft.Extensions.Caching.Memory (>= 2.0.0-preview2-final) -> NETStandard.Library (>= 2.0.0-preview2-25401-01) 
 Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore (>= 2.0.0-preview2) -> NETStandard.Library (>= 1.6.1)
Detected package downgrade: NETStandard.Library from 2.0.0-preview2-25401-01 to 1.6.1 
 Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore (>= 2.0.0-preview2) -> Microsoft.EntityFrameworkCore.Design (>= 2.0.0-preview2-final) -> Microsoft.EntityFrameworkCore.Relational (>= 2.0.0-preview2-final) -> Microsoft.EntityFrameworkCore (>= 2.0.0-preview2-final) -> Microsoft.Extensions.DependencyInjection (>= 2.0.0-preview2-final) -> NETStandard.Library (>= 2.0.0-preview2-25401-01) 
 Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore (>= 2.0.0-preview2) -> NETStandard.Library (>= 1.6.1)
Detected package downgrade: NETStandard.Library from 2.0.0-preview2-25401-01 to 1.6.1 
 Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore (>= 2.0.0-preview2) -> Microsoft.EntityFrameworkCore.Design (>= 2.0.0-preview2-final) -> Microsoft.EntityFrameworkCore.Relational (>= 2.0.0-preview2-final) -> Microsoft.EntityFrameworkCore (>= 2.0.0-preview2-final) -> Microsoft.Extensions.Logging (>= 2.0.0-preview2-final) -> NETStandard.Library (>= 2.0.0-preview2-25401-01) 
 Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore (>= 2.0.0-preview2) -> NETStandard.Library (>= 1.6.1)
Package Microsoft.Composition 1.0.27 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETStandard,Version=v2.0.
Detected package downgrade: NETStandard.Library from 2.0.0-preview2-25401-01 to 1.6.1 
 Microsoft.VisualStudio.Web.CodeGenerators.Mvc (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGeneration (>= 2.0.0-preview2) -> Microsoft.Extensions.DependencyInjection (>= 2.0.0-preview2-final) -> NETStandard.Library (>= 2.0.0-preview2-25401-01) 
 Microsoft.VisualStudio.Web.CodeGenerators.Mvc (>= 2.0.0-preview2) -> NETStandard.Library (>= 1.6.1)
Detected package downgrade: NETStandard.Library from 2.0.0-preview2-25401-01 to 1.6.1 
 Microsoft.VisualStudio.Web.CodeGenerators.Mvc (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGeneration (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGeneration.Core (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGeneration.Templating (>= 2.0.0-preview2) -> Microsoft.AspNetCore.Razor.Language (>= 2.0.0-preview2-final) -> NETStandard.Library (>= 2.0.0-preview2-25401-01) 
 Microsoft.VisualStudio.Web.CodeGenerators.Mvc (>= 2.0.0-preview2) -> NETStandard.Library (>= 1.6.1)
Package Microsoft.Composition 1.0.27 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETStandard,Version=v2.0.
Detected package downgrade: NETStandard.Library from 2.0.0-preview2-25401-01 to 1.6.1 
 Microsoft.VisualStudio.Web.CodeGeneration.Templating (>= 2.0.0-preview2) -> Microsoft.AspNetCore.Razor.Language (>= 2.0.0-preview2-final) -> NETStandard.Library (>= 2.0.0-preview2-25401-01) 
 Microsoft.VisualStudio.Web.CodeGeneration.Templating (>= 2.0.0-preview2) -> NETStandard.Library (>= 1.6.1)
Package Microsoft.Composition 1.0.27 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETStandard,Version=v2.0.
Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'.
Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'.
Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'.
Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'.
Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'.
Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'.
Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'.
Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'.
Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'.
Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'.
Package Microsoft.Composition 1.0.27 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETStandard,Version=v2.0.
Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'.
Project Microsoft.VisualStudio.Web.CodeGenerators.Mvc is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Project Microsoft.VisualStudio.Web.CodeGenerators.Mvc supports: netstandard2.0 (.NETStandard,Version=v2.0)
One or more projects are incompatible with .NETCoreApp,Version=v2.0.
Project Microsoft.VisualStudio.Web.CodeGenerators.Mvc is not compatible with net461 (.NETFramework,Version=v4.6.1). Project Microsoft.VisualStudio.Web.CodeGenerators.Mvc supports: netstandard2.0 (.NETStandard,Version=v2.0)
One or more projects are incompatible with .NETFramework,Version=v4.6.1.
Project Microsoft.VisualStudio.Web.CodeGenerators.Mvc is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0) / win7-x86. Project Microsoft.VisualStudio.Web.CodeGenerators.Mvc supports: netstandard2.0 (.NETStandard,Version=v2.0)
One or more projects are incompatible with .NETCoreApp,Version=v2.0 (win7-x86).
Project Microsoft.VisualStudio.Web.CodeGenerators.Mvc is not compatible with net461 (.NETFramework,Version=v4.6.1) / win7-x86. Project Microsoft.VisualStudio.Web.CodeGenerators.Mvc supports: netstandard2.0 (.NETStandard,Version=v2.0)
One or more projects are incompatible with .NETFramework,Version=v4.6.1 (win7-x86).
Package Microsoft.EntityFrameworkCore 2.0.0-preview2-final is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.EntityFrameworkCore 2.0.0-preview2-final supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.AspNetCore.Server.Kestrel 2.0.0-preview2-final is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.Server.Kestrel 2.0.0-preview2-final supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.EntityFrameworkCore.Design 2.0.0-preview2-final is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.EntityFrameworkCore.Design 2.0.0-preview2-final supports:
  - net461 (.NETFramework,Version=v4.6.1)
  - netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.AspNetCore.Server.IISIntegration 2.0.0-preview2-final is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.Server.IISIntegration 2.0.0-preview2-final supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.EntityFrameworkCore.SqlServer 2.0.0-preview2-final is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.EntityFrameworkCore.SqlServer 2.0.0-preview2-final supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.AspNetCore.Mvc 2.0.0-preview2-final is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.Mvc 2.0.0-preview2-final supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.AspNetCore.Hosting 2.0.0-preview2-final is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.Hosting 2.0.0-preview2-final supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.AspNetCore.StaticFiles 2.0.0-preview2-final is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.StaticFiles 2.0.0-preview2-final supports: netstandard2.0 (.NETStandard,Version=v2.0)
Project ModelTypesLocatorTestClassLibrary is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Project ModelTypesLocatorTestClassLibrary supports: netstandard2.0 (.NETStandard,Version=v2.0)
One or more projects are incompatible with .NETCoreApp,Version=v2.0.
One or more packages are incompatible with .NETCoreApp,Version=v2.0.
Detected package downgrade: NETStandard.Library from 2.0.0-preview2-25401-01 to 1.6.1 
 ModelTypesLocatorTestClassLibrary (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGenerators.Mvc (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGeneration (>= 2.0.0-preview2) -> Microsoft.Extensions.DependencyInjection (>= 2.0.0-preview2-final) -> NETStandard.Library (>= 2.0.0-preview2-25401-01) 
 ModelTypesLocatorTestClassLibrary (>= 2.0.0-preview2) -> NETStandard.Library (>= 1.6.1)
Detected package downgrade: NETStandard.Library from 2.0.0-preview2-25401-01 to 1.6.1 
 ModelTypesLocatorTestClassLibrary (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGenerators.Mvc (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGeneration (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGeneration.Core (>= 2.0.0-preview2) -> Microsoft.VisualStudio.Web.CodeGeneration.Templating (>= 2.0.0-preview2) -> Microsoft.AspNetCore.Razor.Language (>= 2.0.0-preview2-final) -> NETStandard.Library (>= 2.0.0-preview2-25401-01) 
 ModelTypesLocatorTestClassLibrary (>= 2.0.0-preview2) -> NETStandard.Library (>= 1.6.1)
Package Microsoft.Composition 1.0.27 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETStandard,Version=v2.0.
NuGet package restore failed.
Time Elapsed: 00:00:04.1552358
========== Finished ==========

**Comment by badersur** [comment]
Could you paste your `.csproj` file?

Maybe changing `netstandard2.0` to `netstandard1.4` or 1.6 in your `.csproj` could solve your issue, or adding `ExcludeAssets="All"` to `Microsoft.Composition`:

```
<PackageReference Include="Microsoft.Composition" Version="1.0.31" ExcludeAssets="All" />
```

or adding:

```
<PropertyGroup>
  <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
</PropertyGroup>
```

I'm just guessing and for more info, see:

https://stackoverflow.com/questions/42349605/reference-net-4-5-dll-in-net-core-1-1-csproj

and https://marketplace.visualstudio.com/items?itemName=firefox.scaffold

**Comment by prafullbhosale** [comment]
@reezonew this looks like you need to install the latest dotnet cli from https://github.com/dotnet/cli/tree/release/2.0.0#installers-and-binaries

Running `build.cmd` usually downloads a version of dotnet cli in a private location which may not be discovered by VS.

**Comment by mudaser** [comment]
Install .net core first
