### ISSUE TITLE
Line endings for scaffolded files are not correct

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#575]
On Windows the scaffolded files have `LF` instead of `CRLF`.
Staging these files on git causes these warnings:

```
warning: LF will be replaced by CRLF in Root/Views/Cars2/Create.cshtml.
The file will have its original line endings in your working directory.
```

cc @Tratcher

**Comment by mmillican** [comment]
I've been noticing this as well on v2.0 with Visual Studio 2017 15.3.2

Workaround is to do a Save As and change the encoding on the file, but this is tedious for every file.
