### ISSUE TITLE
Razor Page templates use fully qualified name 

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/Scaffolding#585]
_From @Rick-Anderson on August 1, 2017 20:7_

The constructor uses the FQN when it's not necessary. For example:

See [Pages/Movie/Index.cshtml.cs](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Pages/Movie/Index.cshtml.cs#L14-L16)

`using RazorPagesMovie.Models;` is in the template.

To repro - follow the [Razor Pages tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model)

_Copied from original issue: aspnet/Templates#858_

**Comment by vijayrkn** [comment]
This should be fixed in the latest version.
