### ISSUE TITLE
Razor Pages scaffolder eats DbUpdateConcurrencyException 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Scaffolding#587]
Expected behavior:
* Scaffolder should correctly handle `DbUpdateConcurrencyException`

Actual behavior:

 * `DbUpdateConcurrencyException` is caught and ignored.

To repro: 

* Create a RP project and add a model.
* [Scaffold the model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model#add-scaffold-tooling-and-perform-initial-migration)

The *Edit.cshtml.cs* file contains the following code:

```cs
public async Task<IActionResult> OnPostAsync()
{
    if (!ModelState.IsValid)
    {
        return Page();
    }

    _context.Attach(Movie).State = EntityState.Modified;

    try
    {
        await _context.SaveChangesAsync();
    }
    catch (DbUpdateConcurrencyException)
    {
        
    }

    return RedirectToPage("./Index");
}
```
It should be

```cs
catch (DbUpdateConcurrencyException)
        {
            if (!MovieExists(movie.ID))
            {
                return NotFound();
            }
            else
            {
                throw;
            }
        }
```

**Comment by prafullbhosale** [comment]
Fixed by #597
