### ISSUE TITLE
Razor Page scaffolder should add `@page "{id:int}"` directive

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Scaffolding#590]
The RP scaffolder should add @page "{id:int}" directive so generated links pass the ID as route data, not query strings.

All my RP tutorials I have to have a section on adding this. See https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1

Update the Edit, Details, and Delete Razor Pages to use the `"{id:int}"` route template. Change the page directive for each of these pages to `@page "{id:int}"`

I have to do  the same thing in my RP/EF tutorial.

**Comment by Rick-Anderson** [comment]
@seancpeters  @prafullbhosale  If this should be moved to another repo let me know where.

**Comment by seancpeters** [comment]
@javiercn @danroth27 - another scaffolding content concern.

**Comment by javiercn** [comment]
@seancpeters I don't think this is Identity specific. I'll let @danroth27 chip on it.

**Comment by danroth27** [comment]
Sounds reasonable to me.

**Comment by Rick-Anderson** [comment]
It's not Identity specific - my tutorials are not using Identity. It's any model you scaffold.

**Comment by Rick-Anderson** [comment]
@seancpeters @prafullbhosale can we get this scheduled for 3.0 so I don't have to tell customers to manually make this change?

**Comment by Rick-Anderson** [comment]
@seancpeters can we get this scheduled to 3.1? It seems passing the ID as route data is cleaner than passing as a query string. cc @tdykstra

**Comment by vijayrkn** [comment]
@Rick-Anderson - Is this an issue with the default template content as well? If so, can you please transfer this issue to the AspNetCore repo where the template resides?

**Comment by Rick-Anderson** [comment]
@vijayrkn  it doesn't have anything to do with the default template or Identity. The scaffolder generates correct code. My preference is to pass the ID as route data, not as a query string. You can close this case if you like since it's a feature request, not a bug.

**Comment by vijayrkn** [comment]
Sure. Will close this since it is a feature request on all generated content and not specific to scaffolding.
