### ISSUE TITLE
Unable to restore minimal dependencies for scaffolding in an asp.net core 2 preview project.

### ISSUE THREAD

**Issue by tothsuo19** [aspnet/Scaffolding#591]
Trying to scaffold a controller in an asp.net core 2 project, nuget fails @ 
**Error	NU1102	Unable to find package Microsoft.VisualStudio.Web.CodeGeneration.Design with version (>= 2.0.0)** after installing minimal dependencies.
Changing this within the .csproj folder results in further dependency errors. Is there a smart workaround to this or would I need to develop out of the core 2 preview?

**Comment by prafullbhosale** [comment]
Hi @tothsuo19, 
Can you please try again? 
The [package](https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGeneration.Design/2.0.0) is now available on NuGet.org and you shouldn't face this issue anymore.

**Comment by tothsuo19** [comment]
@prafullbhosale 
Worked an absolute treat, thank you kindly.
It does however alert me of the detection of a package downgrade and to directly reference it within I assume the .csproj but not something I should be worried about I'm guessing. I'm able to scaffold a controller as advertised on the tutorial written by Rick & Tom. Hope this has helped others as it has myself.

**Comment by prafullbhosale** [comment]
@tothsuo19 that shouldn't be the case. 
Could you please provide a sample project where this can be repro'ed? I'd love to take a look as to why this is happening.

**Comment by tothsuo19** [comment]
Sure.

[MvcMovie.zip](https://github.com/aspnet/Scaffolding/files/1226247/MvcMovie.zip)

The only other issue encountered from start to finish is upon adding the 'Rating' migration to the database. It will complain that 'Movie' is itself a pre-existing object but that's ef not scaffolding.

The tutorial was of great help yet the issues might scare a few people away from the technology.

**Comment by prafullbhosale** [comment]
@tothsuo19 , the csproj contains `Microsoft.AspNetCore.All` version `2.0.0-preview2-final` which indicates that you have a slightly older version of dotnet CLI installed on your machine.
This is causing the package downgrade warnings for `Microsoft.NETCore.App`.
If you install the latest 2.0 CLI from https://www.microsoft.com/net/download/core, you should get the latest templates that have the right versions of the packages.

**Comment by tothsuo19** [comment]
@prafullbhosale 
Ah, so that's the issue. I assumed that, with using the preview and it being updated to a complete state I'd of had such a thing already installed? I'll see what happens and it's surely safe to close this.

Thanks again.
