### ISSUE TITLE
RP scaffolder should not decorate model with  [BindProperty]  in delete

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Scaffolding#592]
`[BindProperty]` in not needed in the [delete page](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Pages/Movies/Delete.cshtml.cs#L21-L22). There is nothing to bind on the delete page - it uses ID to get the model. 

To repo, follow [RP tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model).

**Comment by vijayrkn** [comment]
Content issue. Can you please have some one on your side take care of this?

**Comment by Rick-Anderson** [comment]
https://github.com/aspnet/AspNetCore.Docs/issues/15616 tracks documenting that.
