### ISSUE TITLE
Scaffolder code has empty `using ;` when you don't specify the FQN on the DC

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Scaffolding#599]
To repro:

```
mkdir RazorPagesMovie
cd RazorPagesMovie
dotnet new razor
```
Add a [movie model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model)

```
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet aspnet-codegenerator razorpage -m Movie -dc MovieContext -udl -outDir Pages\Movies --referenceScriptLibraries
```

Run `dotnet ef migrations add Initial`

Result:
`<timestamp>_Initial.cs` and *MovieContextModelSnapshot.cs* both start out with

```csharp
// <auto-generated />
using ;
using Microsoft.EntityFrameworkCore;
```

Fix is to specify the fully qualified namespace on the dc.

**Comment by prafullbhosale** [comment]
@Rick-Anderson, With the command line you provided,  the generated DbContext class is not in any namespace: 

```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using RazorTest.Models;

    public class MovieContext : DbContext
    {
        public MovieContext (DbContextOptions<MovieContext> options)
            : base(options)
        {
        }

        public DbSet<RazorTest.Models.Movie> Movie { get; set; }
    }
```

But there's no `using ;` generated during scaffolding step. 
I can build the project successfully. 

I see the issue when I run `dotnet ef migrations add Initial`
The files you mentioned `<timestamp>_Initial.cs` and `MovieContextModelSnapshot.cs` seem to be generated by EF migrations. 

The issue on EF repo: https://github.com/aspnet/EntityFrameworkCore/issues/2467


The fix from scaffolding side would be to add the default namespace if only the shortname is provided on the command line.

**Comment by vijayrkn** [comment]
Closing since the linked issue is fixed.
