### ISSUE TITLE
[ASP.NET Core 2.0] Scaffolding failed to edit Startup class...

### ISSUE THREAD

**Issue by mrlife** [aspnet/Scaffolding#603]
Running the `dotnet aspnet-codegenerator` produces the following error: 

> Scaffolding failed to edit Startup class to register the new Context using Dependency Injection. Make sure there is a Startup class and a ConfigureServices method and Configuration property in it.

There is indeed a `Startup.cs` that contains both a `ConfigureServices()` and an `IConfigurationRoot Configuration` property.

Here are the full contents of the terminal (`Models/ContactInfo.cs` and `Models/AppContext.cs` exist):

> dotnet aspnet-codegenerator controller -name ContactInfoController -m ContactInfo -dc AppContext --relativeFolderPath Controllers --useDefaultLayout --referenceScriptLibraries
Building project ...
Finding the generator 'controller'...
Running the generator 'controller'...
Generating a new DbContext class 'AppContext'
Scaffolding failed to edit Startup class to register the new Context using Dependency Injection. Make sure there is a Startup class and a ConfigureServices method and Configuration property in it.
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:17.92

Following the code from the official docs: https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-mac/adding-model#scaffold-the-moviecontroller

**Comment by SaravananArunagiri** [comment]
can you post the startup class

**Comment by mrlife** [comment]
Here is the `startup` class:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using App.Models;

namespace co
{
	public class Startup
	{
		public Startup(IHostingEnvironment env)
		{
			var builder = new ConfigurationBuilder()
				.SetBasePath(env.ContentRootPath)
				.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
				.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
				.AddEnvironmentVariables();
			Configuration = builder.Build();
		}

		public IConfigurationRoot Configuration { get; }

		// This method gets called by the runtime. Use this method to add services to the container.
		public void ConfigureServices(IServiceCollection services)
		{
			// Add framework services.
			services.AddMvc();
		}

		// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
		public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
		{
			loggerFactory.AddConsole(Configuration.GetSection("Logging"));
			loggerFactory.AddDebug();

			if (env.IsDevelopment())
			{
				app.UseDeveloperExceptionPage();
				app.UseBrowserLink();
			}
			else
			{
				app.UseExceptionHandler("/Home/Error");
			}

			app.UseStaticFiles();

			app.UseMvc(routes =>
			{
				routes.MapRoute(
					name: "default",
					template: "{controller=Home}/{action=Index}/{id?}");
			});
		}
	}
}
```

**Comment by prafullbhosale** [comment]
@mrlife, since the DbContext file already exists (`Models\AppContext.cs`), you would have to make sure that the DbContext is registered in the Startup class' `ConfigureServices()` method as well. 

```cs
    services.AddDbContext<AppContext>(options => 
           options.UseSqlServer(Configuration.GetConnectionString("ConnectionStringName")));
```

The `ConnectionStringName` in the above snippet maps to the connection string in appsettings.json


Scaffolding will not be able to register existing DbContext classes in the Startup class.

**Comment by mrlife** [comment]
@prafullbhosale, you are right about the `AddDbContext` being needed in `ConfigureServices()`. I did try the scaffolding with and without that line, and it didn't affect the error message, so I left it out as a way to provide the smallest code that produces the error.

**Comment by mrlife** [comment]
Could this be verified whether a bug or maybe an undocumented/overlooked configuration change needed with .NET 2.0?

**Comment by mrlife** [comment]
I was missing running a command like the following before the `dotnet aspnet-codegenerator` command:

```
dotnet ef dbcontext scaffold "Server=localhost;User Id=root;Password=123456;Database=eftests" "Pomelo.EntityFrameworkCore.MySql"
```
