### ISSUE TITLE
Feature request: Repository Pattern Controller Scaffolding

### ISSUE THREAD

**Issue by jepperaskdk** [aspnet/Scaffolding#608]
As described in my thread on StackOverflow here [https://stackoverflow.com/questions/45905420/visual-studio-2017-mvc-scaffolding-add-custom-directory](url), it would be cool with a Controller-scaffolder adhering to the Repository-pattern.

**Comment by vijayrkn** [comment]
This has an invalid link. Please re-open if this is still relevant.
