### ISSUE TITLE
Scaffolding fails with async main function 

### ISSUE THREAD

**Issue by ibqn** [aspnet/Scaffolding#631]
I was following this famous [tutorial](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/read-related-data#create-a-courses-page-that-displays-department-name) on GNU/Linux running dotnet core 2.0 with some modifications, where one of such was the switch to the _async_ main function.

As the result scaffolding was failing for me with the very "descriptive" error message (which is probably a standard on windows):

    ibqn@pLs ~/d/d/contoso-uni> dotnet aspnet-codegenerator controller -name CoursesController -m 
    Course -dc SchoolContext --relativeFolderPath Controllers --useDefaultLayout --
    referenceScriptLibraries
    Building project ...
    Finding the generator 'controller'...
    Running the generator 'controller'...
    Attempting to compile the application in memory.
    Could not get the reflection type for DbContext : ContosoUniversity.Data.SchoolContext
       at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
       at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
       at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
       at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
    RunTime 00:00:10.66

Once, I have reverted to the default main function used by the template, I was able to  use the scaffold command. Below you can find the diff change: 

```
+++ b/contoso-uni/Program.cs
@@ -15,7 +15,8 @@ namespace ContosoUniversity
 {
     public class Program
     {
-        public static async Task Main(string[] args)
+        //public static async Task Main(string[] args)
+        public static void Main(string[] args)
         {
             IWebHost host = BuildWebHost(args);
             using (IServiceScope scope = host.Services.CreateScope())
@@ -24,7 +25,7 @@ namespace ContosoUniversity
                 try
                 {
                     SchoolContext context = services.GetRequiredService<SchoolContext>();
-                    await DbInitializer.InitializeAsync(context);
+                    //await DbInitializer.InitializeAsync(context);
                 }
                 catch (Exception exception)
                 {
@@ -32,7 +33,8 @@ namespace ContosoUniversity
                     logger.LogError(exception, "An error occured while seeding the database.");
                 }
             }
-            await host.RunAsync();
+            //await host.RunAsync();
+            host.Run();
         }
```

**Comment by vijayrkn** [comment]
This should work in the latest version.
