### ISSUE TITLE
scaffolder doesn't use plural from DbSet

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Scaffolding#633]
new shorter instructions

1.  Create a RP web app named `RazorPagesMovie`
1. Follow [these](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model) instructions **EXCEPT** - name the `DbSet` plural
`public DbSet<Movie> Movies { get; set; }`

This tutorial had 30K confirming it works until an update was made to change to the plural `public DbSet<Movie> Movies { get; set; }`

-- what follows is essentially the same instructions

In VS, create a new Razor Pages (RP) app named ContosoUniversity
Create a Models folder. In the Models folder, create a class file named Student.cs and replace the code with the following:
```
using System;
using System.Collections.Generic;

namespace ContosoUniversity.Models
{
    public class Student
    {
        public int ID { get; set; }
        public string LastName { get; set; }
        public string FirstMidName { get; set; }
        public DateTime EnrollmentDate { get; set; }
    }
}
```

In the Data folder create a new class file named SchoolContext.cs, and replace the template code with the following code:

```
using ContosoUniversity.Models;
using Microsoft.EntityFrameworkCore;

namespace ContosoUniversity.Data
{
    public class SchoolContext : DbContext
    {
        public SchoolContext(DbContextOptions<SchoolContext> options) : base(options)
        {
        }

        public DbSet<Student> Students { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<Student>().ToTable("Student");
        }
    }
}
```

Add SchoolContext to the DI container:

```
// ADD EF using
// using Microsoft.EntityFrameworkCore;

public void ConfigureServices(IServiceCollection services)
{
    services.AddDbContext<Data.SchoolContext>(options =>
        options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

    services.AddMvc();
}
```

Open the appsettings.json file and add a connection string as shown in the following code:

```
{
  "ConnectionStrings": {
    "DefaultConnection": "Server=(localdb)\\mssqllocaldb;Database=ContosoUniversity1;Trusted_Connection=True;MultipleActiveResultSets=true"
  },
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning"
    }
  }
}
```
In the Package Manager Console (PMC), enter the following commands:
```
Install-Package Microsoft.VisualStudio.Web.CodeGeneration.Design -Version 2.0.0
Add-Migration Initial
Update-Database
```
*Scaffold the model

dotnet aspnet-codegenerator razorpage -m Student -dc SchoolContext -udl -outDir Pages\CU --referenceScriptLibraries

Build the project. You get errors
` error CS1061: 'SchoolContext' does not contain a definition for 'Student' and no extension method 'Student'`

Here is the generated code: `            _context.Student.Add(Student);
`
It should be plural 
`_context.Students.Add(Student);`

**Comment by mikebrind** [comment]
Related to the issue outlined, the scaffolder also generates singular names for collection properties, which is odd, in my opinion. So instead of 
```csharp
public IList<Student> Students { get; set; }
```
you get 

```csharp
public IList<Student> Student { get; set; }
```
And in the Razor Page:
```csharp
@foreach (var item in Model.Student) {
```

**Comment by Eilon** [comment]
@prafullbhosale what is the reason to patch this? Is it just a bug, or is it really a new feature?

**Comment by Rick-Anderson** [comment]
@Eilon  sorry for the verbose write up. The scaffolder generates incorrect code when the `DbSet` is plural.

` public DbSet<Student> Students { get; set; }`

**Comment by Eilon** [comment]
Ah ok so it's a genuine, old-fashioned, plain & simple bug then?

**Comment by Eilon** [comment]
Talked to @mlorbetske about this. It's indeed worth fixing, but given the timelines, we are moving this issue to the March 2018 patch.

**Comment by Rick-Anderson** [comment]
Yes. Most folks like to user plural for the DbSet, but doing so generates invalid code.  See [Scaffold the model](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro#scaffold-the-model)

Build the project. The build generates errors like the following:

1>Pages\Students\Index.cshtml.cs(26,38,26,45): error CS1061: 'SchoolContext' does not contain a definition for 'Student'

Globally change `_context.Student` to `_context.Students` (that is, add an **"s"** to Student). 7 occurrences are found and updated. We hope to fix this bug in the next release.

**Comment by prafullbhosale** [comment]
> Talked to @mlorbetske about this. It's indeed worth fixing, but given the timelines, we are moving this issue to the March 2018 patch.

The fix for this is already in the placeholder branch for 2.0.x #667

**Comment by Eilon** [comment]
@prafullbhosale please discuss with @mlorbetske whether you two agree it is safe to take for this patch. I'm fine either way.

**Comment by mlorbetske** [comment]
@Eilon I talked this over with @prafullbhosale and reviewed the changes. It looks like this is low risk & could be taken for this release.

**Comment by Eilon** [comment]
Okie dokie, approved for 2.0.6.

**Comment by philysworld** [comment]
how do you fix this error from happening, what and where would i change the text?

**Comment by Rick-Anderson** [comment]
@philysworld 
This issue fixes the problem and has nothing to do with my tutorial.
 Globally means in every file where ` _context.Student` occurs.  If you're using Visual Studio:

* Ctrl+Shift+F to bring up the **Find and Replace** dialog.
* Select the **Replace in Files** tab.
*  Complete the dialog

**Comment by philysworld** [comment]
am not to sure what page you guys are looking at but i changed in my project every file and coding that had Student to Students and still getting the error. 

also for this cmd do i have to input my local database name

**Comment by Rolito2009** [comment]
Thank you Rick, your tutorials are the best I could find. The last clarification on how to proceed was what I needed. Some of us need as much detail as possible to fully understand the issue and how to fix it.

**Comment by mwhitis** [comment]
@Eilon - you mentioned earlier that this was targeted for the March patch.  Can you comment on whether or not that happened?
