### ISSUE TITLE
Update Web API scaffolders to use new Web API conventions

### ISSUE THREAD

**Issue by danroth27** [aspnet/Scaffolding#636]
We are adding some new [Web API specific conventions]() that we will need the Web API scaffolders to react to.

We are adding `[ApiController]` attribute as the way to opt-in to new API specific conventions and behaviors that are tuned around best practices for APIs.

This will include:
- Automatically responding with a 400 when validation errors occur (using https://tools.ietf.org/html/rfc7807)
- Infer smarter defaults for action parameters (`[FromBody]` for complex types, `[FromRoute]` when possible, otherwise `[FromQuery]`)

**Comment by danroth27** [comment]
@vijayrkn What's the status of this issue? Looks like it was never assigned to anyone.

**Comment by danroth27** [comment]
I'd like to get it done for 2.1.0 RTW. We've already made these updates for the project templates.

**Comment by vijayrkn** [comment]
We have a few more scaffolding items to finish for rc1.  
@seancpeters Can you please take a look at this once you are done with all the rc1 items?

**Comment by seancpeters** [comment]
@danroth27 - I have some time to work on this issue now. Do you know the PR for the corresponding template changes? If I understand correctly, this work would be to apply similar changes to the scaffolding content.

**Comment by danroth27** [comment]
@seancpeters I think it was this one: https://github.com/aspnet/templating/pull/220

**Comment by seancpeters** [comment]
@danroth27 - I noticed that in the aspnet/templating, not all controllers were changed to using ControllerBase (see below). With this in mind, should I make the change to all of the scaffolded Controllers? I'm thinking yes.

Only the WebApi-CSharp template has the change:
https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/WebApi-CSharp/Controllers/ValuesController.cs

These do not:
StarterWeb: https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Controllers/HomeController.cs
Angular-CSharp: https://github.com/aspnet/templating/blob/release/2.1/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/Angular-CSharp/Controllers/SampleDataController.cs
React-CSharp: https://github.com/aspnet/templating/blob/release/2.1/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/React-CSharp/Controllers/SampleDataController.cs
ReactRedux-CSharp https://github.com/aspnet/templating/blob/release/2.1/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/ReactRedux-CSharp/Controllers/SampleDataController.cs

**Comment by danroth27** [comment]
@seancpeters Only web API controllers should derive from `ControllerBase`. Web UI controllers (like `HomeController`) should continue to derive from `Controller`. Only change Web API specific scaffolders to derive from `ControllerBase`.

Looks like we missed updating the SPA templates to use the new Web API conventions. We'll have to deal with that in the next release.

**Comment by muratg** [comment]
@vijayrkn What's the status of this? This was approved 4 days ago.

**Comment by vijayrkn** [comment]
@seancpeters Is this already merged?

**Comment by seancpeters** [comment]
@vijayrkn @muratg - yes, the corresponding PR #772 was merged on Tuesday I believe.

So I'll close this issue.
