### ISSUE TITLE
Areas scaffolding ScaffoldingReadMe.txt and a suggestion

### ISSUE THREAD

**Issue by NoralK** [aspnet/Scaffolding#643]
Clean project - MVC with individual accounts
.Net Core 2.0
VS2017 - 15.4.0

If I right click "Project Name" -> Add -> Area.  Give the Area name it will scaffold the area up.  It creates a file named ScaffoldingReadMe.txt in the root folder with this text, which has a misspelling.

This is what the file contains:
```
Scaffolding has generated all the files and added the required dependencies.

However the Application's Startup code may required additional changes for things to work end to end.
Add the following code to the Configure method in your Application's Startup class if not already done:

        app.UseMvc(routes =>
        {
          route.MapRoute(
            name : "areas",
            template : "{area:exists}/{controller=Home}/{action=Index}/{id?}"
          );
        });

```
this is what is should be (the `s` is missing in routes.MapRoute):
```
Scaffolding has generated all the files and added the required dependencies.

However the Application's Startup code may required additional changes for things to work end to end.
Add the following code to the Configure method in your Application's Startup class if not already done:

        app.UseMvc(routes =>
        {
          routes.MapRoute(
            name : "areas",
            template : "{area:exists}/{controller=Home}/{action=Index}/{id?}"
          );
        });

```
### Suggestions
It would probably be helpful to have a hyperlink(I know it is text) to the documentation about Areas.

It would also be nice to have, in the Views folder, a basic `_ViewStart.cshtml`, `_ViewImports.cshtml`, and in the Shared folder `_Layout.cshtml`.

Going for broke ... a HomeController(painted for the area) in the Controllers folder with an `Index.cshtml` in the Views\Home folder.

This would make wiring up a site much faster, in my opinion.

Noral

**Comment by Eonasdan** [comment]
did a Google search to submit a ticket for this very thing

**Comment by vijayrkn** [comment]
This should be fixed.
