### ISSUE TITLE
Request: Tooling option for C# model generation.  

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Scaffolding#661]
_From @jaszb on December 7, 2017 11:26_

I'd love to have the ability to use the scaffolding ability like "Razor Pages using EF CRUD" except allowing us to control the Class generated.

For example say we want to connect to a restful web api, then being ale to scaffold CRUD against a DTO object would be super useful.

right now the only way i can hack around this is to gen against EF, then turn those classes into DTOs and rip out all the gen'd db context code and replace it with http client calls.  

not a small task on a big project.

having some customization over the class gen'd would be great.

just a small bit of feed back for you.

thanks

_Copied from original issue: aspnet/Razor#1802_

**Comment by vijayrkn** [comment]
We have the service reference option in new version of Visual Studio that supports generating contents to talk to open API end point.
