### ISSUE TITLE
Scaffolding fails to get type information about the Model class from DbContext if the DbContext class is in a dependency

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#663]
Related: https://github.com/aspnet/Scaffolding/issues/407#issuecomment-284031010

This is because the Roslyn returns `ErrorType` for types defined in transitive references.

cc @Eilon @mlorbetske

**Comment by lpinter** [comment]
The scaffolding fails even if everything is in the same assembly and same namespace.
![2017-12-17_19-55-57](https://user-images.githubusercontent.com/30354422/34089378-73aa8e18-e364-11e7-9420-f5f2401c74a7.png)

I still get the error message
![2017-12-17_19-59-28](https://user-images.githubusercontent.com/30354422/34089759-70b92ffe-e367-11e7-998e-541a42b7b9ce.png)

The original code in the ConfigureServices() method of the Startup.cs file cannot read the connection string from the appsettings.json file
```
services.AddDbContext<ApplicationDbContext>(options =>
  options.UseSqlServer(Configuration.GetConnectionString("OriginalConnection")));
```

To be able to do the scaffolding, I had to hardcode the connection string in the ConfigureServices() method of the Startup.cs file
```
var sqlConnectionString = "Server=(localdb)\\mssqllocaldb;Database=aspnet-SocialMedia_WebApp-53bc9b9d-9d6a-45d4-8429-2a2761773502;Trusted_Connection=True;MultipleActiveResultSets=true";
services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(sqlConnectionString));
```

**Comment by DataWingSoftware** [comment]
Hello @prafullbhosale. So is this an issue with the scaffolding, or with Roslyn? I'd be happy to help if I knew where the issue is. This is how all our projects are architected (With a model project that is then referenced by our DAL, which is then consumed by multiple end released products for consistency across the product lines.) Should I be looking here or at Rosyln in your opinion?

**Comment by prafullbhosale** [comment]
@DataWingSoftware, This isn't an issue with Roslyn. Roslyn returns `ErrorType` for types defined in transitive references by design. Scaffolding wasn't taking this into consideration. The fix for this is in the PR #658

**Comment by Eilon** [comment]
This patch is **approved** for the Feb 2018 patch. Please send a PR to the appropriate branch, get it reviewed, and merge.

Please consider adding a [quirks-mode switch](https://github.com/aspnet/Home/wiki/Quirks-mode-switches-in-patches) for this change.

**Comment by prafullbhosale** [comment]
Closing.

**Comment by oswaldoporcari** [comment]
I have the same problem in version 3.1

**Comment by XF-at-Checkmarx** [comment]
Same here. Reproducible in 3.14.
