### ISSUE TITLE
Identity scaffolder

### ISSUE THREAD

**Issue by danroth27** [aspnet/Scaffolding#666]
Build a scaffolder for generating the identity related code from the individual user accounts template.

**Comment by Eilon** [comment]
@danroth27 / @prafullbhosale - what's the status of this preview1 work item?

**Comment by prafullbhosale** [comment]
The preview1 changes are checked in to release/2.1 branch https://github.com/aspnet/Scaffolding/pull/678 and merged to dev.

**Comment by Eilon** [comment]
Cool. Should we close this issue? Or is it tracking any other work?

**Comment by prafullbhosale** [comment]
There are changes planned for Preview2. Not sure if @danroth27 wants to track it here or separately. 
I don't have a preference either ways.

**Comment by Eilon** [comment]
Moved to preview2. I'll let @danroth27 work with you on how to track any remaining work.

**Comment by javiercn** [comment]
We have a fantastic project board for it https://github.com/orgs/aspnet/projects/12

**Comment by prafullbhosale** [comment]
@danroth27/ @javiercn  I am closing this as done (All preview2 changes are in). 
If we need to make further changes to the command line experience, lets open separate issues to track those changes.
