### ISSUE TITLE
 I need to develop via vsix visual studio 2017 custom scaffolding custom code, production development generator.

### ISSUE THREAD

**Issue by ltm0203** [aspnet/Scaffolding#672]
Hello, I want to propose a demand or a function.
I want to develop based on vsix as a code generator.
In the. NET framework, I can use vsix to achieve, the use of. Net framework class library, installation 

```
Microsoft.AspNet.Scaffolding 
```
for assembly resolution.
As shown below:

![image](https://user-images.githubusercontent.com/7875527/34719356-809b28f8-f575-11e7-91e0-e4bbcfaca522.png)
 ![image.png](http://upload-images.jianshu.io/upload_images/1979022-cf4ed1018b099db3.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![image.png](http://upload-images.jianshu.io/upload_images/1979022-cc3d9317d4dd2449.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

And by the time of .NET Core, I wanted to do the same development, and I found I could not find a similar ```Microsoft.AspNet.Scaffolding``` or ```Microsoft.AspNetCore.Scaffolding``` for processing
But vs2017 also supports the generation of web project code.
So can you give me a document or help manual to make a call? ? ?

This is my code generator based on the .net framework version

url: https://visualstudiogallery.msdn.microsoft.com/b1364d50-a445-433f-971c-373b402b6694

**Comment by shennwei** [comment]
I hope you can give a solution Thank you.

**Comment by LNBQIAN** [comment]
I hope you can give a solution Thank you.

**Comment by dengyongbiao** [comment]
I hope you can give a solution Thank you.

**Comment by pipiluhua** [comment]
I hope you can give a solution Thank you

**Comment by LitterZ** [comment]
I hope you can give a solution Thank you.

**Comment by ck505778675** [comment]
我希望你能给一个解决方案谢谢

**Comment by madeinchinalmc** [comment]
I hope you can give a solution Thank you.

**Comment by ganqiyin** [comment]
I hope you can give a solution Thank you.

**Comment by lizejia** [comment]
I hope you can give a solution Thank you.

**Comment by haoyk** [comment]
I hope you can give a solution Thank you.

**Comment by HowToPlayNo1** [comment]
I hope you can give a solution Thank you.

**Comment by yangxuilyx** [comment]
I hope you can give a solution Thank you.

**Comment by mac2222** [comment]
I hope you can give a solution Thank you.

**Comment by faith3729** [comment]
I hope you can give a solution Thank you.

**Comment by gezb19890407** [comment]
I hope you can give a solution Thank you.

**Comment by amin168** [comment]
I hope you can give a solution Thank you.

**Comment by LXKing** [comment]
I hope you can give a solution Thank you.

**Comment by chuankang** [comment]
I hope you can give a solution Thank you.

**Comment by cato541265** [comment]
I hope you can give a solution Thank you.

**Comment by jackehuang** [comment]
I hope you can give a solution Thank you

**Comment by fzrain** [comment]
I hope you can give a solution Thank you.

**Comment by loudjay** [comment]
I hope can give a solution to help, Thank you.

**Comment by Future1995** [comment]
I hope you can give a solution Thank you.

**Comment by lihongfang16** [comment]
I hope you can give a solution Thank you.

**Comment by zhaohejing** [comment]
I hope you can give a solution Thank you.

**Comment by ideafirm** [comment]
I hope you can give a solution Thank you.

**Comment by linyujie** [comment]
I hope you can give a solution Thank you

**Comment by wenxiayili** [comment]
Could you help with the solution code?

**Comment by strugglepcx** [comment]
I hope you can give a solution Thank you

**Comment by xxxxxxshu** [comment]
I hope you can give a solution Thank you.

**Comment by yangpengfei** [comment]
I hope can give a solution to help, Thank you.

**Comment by jasonoiu** [comment]
I hope you can give a solution Thank you.

**Comment by zengchangyang** [comment]
I hope you can give a solution Thank you.

**Comment by 251638256** [comment]
I hope can give a solution to help, Thank you very much

**Comment by thelaurelyy** [comment]
I hope you can give a solution Thank you.

**Comment by jerryzhengsz** [comment]
I hope you can give a solution Thank you.

**Comment by ryanruan** [comment]
I hope you can give a solution Thank you.

**Comment by gjl8820** [comment]
I hope you can give a solution Thank you.

**Comment by huanchen21** [comment]
I hope you can give a solution Thank you.

**Comment by yinboxie** [comment]
I hope you can give a solution Thank you.

**Comment by kiaser** [comment]
I hope you can give a solution Thank you.

**Comment by brsoft001** [comment]
I hope you can give a solution Thank you

**Comment by toddfsy** [comment]
I hope you can give a solution Thank you.

**Comment by haojiefu007** [comment]
I hope you can give a solution Thank you.

**Comment by zhupeng0929** [comment]
I hope you can give a solution Thank you.

**Comment by remember2011** [comment]
I hope you can give a solution Thank you.

**Comment by yangsanjun** [comment]
I hope you can give a solution Thank you.

**Comment by cwsheng** [comment]
I hope you can give a solution Thank you.

**Comment by huoyingluoye** [comment]
I hope you can give a solution Thank you.

**Comment by pointch** [comment]
well done,  I want to see a perfect solution, best wishes to you.

**Comment by yidui2ban** [comment]
well done, I want to learn more from a solution,thx.

**Comment by risfeng** [comment]
I hope you can give a solution Thank you.

**Comment by ouyangnengjun** [comment]
I hope you can give a solution Thank you.

**Comment by yaozhenfa** [comment]
I hope you can give a solution Thank you.

**Comment by suqinghe** [comment]
I hope you can give a solution Thank you.

**Comment by 470503790** [comment]
I hope you can give a solution Thank you.

**Comment by cgq355716727** [comment]
I hope you can give a solution Thank you.

**Comment by a602123** [comment]
I hope you can give a solution Thank you.

**Comment by yunfeiyang1916** [comment]
I hope you can give a solution Thank you.

**Comment by haiqing-li** [comment]
I hope you can give a solution Thank you.

**Comment by thl1991** [comment]
I hope you can give a solution Thank you.

**Comment by wai2dance** [comment]
I hope you can give a solution Thank you.

**Comment by SeanChen2012** [comment]
I hope you can give a solution Thank you.

**Comment by LanceFang** [comment]
我希望你能给一个解决方案谢谢
