### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by gforceg** [aspnet/Scaffolding#673]
Does this project extend the command line like the [dotnet-ef](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet)? If so can we expect dedicated documentation on docs.microsoft.com to it similar to EF Core?

The reference to what scaffolding is (README.md) shows how to select a scaffold in the Visual Studio IDE.

**Comment by vijayrkn** [comment]
We have documentation on how to use the commandline tool here - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-3.0
