### ISSUE TITLE
Add flag for EF based scaffolders to allow users to choose between SQL server and SQLite

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#677]
Currently EF based scaffolding generates code which registers a `DbContext` in the Startup class always using `SqlServer` as follows:
```cs
 services.AddDbContext<MyDbContext>(options =>
     options.UseSqlServer(Configuration.GetConnectionString("ConnectionName"));
```

Scaffolding should allow the user to choose SQLite or SQLServer 

cc @danroth27 @mlorbetske

**Comment by vijayrkn** [comment]
Closing as a dupe of https://github.com/aspnet/Scaffolding/issues/1231
