### ISSUE TITLE
Identity scaffolder overwrites files even without the --force option

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Scaffolding#684]
Repro:
- Run `dotnet new mvc --auth Individual`
- Run `dotnet aspnet-codegenerator identity`
- Modify `IdentityHostingStartup.cs` to make sure we know when it is overwritten
- Run `dotnet aspnet-codegenerator identity` (Note: no `--force`)

Expected:
An error that says file already exists.

Actual:
`IdentityHostingStartup` gets overwritten.

**Comment by vijayrkn** [comment]
I cant repro this issue any more. It gives me an error message that I need to pass --force. Closing.
