### ISSUE TITLE
Identity scaffolder: Mvc individual auth with custom UserClass fails on first request

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Scaffolding#685]
Repro:
- Run `dotnet new mvc --auth Individual`
- Run `dotnet aspnet-codegenerator identity -u CustomUserClass`
- Remove `AddIdentity` bit from `Startup.cs` as mentioned in `ScaffoldingReadme.txt`
- Run `dotnet run` and go to localhost:5001

Expected:
Loads the home page

Actual:
Throws InvalidOperationException: No service for type 'Microsoft.AspNetCore.Identity.UserManager

**Comment by danroth27** [comment]
@prafullbhosale I think this is because the readme text is wrong. You shouldn't remove the call to `AddIdentity`. Instead you need to remove the call to `AddDefaultUI`.

**Comment by prafullbhosale** [comment]
> You shouldn't remove the call to AddIdentity. Instead you need to remove the call to AddDefaultUI.

It needs to be conditionally done based on whether the user intended to create a new DbContext or use an existing one.

**Comment by danroth27** [comment]
This should just be readme update to tell the user to fix their login partial. We should open a separate bug to conditional tell the user to remove AddIdentity vs AddDefaultUI.

**Comment by vijayrkn** [comment]
The readme doesnt seem to have this section mentioned. The code might have changed since then. Closing.
