### ISSUE TITLE
Identity scaffolder: Navigating to localhost:5001/Identity/Manage/Index for the first time does not redirect to Login

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Scaffolding#687]
Repro:
- Run `dotnet new razor --auth Individual`
- Run `dotnet aspnet-codegenerator identity`
- Remove `AddIdentity` bit from `Startup.cs` as mentioned in `ScaffoldingReadme.txt`
- Run all the necessary ef migrations
- Go to https://localhost:5001/Identity/Manage/Index

Expected:
- Redirected to Login page

Actual:
Response saying `Unable to load user with ID ''.`

**Comment by danroth27** [comment]
@prafullbhosale I think the `ScaffoldingReadme.txt` has a typo. You shouldn't remove the call to `AddIdentity`. You just need to remove the call to `AddDefaultUI`.

**Comment by danroth27** [comment]
We need to update the code that sets up authorization to look like this:

```c#
                services.AddMvc()
                    .AddRazorPagesOptions(options =>
                    {
                        options.AllowAreas = true;
                        options.Conventions.AuthorizeAreaFolder("Identity", "/Account/Manage");
                        options.Conventions.AuthorizeAreaPage("Identity", "/Account/Logout");
                    });
```
