### ISSUE TITLE
Tracking: Scaffolding is broken in 5.2.4 release

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Scaffolding#692]
_From @mkArtakMSFT on February 16, 2018 21:32_

With the release of 5.2.4 of MVC, scaffolding is broken for MVC 5 if customers update their packages until we update VS.

This is a tracking bug to just make sure that the upcoming release will have this fixed.

_Copied from original issue: aspnet/AspNetWebStack#130_

**Comment by mkArtakMSFT** [comment]
_From @Eilon on February 16, 2018 21:59_

Just a task, right? Nothing for us to change in Web Stack as far as I understood; ultimately the bug is in Scaffolding.

**Comment by mkArtakMSFT** [comment]
Correct. Nothing to do right away. Just tracking for the next release. I'll also move this to the scaffolding repo.

**Comment by mkArtakMSFT** [comment]
Assigning to the preview2 milestone to handle during validation and make sure that the scaffolding works fine.

**Comment by mkArtakMSFT** [comment]
@jbagga, parking this issues on your plate for now. This is really used to track scaffolding validation when we'll be wrapping up preview2 release.

**Comment by jbagga** [comment]
@mkArtakMSFT Looks like @prafullbhosale moved this out of the preview2 milestone. Does this need to be validated?

**Comment by mkArtakMSFT** [comment]
@prafullbhosale, do you have any other way you track verification work? The goal was to make sure that the issue introduced in an earlier release is fixed in the next one (upcoming)

**Comment by prafullbhosale** [comment]
> do you have any other way you track verification work? The goal was to make sure that the issue introduced in an earlier release is fixed in the next one (upcoming)

The MVC5 and older scaffolding work is tracked in TFS. Let me check if there is an existing issue for this in TFS (I will create one if it doesn't already exist).

**Comment by mkArtakMSFT** [comment]
@prafullbhosale, do you have any update on this?
/cc @seancpeters

**Comment by prafullbhosale** [comment]
This is being tracked in TFS now (sent you the TFS issue on email).
The actual work hasn't been started on this yet.

**Comment by mkArtakMSFT** [comment]
Closing this as there I no action item here and the TFS issue is tracking this work.
