### ISSUE TITLE
Error running Razor Scaffolding due to language version

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Scaffolding#693]
_From @Valks on February 21, 2018 3:58_

### Functional impact
Cannot use the generator to create a set of Views because it fails.

### Minimal repro steps
1. Create a asp.net core 2.0 app )Web Application with Authentication set to Individual User Accounts.
2. create a function which uses a newer language feature e.g. default parameter `public void Test(CancellationToken token = default) { }
3. Create a new folder in Pages called Test
4. Right click on the folder and go Add > Razor Page...
5. Select Razor Pages using Entity Framework (CRUD)
6. Select a Model class - ApplicationUser (WebApplication1.Data)
7. Select a Data context class - ApplicationDbContext (WebApplication1.Data)
8. Deselect all options
9. Press Add
10. Error log should appear in a modal.

### Expected result
Expected the Razor Views to be generated.

### Actual result
Error modal appeared with the error log while it tried to generate the code.

### Further technical details
My best assumption is the generator runs ignoring the project language settings (both in release and debug) defaulting to the latest major version.

_Copied from original issue: aspnet/Razor#2094_

**Comment by prafullbhosale** [comment]
Sounds similar to this: https://github.com/aspnet/Scaffolding/issues/501
@Valks can you try adding a package reference to `Microsoft.CodeAnalysis.CSharp.Workspaces` to the project?

**Comment by vijayrkn** [comment]
Scaffolding supports the latest version now. Closing.
