### ISSUE TITLE
Add instructions to the ScaffoldingReadme.txt for the identity scaffolder on how to pick up the application layout

### ISSUE THREAD

**Issue by danroth27** [aspnet/Scaffolding#702]
The scaffolded identity area has its own layout. To use the application layout instead you need to remove the layout in the identity area and update `_ViewStart.cshtml` to point to the application layout.

**Comment by prafullbhosale** [comment]
Closing this. Based on discussion, now that layout file is specified as an option (or is generated), adding to _ViewStart.cshtml is done by the scaffolder.
