### ISSUE TITLE
Update the scaffolders to use the new <partial /> Tag Helper when targeting 2.1 projects

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Scaffolding#706]
We introduced the new `<partial />` Tag Helper in ASP.NET Core 2.1 and thus we should update the scaffolders for both Views and Razor Pages to use it when adding the validation scripts partial when they're scaffolding into a project targeting 2.1.0:

``` html
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}
```

**Comment by DamianEdwards** [comment]
@prafullbhosale @mlorbetske

**Comment by mlorbetske** [comment]
@seancpeters

**Comment by vijayrkn** [comment]
Checked the code and this is already available in the code. This bug was not updated. Closing
https://github.com/aspnet/Scaffolding/blob/61114a665ee506804c3a648cb88b8ebc11ae9819/src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Manage/Account.Manage.SetPassword.cshtml#L9
