### ISSUE TITLE
Update controller scaffolders for new features in 2.1

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Scaffolding#707]
2.1 introduces some [new features for controllers](https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-web-apis/) that the scaffolders should now generate in projects that target 2.1:
- [ ] the new `ActionResult<T>` type should be used as the return type for any actions that return a result
- [ ] the new `[ApiController]` attribute should be applied to Web API controllers and their action methods updated to omit explicit `ModelState` checks (as these are done automatically when the attribute is present)

**Comment by DamianEdwards** [comment]
@mlorbetske @rynowak

**Comment by mlorbetske** [comment]
@seancpeters @prafullbhosale

**Comment by vijayrkn** [comment]
Looked at the scaffolding templates & we already have these updates. 
e.g : https://github.com/aspnet/Scaffolding/blob/9efe0f7e05e51bb43c878be49087bdba7456e36d/src/VS.Web.CG.Mvc/Templates/ControllerGenerator/ApiEmptyController.cshtml#L12

Closing
