### ISSUE TITLE
error compiling sources

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Scaffolding#71]
Hi,
  I just updated the repository clone, added to a custom scaffolders solution and tried recompiled, but I receive several errors

3>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AspNet\Microsoft.Web.AspNet.targets(143,5): error : Initiate build in the design time host failed with the following error: Could not load file or assembly 'a1bdf404-2a84-4219-84c6-6f06386d4d7a$Microsoft.Framework.Runtime.Roslyn' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))
6>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AspNet\Microsoft.Web.AspNet.targets(143,5): error : Initiate build in the design time host failed with the following error: Could not load file or assembly '8147ab57-b6e5-4219-9b53-c2a54be0e337$Microsoft.Framework.Runtime.Roslyn' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))

5>D:\Sorgenti\VNext\Scaffolders\ScaffoldingSourceRoot\Microsoft.Framework.CodeGeneration.Common\CommonUtilities.cs(36,52): ASP.NET 5.0 error CS0012: The type 'ImmutableArray<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Collections.Immutable, Version=1.1.33.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
5>D:\Sorgenti\VNext\Scaffolders\ScaffoldingSourceRoot\Microsoft.Framework.CodeGeneration.Common\CommonUtilities.cs(36,52): ASP.NET Core 5.0 error CS0012: The type 'ImmutableArray<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Collections.Immutable, Version=1.1.33.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

and so on

**Comment by robbert229** [comment]
I assume that this got fixed. Can you still not build?
