### ISSUE TITLE
Remove PrivateAssets="All" for EF Core. Design dependency in MS.VS.Web.CG.EFCore package

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#711]
Making the `Microsoft.EntityFrameworkCore.Design` package a private dependency has an unfortunate side effect:
https://github.com/aspnet/Scaffolding/blob/dev/src/VS.Web.CG.EFCore/VS.Web.CG.EFCore.csproj#L20

Scaffolding fails if the user project has a lower version of `Microsoft.EntityFrameworkCore.Design` than what was used to build the scaffolding packages. 

In the below csproj, `Microsoft.AspNetCore.All` package has `Microsoft.EntityFrameworkCore.Design` at version 2.0.1 whereas `Microsoft.VisualStudio.Web.CodeGeneration.Design` was built with version 2.0.2

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.3"  />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
  </ItemGroup>
</Project>
```

The user would see an error while scaffolding: 

```
Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.0.2.0, Culture=neutral, PublicKeyToken=...'. The located assembly's manifest definition does not match the assembly reference.
```

**The workaround** for the user would be to update the `Microsoft.AspNetCore.All` package to the latest 2.0.x version. 

cc @seancpeters @vijayrkn

**Comment by prafullbhosale** [comment]
cc @Eilon. Assigned to 2.0.8 milestone for this to be picked up by triage.

**Comment by Eilon** [comment]
@prafullbhosale thanks, understood. I'll scan for patch bugs for 2.0.8 in a couple of weeks.

**Comment by bricelam** [comment]
Removing `PrivateAssets="all"` doesn't feel like the right fix. Surely there's an alternative using binding redirects or late binding.

**Comment by prafullbhosale** [comment]
> Surely there's an alternative using binding redirects or late binding.

The binding redirects work for .NET Framework, but on NetCoreApp it only works if the EF Core assemblies (from the project graph) have a higher version than what the scaffolding assemblies were built with.

**Comment by bricelam** [comment]
What EF code to you bind to? Can it be replaced by reflection and dynamic invocations?

**Comment by prafullbhosale** [comment]
Invoking EFCore Design Apis to get the dbContext instance: https://github.com/aspnet/Scaffolding/blob/dev/src/VS.Web.CG.EFCore/EntityFrameworkModelProcessor.cs#L357-L413
Extension methods for IProperty: https://github.com/aspnet/Scaffolding/blob/dev/src/VS.Web.CG.EFCore/IPropertyExtensions.cs
Information about navigation properties: https://github.com/aspnet/Scaffolding/blob/dev/src/VS.Web.CG.EFCore/NavigationMetadata.cs

**Comment by Eilon** [comment]
@vijayrkn - any idea what should be done with this bug? I'm pretty sure this milestone isn't accurate anymore.

**Comment by vijayrkn** [comment]
I have cleared the milestone. 

@Eilon - We will triage this in the next Scaffolding triage.

**Comment by vijayrkn** [comment]
@seancpeters - Can you take a look at this and see if there is anything that needs to be done?

**Comment by vijayrkn** [comment]
Since 3.0 version does not support .NET Framework, this is not an issue any more. Closing.
