### ISSUE TITLE
Identity UI Scaffolding Code Bug: duplicate "_LoginPartial.cshtml" cause some Anti-forgery token error.

### ISSUE THREAD

**Issue by javiercn** [aspnet/Scaffolding#714]
_From kapr1k0rn_

I searched and did not see this bug was mentioned.
Following the instruction in the 2.1 Identity UI, I added the identity code back to my project, then found this: if I logout from any of the "Manage your account" pages, an anti-forgery token error would happen and caused a 400 status page. It turned out that there were 2 _LoginPartial.cshtml in the project, /Pages/Shared/_LoginPartial.cshtml and /Views/Shared/_LoginPartial.cshtml. Removing /Pages/Shared/_LoginPartial.cshtml fixed the error for me.

See related
https://github.com/aspnet/Identity/issues/1659

**Comment by javiercn** [comment]
@prafullbhosale

**Comment by vijayrkn** [comment]
I think we have logic to check for the existence of the file before adding a new one.  If this is still an issue, please re-open.
