### ISSUE TITLE
Microsoft.VisualStudio.Web.CodeGeneration.Design doesn't install after upgrade to core 2.0

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/Scaffolding#719]
_From @livarcocc on March 15, 2018 17:41_

_From @ozitraveller on August 22, 2017 1:21_

## Steps to reproduce
After the upgrade to dotnet core 2.0, I created a dotnet core 1.1 webapi project without docker support. While installing the components for the Scaffold-DbContext I need to install Microsoft.VisualStudio.Web.CodeGeneration.Design version 1.1.1

## Expected  behavior
I expected to be able to still create dotnet core 1.1 solutions

## Actual behavior
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
Package restore failed. Rolling back package changes

## Environment data

VS 2017 15.3.1

_Copied from original issue: dotnet/core-setup#3077_

_Copied from original issue: aspnet/websdk#321_

**Comment by prafullbhosale** [comment]
@mrtaunus, @ozitraveller,
Can you confirm if the `.csproj` file has the below line?

```xml
<PropertyGroup>
  <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
</PropertyGroup>
```

This is needed for installing the scaffolding package `Microsoft.VisualStudio.Web.CodeGeneration.Design` for ASP.NET Core 1.0 and 1.1 projects.

**Comment by QuAzI** [comment]
Looks like I have the same error. 
Can't create new View in asp.net core 2.1 project because VS2017 tries to install Microsoft.VisualStudio.Web.CodeGeneration.Design then write "package restore failed".

![2018-10-25_13-46-30_plguf1sz](https://user-images.githubusercontent.com/1897605/47496130-a0236600-d85e-11e8-8df3-c0b9651b60a5.png)

**Comment by vijayrkn** [comment]
This is the old behavior. This is all fixed. closing
