### ISSUE TITLE
[Preview2-Validation] Scaffolding using EF CRUD should create a sub folder automatically

### ISSUE THREAD

**Issue by Eilon** [aspnet/Scaffolding#720]
_From @kichalla on April 4, 2018 23:10_

**Repro:**
- Create a new `WebApplication` template based project
- Add a new class like the following
```c#
public class Customer
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int ZipCode { get; set; }
}
```
- Right click on Customers folder | Add Razor Page.. | Razor Pages using EntityFramework (CRUD) | Add | Choose Customer model class and ApplicationDbContext | Add

**Expected:** A `Customers` folder is created and the RazorPages views are generated in it.
**Actual**: A warning dialog like the following
![image](https://user-images.githubusercontent.com/6559784/38339302-67257a46-3822-11e8-83b3-290303e2d8ce.png)

In MVC scaffolding when we right-click on the Controllers and scaffold a controller, we use the plural service to automatically suggest `CustomersController` and also generate the views in `Customers` folder. We could do something like this for RazorPages too

_Copied from original issue: aspnet/templating#450_

**Comment by Eilon** [comment]
Should this be in the Scaffolding repo?

**Comment by seancpeters** [comment]
@Eilon @vijayrkn - The actionable work here seems to be what's said in the final part of the original issue, i.e.:

> In MVC scaffolding when we right-click on the Controllers and scaffold a controller, we use the plural service to automatically suggest CustomersController and also generate the views in Customers folder. We could do something like this for RazorPages too

This would require a change in the scaffolding UI in VS.

**Comment by prafullbhosale** [comment]
Maybe we should consider allowing the user to choose if they want the generated files in a folder or not. 
Otherwise if a user already created a desired folder and we put the generated files inside a folder using conventional name, it may not be what user intended. 

Note that the namespaces of the generated `PageModel` classes are affected based on the output path.

**Comment by vijayrkn** [comment]
We haven't heard many complaints on this and it is very easy to add the views to a new folder. Closing a low priority.
