### ISSUE TITLE
[Preview2-Validation] Adding Identity scaffolding in a RazorPages project (created without authentication) throws error

### ISSUE THREAD

**Issue by kichalla** [aspnet/Scaffolding#722]
**VS version:**
15.7.Preview 3.0 [27604.0.d15.7]

**Repro:**
- Create 'WebApplication` based project | right-click on project | Add | New Scaffolded Item.. | choose Identity on left pane | Identity | Add
- In the `Add Identity` dialog, supply `~/Pages/Shared/_Layout.cshtml` for layout textbox
- Choose to override `Account\Manage\EnableAuthenticator`
- Create a new Data context class
- Create a new User class
- You should see an error dialog pop up.

**Expected:**
No error and Identity area gets added successfully

**Actual:**
![image](https://user-images.githubusercontent.com/6559784/38385164-0a496d1a-38c6-11e8-951c-85c4f4151a4a.png)

**Workaround:**
Add the following package reference manually in the .csproj file and repeat the above steps and the scaffolding should work fine now.
`<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0-preview2-30558" />`

**Comment by danroth27** [comment]
@prafullbhosale

**Comment by seancpeters** [comment]
@kichalla @prafullbhosale @danroth27 - I believe the real solution here is to update to the latest CLI. This version `2.1.300-preview2-008530` causes this package ref to be added:
`    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0-preview2-final" />
`

**Comment by vijayrkn** [comment]
This is fixed.
