### ISSUE TITLE
[Preview2-Validation] Identity UI scaffolding doesn't allow to choose an existing user

### ISSUE THREAD

**Issue by kichalla** [aspnet/Scaffolding#723]
**VS version:**
15.7.Preview 3.0 [27604.0.d15.7]

**Repro:**
- Create 'WebApplication` based project | right-click on project | Add | New Scaffolded Item.. | choose Identity on left pane | Identity | Add
- Create the following classes
  - In **Data** folder
     ```c#
    public class ApplicationDbContext : IdentityDbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }
    }
     ```
  - In **Models** folder
     ```c#
    public class ApplicationUser : IdentityUser
    {
    }
     ```
- In the `Add Identity` dialog, supply `~/Pages/Shared/_Layout.cshtml` for layout textbox
- Choose to override `Account\Manage\EnableAuthenticator`
- You should be able to choose `ApplicationDbContext` for db context
- Now try choosing the above `ApplicationUser` for the user class

**Expected**: The above created `ApplicationUser` shows up in the dropdown and we should be able to scaffold successfully.
**Actual**: Does not show up in the dropdown.

**Comment by seancpeters** [comment]
This is by design, specifically:
- If an existing DB context is selected, no user selection can be made
- If a new DB context is selected, either a new or existing user class can be selected.
