### ISSUE TITLE
[Preview2-Validation] Identity scaffolding's IdentityHostingStartup should use the simpler `AddDefaultIdentity<TUser>` extension

### ISSUE THREAD

**Issue by kichalla** [aspnet/Scaffolding#725]
Following is how it looks like for code that is generated in `IdentityHostingStartup` file:
```c#
services.AddIdentity<RazorPagesNoAuthenticationUser, IdentityRole>()
    .AddEntityFrameworkStores<RazorPagesNoAuthenticationContext>()
    .AddDefaultUI()
    .AddDefaultTokenProviders();
```

This has the problem that if someone has their own custom IdentityUser and role (ex: `ApplicationUser: IdentityUser<Guid>, ApplicationRole: IdentityRole<Guid>`) and chose the `ApplicationUser` model, then using the generated `IdentityRole` would be incorrect.

Instead we should use the simpler extension `AddDefaultIdentity<TUser>` which just accepts a user type, so it would be
```c#
services.AddDefaultIdentity<RazorPagesNoAuthenticationUser>()
    .AddEntityFrameworkStores<RazorPagesNoAuthenticationContext>()
```

**Comment by seancpeters** [comment]
@kichalla @javiercn @mkArtakMSFT 
I cannot find an IServiceCollection extension method AddDefaultIdentity<TUser>(). It appears to have existed at one time, but doesn't currently exist in Microsoft.Extensions.DependencyInjection.IdentityServiceCollectionExtensions

**Comment by javiercn** [comment]
@HaoK

**Comment by kichalla** [comment]
Its over here https://github.com/aspnet/Identity/blob/dev/src/UI/IdentityServiceCollectionUIExtensions.cs#L32

@HaoK probably the namespace should be fixed?
