### ISSUE TITLE
Tests to ensure content generated by Identity scaffolder is in sync with content in Identity UI package

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#728]
If we end up with a mismatch, the generated content will not behave the same as intended.

**Comment by jbagga** [comment]
cc @Eilon

**Comment by Rick-Anderson** [comment]
This should be a priority as the Identity [RCL](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.2&tabs=visual-studio) is not the same as the generated code. See #937

**Comment by vijayrkn** [comment]
@HaoK - I am going to close this issue since you own both these contents (scaffolding & project creation).
