### ISSUE TITLE
Use content from Identity UI package for generating identity scaffolder code.

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#729]
Currently scaffolding packages carry all the pages and related content, needed for generating the Identity UI
Instead scaffolding should try to pick up the pages (and related files) from the identity UI package itself.

**Comment by jbagga** [comment]
cc @Eilon

**Comment by vijayrkn** [comment]
This is part of a bigger effort to consolidate all the template contents for Project Creation, Item Creation & Scaffolding. Closing.
