### ISSUE TITLE
support for github, npm and bower

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Scaffolding#73]
Hi all,
  Has been planned support to integrated download source from **github repositories** and add packages to **npm**, **bower** and **grunt** config files when writing scaffolders? I seen several yeoman generators (mean.io) that start downloading files grom github: the main advantage in hosting sources in github is that I can see changes when a new version is uploaded.

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232570&fullScreen=false&_a=edit">232570</a>

**Comment by sayedihashimi** [comment]
Hi @lucamorelli nice to see you here. We don't have a great story for custom scaffolders today. We are focused on getting .NET Core scaffolding up to par with ASP.NET, and after that we will likely start looking more into areas like this.
