### ISSUE TITLE
Consider adding a way to select entire folders to scaffold for Identity area

### ISSUE THREAD

**Issue by HaoK** [aspnet/Scaffolding#730]
It would be nice if there was some way to select everything under /Account, or everything under /Account/Manage, today you have to manually select every page.

Or at the least, it would be nice if you could select override all (then unselect it which would leave everything selected, and let you toggle the ones you don't want off, today it unselects everything)

**Comment by Rick-Anderson** [comment]
@HaoK I take it you want to do this selection from the VS UI, not from 
`dotnet aspnet-codegenerator identity  --files`

I'd like to be to select everything under /Account from the command line. I'd also like to specify overwrite all files, like VS does.

**Comment by vijayrkn** [comment]
@HaoK - Are you looking for a VS UI gesture here. Then we need a VS feedback ticket to track this. I am going to close this issue here. Let me know otherwise.

**Comment by Rick-Anderson** [comment]
We get lots of traffic  and comments on [Scaffold Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.0&tabs=visual-studio) but so far no complaints.

**Comment by vijayrkn** [comment]
Thanks @Rick-Anderson. That is good to know. 

Kudos to @HaoK and team
