### ISSUE TITLE
Identity scaffolder readme should contain instructions to run EF Core imgrations

### ISSUE THREAD

**Issue by danroth27** [aspnet/Scaffolding#733]
If you run the identity scaffolder you get a pretty cryptic error about not being able to connect to the database because of a login failure. This is because you need to run migrations. But you're starting without identity you probably don't have the database error page and there isn't anything in the readme about needing to run a migration. We should update the readme about the need to run a migration.

**Comment by seancpeters** [comment]
Fixed by #767
