### ISSUE TITLE
Identity scaffolding should not require authentication for /Account/Logout

### ISSUE THREAD

**Issue by dougbu** [aspnet/Scaffolding#734]
Logout.cshtml and Logout.cshtml.cs are used before _and after_ the user is logged out. If user posts to the Logout page without a `returnUrl` value, the page displays a message: `You have successfully logged out of the application.` Unfortunately, the page is unreachable after logging out (i.e. requires authentication) due to the following line in the generated `IdentityHostingStartup`: https://github.com/aspnet/Scaffolding/blob/6558238ab8c2add9b75b8022d1445ed20c71c7a1/src/VS.Web.CG.Mvc/Templates/Identity/IdentityHostingStartup.cshtml#L80

**Comment by dougbu** [comment]
Found while validating aspnet/Release#265

**Comment by vijayrkn** [comment]
All related issues are closed. Closing this as well.
