### ISSUE TITLE
Refresh user signin after updating their profile

### ISSUE THREAD

**Issue by dougbu** [aspnet/Scaffolding#736]
_From @Biarity on December 14, 2017 7:17_

That way, the changes are immediately visible.

_Copied from original issue: aspnet/templating/pull/199_

**Comment by dougbu** [comment]
_From @Eilon on December 19, 2017 17:13_

I'm not sure if this is necessary because there's a redirect that's about to happen anyway. I feel that even though this API is called, the "system" is overall in a "bad state" because half of it will think the user is the "old" profile, and half of it will think the user is the "new" profile.

@HaoK / @Tratcher / @blowdart - thoughts on this?

**Comment by dougbu** [comment]
_From @Tratcher on December 19, 2017 17:23_

This makes sense. The user has just changed some of their profile information in the database but still has the old values cached as claims in the auth cookie. RefreshSignInAsync issues a new auth cookie with the updated information.

**Comment by dougbu** [comment]
_From @HaoK on December 19, 2017 17:28_

Its safe to call refresh sign in generally to update the claims on the response.  That said, identity doesn't put the phone number of email in the cookie by default, so this shouldn't actually result in any claims being updated

**Comment by dougbu** [comment]
_From @blowdart on December 19, 2017 17:54_

We should add it though, for "correctness" or an illustration of what should eb done.

**Comment by dougbu** [comment]
_From @Eilon on February 2, 2018 0:59_

@jbagga can you review & merge? @Tratcher and @blowdart say it's good, so let's do it.

**Comment by dougbu** [comment]
_From @jbagga on February 2, 2018 1:1_

@Eilon Which milestone is this in?

**Comment by dougbu** [comment]
_From @Eilon on February 2, 2018 5:19_

`2.1.0-preview2`, so just `dev`

**Comment by dougbu** [comment]
_From @jbagga on February 5, 2018 21:54_

The code has moved to Identity UI https://github.com/aspnet/Identity/pull/1615

**Comment by dougbu** [comment]
_From @jbagga on February 5, 2018 21:55_

@Biarity Thanks for the suggestion! The code change has been moved to the new location.

**Comment by dougbu** [comment]
This issue is much less about the original PR (aspnet/templating#199) than the final changes made to fix aspnet/Identity#1616. Those changes should be done here too.

**Comment by blowdart** [comment]
Fine by me
