### ISSUE TITLE
Account/Manage/_ViewStart missing after scaffold

### ISSUE THREAD

**Issue by HaoK** [aspnet/Scaffolding#740]
This causes the Sidebar to be missing:

Create a new WAP/Scaffold overriding all files
Login with bogus data to trigger Apply Migration
Register a user
Click on hello user to go to manage
Expect to see the Profile/TwoFactor/Privacy side bar, Actual: no sidebar

**Comment by vijayrkn** [comment]
Closing since this is fixed.
