### ISSUE TITLE
Review how identity scaffolder updates the layout to add the login partial

### ISSUE THREAD

**Issue by danroth27** [aspnet/Scaffolding#743]
Currently the identity scaffolder updates the app layout with the following code to add the login partial:

```html
            <div class="navbar-collapse collapse">
                @{
                    var result = Engine.FindView(ViewContext, "_LoginPartial", isMainPage: false);
                }
                @if (result.Success)
                {
                    await Html.RenderPartialAsync("_LoginPartial");
                }
                else
                {
                    throw new InvalidOperationException("The default Identity UI layout requires a partial view '_LoginPartial' " +
                        "usually located at '/Pages/_LoginPartial' or at '/Views/Shared/_LoginPartial' to work. Based on your configuration " +
                        $"we have looked at it in the following locations: {System.Environment.NewLine}{string.Join(System.Environment.NewLine, result.SearchedLocations)}.");
                }
            </div>
```

We should review this code and make share it is appropriate for all layouts.

**Comment by danroth27** [comment]
@javiercn

**Comment by NeelBhatt** [comment]
@danroth27 - I am getting this error while using Identity as UI feature. I added all necessary steps but after opening the Register link I am getting - "The default Identity UI layout requires a partial view '_LoginPartial' usually located at '/Pages/_LoginPartial' or at '/Views/Shared/_LoginPartial' to work. Based on your configuration we have looked at it in the following locations: " 

Any suggestions?

**Comment by javiercn** [comment]
@danroth27 I believe this is fixed in RTM. @seancpeters can you confirm?

**Comment by phantom2017-Nov** [comment]
It is 2018, and you decided to hard code a reference to a "_LoginPartial" in your code ! Wow! 
Why do you keep changing things that are working, especially if you can't give a seamless upgrade ... This is wasting time to figure out where the reference to this file is & how to get rid of it - if at all possible. Further, it seems to generate its own templated page .. who asked for all of this brilliancy from your side ?

**Comment by danroth27** [comment]
Hi @phantom2017-Nov. I'd like to help out. Can you tell me more about what you're trying to do and which changes specifically are causing you issues?

**Comment by Rick-Anderson** [comment]
Can this issue (fixed in RTM) be closed?  cc @seancpeters

**Comment by seancpeters** [comment]
@danroth27 - this is a content issue, so I'd leave it to you to close it if appropriate.

**Comment by vijayrkn** [comment]
@HaoK - Do you know if this already fixed?

**Comment by Rick-Anderson** [comment]
It works for:

* Scaffold identity into a Razor project **without** existing authorization
* Scaffold identity into a Razor project **with** authorization
* Scaffold identity into a MVC project **without** existing authorization
* Scaffold identity into a MVC project **with** authorization

See [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.0&tabs=visual-studio#scaffold-identity-into-a-razor-project-without-existing-authorization)

**Comment by vijayrkn** [comment]
@Rick-Anderson do you think we can close this then? Are there scenarios that doesn’t work?

**Comment by Rick-Anderson** [comment]
Close it.  We get alot of traffic and comments on that topic.
 That page gets 18.5 PV/month.
