### ISSUE TITLE
Flaky test: TestGetModelMetadata_WithoutDbContext

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Scaffolding#750]
This test [fails](http://aspnetci/viewLog.html?buildId=445280&tab=buildResultsDiv&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR#testNameId-192309633891822940) occasionally with the following error:

```
System.InvalidOperationException : Restore failed with exit code: 134 :: Dotnet path: /mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet
   at Microsoft.VisualStudio.Web.CodeGeneration.MsBuildProjectSetupHelper.RestoreAndBuild(String path, ITestOutputHelper output) in /_/test/Shared/MsBuildProjectSetupHelper.cs:line 114
   at Microsoft.VisualStudio.Web.CodeGeneration.MsBuildProjectSetupHelper.SetupProjects(TemporaryFileProvider fileProvider, ITestOutputHelper output, Boolean fullFramework) in /_/test/Shared/MsBuildProjectSetupHelper.cs:line 79
   at Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.Test.CodeModelServicesTests.TestGetModelMetadata_WithoutDbContext() in /_/test/VS.Web.CG.EFCore.Test/CodeModelServiceTests.cs:line 59
------- Stdout: -------
Restoring packages for /mnt/temp/buildTmp/tmpfiles/80796e17-d420-4c41-b8b2-5958d313f239/Library1/Library1.csproj...
  Restoring packages for /mnt/temp/buildTmp/tmpfiles/80796e17-d420-4c41-b8b2-5958d313f239/Root/Test.csproj...
```

Future instances of this failure can be found [here](http://aspnetci/project.html?tab=testDetails&testNameId=-192309633891822940&projectId=XPlat&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

**Comment by ryanbrandenburg** [comment]
TestAreaGenerator [failed again](http://aspnetci/viewLog.html?buildId=519624&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by aspnet-hello** [comment]
TestIdentityGenerator_IndividualFiles_AllFilesBuild [failed with about the same error](http://aspnetci/viewLog.html?buildId=558127&buildTypeId=Releases_22xPublic_OsxUniverse) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 28 failures [with about the same error](http://aspnetci/viewLog.html?buildId=558941&buildTypeId=Releases_22xPublic_UbuntuUniverse) on 2.2:
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- (And 18 more test failures in this build)


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 28 failures [with about the same error](http://aspnetci/viewLog.html?buildId=559352&buildTypeId=Releases_22xPublic_OsxUniverse) on 2.2:
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- (And 18 more test failures in this build)


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 28 failures [with about the same error](http://aspnetci/viewLog.html?buildId=559827&buildTypeId=Releases_22xPublic_Win2012) on 2.2:
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- (And 18 more test failures in this build)


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by BrennanConroy** [comment]
@Eilon No one is pinged for scaffolding issues? Or this was made before that was added.

Either way no one is looking at this!

**Comment by ryanbrandenburg** [comment]
This issue predates @'ing managers. (You can tell because my account made it and not the hello bot).

**Comment by Eilon** [comment]
@vijayrkn - can someone on your team take a look at this test failure?

**Comment by vijayrkn** [comment]
@seancpeters - Can you please take a look?

**Comment by aspnet-hello** [comment]
There were 28 failures [with about the same error](http://aspnetci/viewLog.html?buildId=560348&buildTypeId=Releases_22xPublic_OsxUniverse) on 2.2:
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- (And 18 more test failures in this build)


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by seancpeters** [comment]
@pranavkm - I think I'm going to need your help on this one. The actual problem is due to this error:
`Assembly location for Razor SDK Tasks was not specified. The most likely cause is an older incompatible version of Microsoft.NET.Sdk.Razor, or Microsoft.NET.Sdk.Web used by this project. Please target a newer version of the .NET Core SDK.`

My guess is that somehow I'm referencing two different gersions of Microsoft.AspnetCore.Razor.Design, but I'm not seeing how this is occurring.

Probably easiest if we chat in person tomorrow.
Thanks!

**Comment by aspnet-hello** [comment]
There were 28 failures [with about the same error](http://aspnetci/viewLog.html?buildId=561409&buildTypeId=Releases_22xPublic_Win2012) on 2.2:
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- TestIdentityGenerator_IndividualFiles_AllFilesBuild
- (And 18 more test failures in this build)


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=567375&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 9:11:39 AM:
- TestIdentityGenerator_IndividualFiles_AllFilesBuild

**Comment by vijayrkn** [comment]
Moved to arcade. This shouldn't be an issue going forward.
