### ISSUE TITLE
Create and Edit Razor pages have errors when the model class has a boolean property in it.

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#751]
Related: #709 

cc @seancpeters, @Eilon @vijayrkn

**Comment by Eilon** [comment]
@vijayrkn - any idea what should be done with this bug? I'm pretty sure this milestone isn't accurate anymore.

**Comment by vijayrkn** [comment]
I have cleared the milestone. Will pick it up in the next triage.

**Comment by vijayrkn** [comment]
This is fixed.
