### ISSUE TITLE
Use partial tag helper instead of @Html.Partial

### ISSUE THREAD

**Issue by jbagga** [aspnet/Scaffolding#756]
Currently we use `@Html.Partial` for `_StatusMessage` for multiple Identity scaffolder razor pages.

For example: https://github.com/aspnet/Scaffolding/blob/dev/src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Manage/Account.Manage.ChangePassword.cshtml#L8

When scaffolding Identity, this leads to several warnings suggesting use of partial tag helper

**Comment by tura08** [comment]
This is a pretty easy fix. Would the team be happy to accept a PR for this?

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/aspnet/Scaffolding/commit/2ad31dbd843fb2ac7b9f5c586dc9d3b269209f52.
