### ISSUE TITLE
Identity Scaffolding: Existing user class should be used in generated pages

### ISSUE THREAD

**Issue by seancpeters** [aspnet/Scaffolding#761]
1. Create a new Web Application | No Auth
2. Create a custom user class, and a DB context that uses the custom user class.
3. Open the Identity scaffolder, select the existing DB context.
4. Select some user management pages to scaffold (e.g.: login, register, logout)

Expected:
The newly scaffolded user management pages should use the custom user class specified in the DB context.

Actual:
The default IdentityUser is referenced in the scaffolded pages.

Also, if possible, when an existing DB context is selected, detect its user class, and show it in the user class selector. This should not change the behavior where the user class selector is disabled when an existing DB context is selected, it should just show the user the associated user context.

**Comment by prafullbhosale** [comment]
Closed by #765
