### ISSUE TITLE
Identity Scaffolding: Pages not chooseable by the user need to be generated appropriately

### ISSUE THREAD

**Issue by seancpeters** [aspnet/Scaffolding#763]
We need to identify in exactly which situations pages not selectable in the Identity Scaffolder UI should be generated, and where. This also includes where to look for existing instances of those pages in the user project. 

Pages that must be dealt with include:
- _LoginPartial
- _ViewImports
- _ViewStart
- _ValidationScriptsPartial

**Comment by seancpeters** [comment]
These specs are from an email @javiercn:
•	Whenever we generate a layout we need to generate all supporting files if they are not present (Take the files/layout present on the templates as a reference):
o	  _LoginPartial
o	  _ValidationScriptsPartial
o	  _CookieConsentPartial
o	  _ViewImports
o	  _ViewStart
Think of it as transitioning from empty to (MVC|RazorPages) with Individual user accounts.

•	Location for generating the Layout:
o	  If there is already a _Layout.cshtml file in Pages/Shared, all supporting files should go there (if they don't exist).
o	  If there is already a _Layout.cshtml file in Views/Shared, all supporting files should go there (if they don't exist).
•	  If there is no _Layout.cshtml in Pages/Shared nor Views/Shared:
o	    If there is a Pages folder, the layout and supporting files should go in Pages/Shared
o	    If there is a Views folder, the layout and supporting files should go in Views/Shared
o	    If there is no Pages nor Views folder, the layout and supporting files should go in the Pages/Shared folder

**Comment by seancpeters** [comment]
Update from @javiercn 
Above is the logic for when we generate the layout file.

The only correction is that when we are using an existing layout on the app, we will only generate the login partial, not any of the other partials.

Also the _ViewStart in Areas/Identity/Pages/ needs to be updated to point to the layout in either Views/Shared, Pages/Shared, or the layout chosen by the user.

**Comment by seancpeters** [comment]
@javiercn - looking at this now. We don't have a _CookieConsentPartial page in the current identity scaffolding.

**Comment by seancpeters** [comment]
@javiercn @mkArtakMSFT 
Also, should we check for the existence of _LoginPartial, _ViewImports, _ViewStart, and _ValidationScriptsPartial in Pages/Shared/ and Views/Shared regardless of what was discovered about the _Layout file, or only look in the same location as the _Layout file (if found)? 

Note:
After the previous updates to this, we were looking for _LoginPartial in Pages/ and Pages/Shared/

**Comment by seancpeters** [comment]
@javiercn @mkArtakMSFT 

> The only correction is that when we are using an existing layout on the app, we will only generate the login partial, not any of the other partials.

Are all of _LoginPartial, _ViewImports, _ViewStart, and _ValidationScriptsPartial considered to be "partials"? Or are the partials only _LoginPartial & _ValidationScriptsPartial?

**Comment by seancpeters** [comment]
@javiercn @mkArtakMSFT 
We're going to need to discuss the _ViewImports page generation a bit more. Where it gets looked for, and if it gets generated and if so where - is currently a lot more complicated than just checking it's existence in one place.

**Comment by seancpeters** [comment]
@javiercn @mkArtakMSFT 
We'll also need to discuss the _ValidationScriptsPartial page generation. Currently if it's generated, it goes into Areas/Identity/Pages/_ValidationScriptsPartial.cshtml

We'll have to determine if it continues to go there, or if it should go where the _Layout file is generated / already exists.

**Comment by javiercn** [comment]
_ViewImports and _ViewStart are not partials. I would say that when in doubt, follow the same layout as the MVC/Razor pages with individual user accounts templates and use the presence of a Pages folder to determine whether the app is “Razor pages” or MVC.
If the user explicitly selected a Layout that is not in Pages/Shared, Views/Shared, I would just scaffold everything else on the same folder. I think that would be a more advanced scenario.

**Comment by muratg** [comment]
@vijayrkn @seancpeters Any status update on this guys?

**Comment by seancpeters** [comment]
@vijayrkn @muratg - this was dealt with in PR #766, merged earlier in the week.
