### ISSUE TITLE
External login provider and confirm email page is not accessible when using global authorize filter

### ISSUE THREAD

**Issue by blowdart** [aspnet/Scaffolding#769]
_From @jbagga on April 18, 2018 18:53_

When an external login provider is configured, and a global authorize filter is applied, clicking the button to navigate to the provider (say Twitter sign in) redirects back to the current Login page.

To allow anonymous users to log in to an external provider while using a global authorize filter, the user can scaffold the `ExternalLogin.cshtml.cs` page and add the `AllowAnonymous` attribute to the `ExternalLoginModel`.

Please note, if this is something we want to allow by default, a corresponding change must also be made in aspnet/Scaffolding repo.

_Copied from original issue: aspnet/Identity#1762_

**Comment by blowdart** [comment]
This should be allowed by default, otherwise you can't login. Can you create the corresponding bug please?

**Comment by blowdart** [comment]
Never mind, I'm told I can move it :D

**Comment by jbagga** [comment]
FYI @mkArtakMSFT This is "SHP: Approval Pending" as well. The label doesn't exist in the repo yet
