### ISSUE TITLE
Scaffolding MVC Controller w/ views into area puts Controller in wrong spot

### ISSUE THREAD

**Issue by natelaff** [aspnet/Scaffolding#773]
1) Create an Area in an ASP.NET Core 2.1 app, i.e. Admin
2) Create a simple model
3) Add Scaffolded MVC Controller with Views (EF) into Area

Controller.cs goes into the root of the Area, rather than the pre-created Controllers folder.

**Comment by vijayrkn** [comment]
@natelaff - Is this from the commandline or VS?

**Comment by natelaff** [comment]
@vijayrkn -- it would have been VS. I don't remember the specifics of this though other than those steps. Maybe it's fixed by now, it's been 18+ months.

**Comment by vijayrkn** [comment]
Will close this issue. If you run into this issue from VS, can you please use the VS feedback system (Help -> File issue) to report this. Thank you for using the tools & reporting issues to help make the experience better.
