### ISSUE TITLE
Identity scaffolding in core 2.1 - scaffold account-/managecontrollers

### ISSUE THREAD

**Issue by houbi56** [aspnet/Scaffolding#779]
It should be possible to scaffold the account and manage controllers. Or should I have to copy the code or use asp core 2.0?
Not sure if this is a vs 2017 preview issue or scaffold issue but how would I go about to get the same behaviour (getting all view and controllers for identity genereated) as in vs2017 15.6?

**Comment by vijayrkn** [comment]
We made a decision to support only the Razor pages version of the Identity UI.

**Comment by blowdart** [comment]
Dupe of https://github.com/aspnet/Identity/issues/1658
