### ISSUE TITLE
aspnet-codegenerator nuget version still at 2.1.0-preview1-final

### ISSUE THREAD

**Issue by ghost** [aspnet/Scaffolding#783]
Since 2.1.0-rc1 is now released, shouldn't this package also be updated on nuget? Or is this now available via global tools?

https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGeneration.Tools/

**Comment by prafullbhosale** [comment]
> Or is this now available via global tools?

@tura08 you are correct. This is now available as a global tool 
[dotnet-aspnet-codegenerator](https://www.nuget.org/packages/dotnet-aspnet-codegenerator/2.1.0-rc1-final)

**Comment by tura08** [comment]
Though I was missing something, thanks. I was able to successfully install it via:

`dotnet tool install -g dotnet-aspnet-codegenerator --version 2.1.0-rc1-final`.

Is this documented somewhere because I couldn't find references to it on docs.microsoft?

**Comment by vijayrkn** [comment]
Closing since we have the most recent Scaffolding package versions available in NuGet.org
