### ISSUE TITLE
Remove unused, stale versions of jQuery

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Scaffolding#796]
Follow-up to https://github.com/aspnet/Scaffolding/pull/795#issuecomment-389614308

It appears we still have jQuery 1.10 embedded in some scaffolding templates. We should move this forward to jquery 3.x.

https://github.com/aspnet/Scaffolding/blob/release/2.1/src/VS.Web.CG.Mvc/Templates/StaticFiles/Scripts/jquery-1.10.2.js
https://github.com/aspnet/Scaffolding/blob/release/2.1/src/VS.Web.CG.Mvc/Templates/StaticFiles/Scripts/jquery.validate.js
https://github.com/aspnet/Scaffolding/blob/release/2.1/src/VS.Web.CG.Mvc/Templates/StaticFiles/Scripts/jquery-1.10.2.min.js
https://github.com/aspnet/Scaffolding/blob/release/2.1/src/VS.Web.CG.Mvc/Templates/StaticFiles/Scripts/jquery-1.10.2.intellisense.js
https://github.com/aspnet/Scaffolding/blob/release/2.1/src/VS.Web.CG.Mvc/Templates/StaticFiles/Scripts/jquery.validate-vsdoc.js
https://github.com/aspnet/Scaffolding/blob/release/2.1/src/VS.Web.CG.Mvc/Templates/StaticFiles/Scripts/jquery.validate.min.js

cc @vijayrkn @prafullbhosale

**Comment by natemcmaster** [comment]
Both @seancpeters and I looked at this. We could not identify a way in which these files end up in customer app. If that's the case, let's just remove these from our repo entirely to avoid future confusion.

cc @prafullbhosale

**Comment by prafullbhosale** [comment]
I agree, I tried reproing based on what the code should do -> Empty project -> add new View with some model class. 
And that doesn't add the files. 
These files are being used only by the Dependency scaffolders. The dependency scaffolder itself can be removed completely. They cannot be invoked via commandline anyways.

**Comment by seancpeters** [comment]
#804 and #807 remove the content, and code, respectively.
