### ISSUE TITLE
Move scaffolding content to aspnet/templating

### ISSUE THREAD

**Issue by seancpeters** [aspnet/Scaffolding#798]
The scaffolding content needs to stay in sync with the aspnet templates used by dotnet/templating in with dotnet new and in Visual Studio project creation. It will be easier to keep them in sync if they're in the same repo.

Scaffolding will be modified to consume a nupkg containing the content, which will need to be published by aspnet/templating.

**Comment by vijayrkn** [comment]
Closing this since this is part of the larger code generation template consolidation effort.
