### ISSUE TITLE
Adding controller hangs Visual Studio

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Scaffolding#806]
_From @donnyv on May 31, 2018 19:50_

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):
Uninstall Nuget package Microsoft.EntityFrameworkCore.SqlServer and then use Visual Studio right click to create a new controller.

#### Description of the problem:
When using Visual Studio to create a new controller. The process hangs because it installs Microsoft.EntityFrameworkCore.SqlServer nuget package. When you try again after install, it works.

Why do you need this reference just to add a new controller?

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`: Microsoft.AspNetCore.Mvc

_Copied from original issue: aspnet/Mvc#7844_

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this issue, @donnyv.
@vijayrkn, seems this is caused by the scaffolder. Will move to the appropriate repo now.

**Comment by vijayrkn** [comment]
This should be fixed in the latest version.
