### ISSUE TITLE
Scaffolding 2.1 RTM in existing MVC application 404 for non overridden pages

### ISSUE THREAD

**Issue by javiercn** [aspnet/Scaffolding#811]
_From @dotnetshadow on June 1, 2018 5:7_

I recently upgraded my ASP.NET Core application 2.1. I used the identity scaffolder to override Login and Register pages. Upon doing this I noticed that routes to logout and manage were incorrect

`?page=Account/Manage` rather than `/Identity/Account/Manage`

I then rescaffolded and this time and chose to override all files. This seemed to work. 
In my particular case there seems to be an issue with scaffolding just a handful of pages and not being able to find the remaining pages that aren't scaffolded

Just wondering if I'm missing something?

**update**
I think the issue i have is that i was using AddIdentity instead of AddDefaultIdentity. Unfortunately i am unable to try this yet 

_Copied from original issue: aspnet/Identity#1809_

**Comment by javiercn** [comment]
_From @blowdart on June 1, 2018 21:9_

@javiercn Does this happen for you?

**Comment by javiercn** [comment]
@vijayrkn @seancpeters Can you take a look at this?

**Comment by javiercn** [comment]
@dotnetshadow Are you upgrading a 2.0 app to 2.1 or starting from a 2.1 app?

**Comment by dotnetshadow** [comment]
@javiercn updating from 2.0 app

**Comment by dotnetshadow** [comment]
@javiercn I can confirm that the issue is indead that I was using `services.AddIdentity<ApplicationUser, IdentityRole>` as opposed to `services.AddDefaultIdentity<ApplicationUser>`

After using **AddDefaultIdentity**, the non scaffolded routes worked

**Comment by javiercn** [comment]
@dotnetshadow Thanks for following up. I will be closing this issue as there’s no action to be taken here.

Thanks!
