### ISSUE TITLE
Scaffolding a new controller fails when no internet connection

### ISSUE THREAD

**Issue by mkArtak** [aspnet/Scaffolding#814]
Tried to generate a new controller, while had no internet connection, and got the following error:
![error when creating new controller without intenet connection](https://user-images.githubusercontent.com/7347708/41198694-91aa7cae-6c38-11e8-99dd-16c3d35e0d1c.png)

.NET SDK version: 2.1.300
VS version: 15.7.3

**Comment by mkArtak** [comment]
Seems weird, as the new controller should require no NuGet dependencies during creation.

**Comment by seancpeters** [comment]
Can you post a more detailed repro to generate this error? When I try to scaffold a controller offline without already having the Microsoft.VisualStudio.Web.CodeGeneration.Design package refernce in my project (and correctly restored), this is the error I get:

![image](https://user-images.githubusercontent.com/20912881/41377477-feae480a-6f10-11e8-8256-946aee726997.png)

If i do have that package referenced and installed, then I can successfully scaffold a controller offline. It's that package that scaffolding is attempting to add & restore when creating a new controller.

**Comment by mkArtak** [comment]
I'll try to repro that later and share it.

**Comment by mkArtakMSFT** [comment]
I couldn't repro this really. However, the setup I had when this happened was I was connected to a public wifi point, which shown as connect, but I couldn't actually open any websites. That may give you some clue. If not, unfortunately I can't provide a repro either.

**Comment by vijayrkn** [comment]
Closing since I cant repro this issue.
