### ISSUE TITLE
Namespace of generated DbContext class uses Models when it should use Data

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Scaffolding#822]
When you scaffold EF/CRUD the new DC uses Models in the namespace when it should use Data
![image](https://user-images.githubusercontent.com/3605364/41869829-244ef32c-786f-11e8-8b66-19f672493624.png)

The DC
```
namespace ContosoUniversity.Models
{
    public class ContosoUniversityContext : DbContext
    {
        public ContosoUniversityContext (DbContextOptions<ContosoUniversityContext> options)
            : base(options)
        {
        }

        public DbSet<ContosoUniversity.Models.Student> Student { get; set; }
    }
}
```
But it’s not in the *Models* folder, it’s in the *Data* folder. The namespace should be `ContosoUniversity.Data`

**Comment by Rick-Anderson** [comment]
@seancpeters  this causes alot of confusion in our tutorials. Can we get this scheduled for 3.1?

**Comment by ajcvickers** [comment]
@vijayrkn: @Rick-Anderson is pinging Sean here, so just pinging you so it doesn't get missed.

**Comment by vijayrkn** [comment]
Thank you @ajcvickers . 

@Rick-Anderson - I don't have a dev assigned to the Scaffolding feature yet. Will get to this once we have active resource working on this. 
(Sean has moved to a new company and is not with Microsoft any more)

**Comment by Rick-Anderson** [comment]
I opened [this VS bug](https://developercommunity.visualstudio.com/content/problem/652166/aspnet-core-ef-scaffolder-uses-incorrect-namespace.html) as the CLI is using the correct namespace.
