### ISSUE TITLE
Scaffolder error: Unexpected character encountered while parsing value: . Path", line 0 position 0."

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Scaffolding#823]
From https://github.com/aspnet/Docs/issues/7014

When the scaffolder is run (form VS or the CLI), the following error is returned

c:\RazorPagesMovie>dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPages
Movie.Data.MovieContext -udl -outDir Pages\Movies --referenceScriptLibraries
[Trace]: Command Line: razorpage -m Movie -dc RazorPagesMovie.Data.MovieContext
-udl -outDir Pages\Movies --referenceScriptLibraries
Building project ...
[Trace]: Command Line: --no-dispatch --port-number 63890 razorpage -m Movie -dc
RazorPagesMovie.Data.MovieContext -udl -outDir Pages\Movies --referenceScriptLib
raries --dispatcher-version 2.1.0-rtm-30799
Unexpected character encountered while parsing value: A. Path '', line 0, positi
on 0.
Scaffolding failed.
Unexpected character encountered while parsing value: A. Path '', line 0, positi
on 0.
Unable to write data to the transport connection: An existing connection was for
cibly closed by the remote host.
[Trace]: at Microsoft.VisualStudio.Web.CodeGeneration.Design.ScaffoldingClien
t.ReadMessage()
at Microsoft.VisualStudio.Web.CodeGeneration.Design.MessageOrchestrator.GetPr
ojectInformation()
at Microsoft.VisualStudio.Web.CodeGeneration.Design.Program.<>c__DisplayClass
4_0.<b__0>d.MoveNext()
RunTime 00:00:08.95

cc @FDillon00

**Comment by Rick-Anderson** [comment]
Haven't seen this error in a while so closing.

**Comment by Rick-Anderson** [comment]
@seancpeters 	see aspnet/Docs#7014 
It's probably still a problem but rare and unable to reproduce. If I get another customer reporting this I'll reopen and engage customer.

**Comment by noahjanderson** [comment]
I'm getting the same error:

PS C:\Users\noah.anderson\source\repos\TestingModelScaffolding> dotnet aspnet-codegenerator controller -name ConfigOutputTablesController -async -api -m ConfigOutputTables -dc ApplicationDBContext -outDir Controllers
Building project ...
Unexpected character encountered while parsing value: :. Path '', line 0, position 0.
Scaffolding failed.
Unexpected character encountered while parsing value: :. Path '', line 0, position 0.
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..
To see more information, enable tracing by setting environment variable 'codegen_trace' = 1.
RunTime 00:00:15.70

**Comment by Rick-Anderson** [comment]
@noahjanderson  what version of .NET Core SDK? 
``dotnet --version``

Did you install the global scaffolder?
If so, open an issue at https://github.com/aspnet/Scaffolding/issues with all this info and point to this issue.

**Comment by noahjanderson** [comment]
```
PS C:\Users\noah.anderson\source\repos\SampleWebApp> dotnet --version
3.1.101
```
Yes I did install the global scaffolding tool.

Will do, thank you.
