### ISSUE TITLE
Scafolding Models with bool Type Results in Error in CreateModel

### ISSUE THREAD

**Issue by Eilon** [aspnet/Scaffolding#830]
_From @robinwilson16 on April 25, 2018 22:25_

I have found if I add a bool field to a data model - i.e.:
`public class Customer`
    `{`
        `...`
        `public bool CanBeContacted { get; set; }`
        `...`
    `}`

Then generate the model:
`dotnet aspnet-codegenerator razorpage -m Customer -dc ApplicationDbContext -udl -outDir Pages\Customers --referenceScriptLibraries`

The reference is incorrectly generated as:
`<input asp-for="Customer.CanBeContacted" /> @Html.DisplayNameFor(model => model.CanBeContacted))`

When it misses out the model reference and also adds a superfluous closing bracket so it should be:
`<input asp-for="Customer.CanBeContacted" /> @Html.DisplayNameFor(model => model.Customer.CanBeContacted)`

This happens every time I try to add a bool field and run code generator so would seem to be a bug?

The fix is to add the model reference manually (the code is underlined as an error) then it works.

The same is true for the update page except the extra bracket is not also added.

_Copied from original issue: aspnet/Home#3095_

**Comment by seancpeters** [comment]
@robinwilson16 - I've just made PR #832  for the extra trailing paren. 

The issue with the incorrect model was recently addressed here: #709.

**Comment by robinwilson16** [comment]
Hello Sean

Thanks for the update and for fixing it.

Robin

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
