### ISSUE TITLE
Add Custom scaffolding Views 

### ISSUE THREAD

**Issue by mgolois** [aspnet/Scaffolding#833]
From my research, seems like I can only add overwrite the existing scaffolding views (Create, Delete, Details, Edit, List, etct..). However, in previous versions of MVC, I was able to add custom scaffolding views to the list of templates, so that when  a developer wanted to add a viewsmy customs views will also show up be list.
How can I achieve that? Thank you!

**Comment by seancpeters** [comment]
@mgolois
With the current version of MVC scaffolding, there are 2 ways to customize scaffolding. 

The first way is along the lines you were indicating, where it’s possible to overwrite existing scaffolded views. But with this method, as you suspected, it’s not possible to add additional custom views.

The second way is a bit more involved. It is possible to create a new custom scaffolder and add your own content to it. Unfortunately we don’t have much for good, current documentation. Below are the best docs available, but they’re about creating custom MVC5 scaffolders. This should include the necessary steps to create a custom scaffolder for Visual Studio, but may fall short of providing enough info for scaffolding on asp.net core:
-	https://www.safaribooksonline.com/library/view/bootstrap-for-aspnet/9781783987283/ch06s05.html
o	Note: requires a login, a Microsoft email address allows single sign-on.
-	https://blogs.msdn.microsoft.com/webdev/2014/04/03/creating-a-custom-scaffolder-for-visual-studio/

**Comment by mgolois** [comment]
Thank you @seancpeters !

**Comment by davidbuckleyni** [comment]
Do u have a sample github looking to modify the controller scaffolding to add new code to the views ?
