### ISSUE TITLE
.NET Core 2.1.302 and aspnet-codegenerator identity doesnt work.

### ISSUE THREAD

**Issue by omnoms** [aspnet/Scaffolding#838]
Trying to follow this https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=netcore-cli

And I face this
```
dotnet aspnet-codegenerator identity --useDefaultUI
[Trace]: Command Line: identity --useDefaultUI
Scaffolding failed.
Failed to get Project Context for C:\Projekt\Privat\QRID\QRID.csproj.

[Trace]:    at Microsoft.Extensions.ProjectModel.MsBuildProjectContextBuilder.Build() in /_/src/Ext.ProjectModel.MsBuild.Sources/MsBuildProjectContextBuilder.cs:line 70
   at Microsoft.VisualStudio.Web.CodeGeneration.Tools.Program.BuildAndDispatchDependencyCommand(String[] args, String projectPath, String buildBasePath, String configuration, Boolean noBuild, ILogger logger) in /_/src/dotnet-aspnet-codegenerator/Program.cs:line 175
   at Microsoft.VisualStudio.Web.CodeGeneration.Tools.Program.<>c__DisplayClass19_0.<Execute>b__0() in /_/src/dotnet-aspnet-codegenerator/Program.cs:line 109
RunTime 00:00:01.56
```

**Comment by seancpeters** [comment]
@omnoms - this type of error is often caused because the project being scaffolded does not build. Could you check if your project will build on its own? Also, please make sure that the Microsoft.VisualStudio.Web.CodeGeneration.Design package was correctly added to your project.

If the above doesn't help, could you post the contents of your .csproj file here, it may give me some indication of the problem.

**Comment by omnoms** [comment]
It builds. Its just a brand new "dotnet new angular".

**Comment by omnoms** [comment]
I had run the dotnet add package line but now that I inspect the csproj file i see that it's actually missing. So that failed silently somehow. Adding it manually and running dotnet restore allowed for the scaffolding to succeed. Thanks!

**Comment by seancpeters** [comment]
Glad you got it working! If dotnet add package is consistently failing for you, perhaps file a bug here:
https://github.com/dotnet/cli
