### ISSUE TITLE
Are there any design docs, wiki,  usecases or scenarios the scaffolding is trying to solve?

### ISSUE THREAD

**Issue by erichexter** [aspnet/Scaffolding#84]
Just wondering what the goal for the use experience is, for both using the scaffolder as well as creating  custom scaffolders

**Comment by sayedihashimi** [comment]
Hi @erichexter sorry for the delay here. For future reference please use the [tooling repo](https://github.com/aspnet/Tooling) for issues as it's monitored more than this repo is.

To answer your question, it's designed to enable the same scenarios as ASP.NET 4 scaffolding. You can find a walk through at https://github.com/aspnet/Tooling/blob/master/specs/vs-scaffolding.pptx.

If you have any more questions please open an issue in the tooling repo, I'm closing this one.
