### ISSUE TITLE
Scaffoling does not follow MS best practice for list iteration

### ISSUE THREAD

**Issue by natelaff** [aspnet/Scaffolding#847]
Was looking through docs
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-2.1

There is this note:

> Always use for (and not foreach) to iterate over a list. Evaluating an indexer in a LINQ expression can be expensive and should be minimized.

However, when scaffolding EF views, the Index view will generate with foreach.

So, which one should we use? :)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @natelaff. It seems that doc article has been tweaked already and doesn't contain such statement any more. Using `foreach` is reasonable and in some cases is even the only way to iterate over elements.
