### ISSUE TITLE
Identity Scaffolding creates empty Services folder

### ISSUE THREAD

**Issue by isaac2004** [aspnet/Scaffolding#857]
## Steps to reproduce:
 - Create new ASP.NET Core 2.1 Project with Identity
 - Scaffold Identity
 - Empty Services Folder with no Email or SMS Services

## Expected behavior:
 - Per @blowdart it seems weird the services aren't generated, the base ones provided in the past should be there at least

## Actual behavior:
 - Nothing in Services folder

**Comment by blowdart** [comment]
@javiercn @mkArtakMSFT

**Comment by javiercn** [comment]
@seancpeters @vijayrkn Can you take a look at this? There should not be a services folder.

**Comment by seancpeters** [comment]
I know why this is happening, I'll get a PR out with the fix.

**Comment by seancpeters** [comment]
With identity scaffolding, we've never had any services scaffolded (such as the ones mentioned in the original post). If it's desired to add those services, let's discuss exactly what we want to add.

**Comment by isaac2004** [comment]
My personal opinion is that the scaffold experience should be very similar to the experience before scaffolding was introduced (i.e. EmailService and SMSService scripted as part of template). If the team disagrees, I would like to know why not making those services available is ideal over the old experience which allowed developers to quickly build out identity apps.

**Comment by javiercn** [comment]
The services mentioned are part of the UI package. We don’t want to scaffold the services because that prevents people from shipping third party package implementations that can be reused.

**Comment by isaac2004** [comment]
If that is truly the goal it should be documented somewhere. If I scaffold identity, the email for account setup does not work out of box.

**Comment by javiercn** [comment]
@Rick-Anderson Can you add something on the docs for this?

**Comment by isaac2004** [comment]
I can add this needed info to the scaffold doc.

**Comment by seancpeters** [comment]
The creation of the empty services folder is fixed as part of with #866

**Comment by Rick-Anderson** [comment]
@isaac2004  yes, PR the doc.
