### ISSUE TITLE
Unable to build project, on OSX (and likely Linux, too)

### ISSUE THREAD

**Issue by TheDarkTrumpet** [aspnet/Scaffolding#86]
Steps to Reproduce:
1) Git clone the repository (dev branch)
2) sh build.sh

The error I'm getting is:
Errors in /Users/dthole/Programming/Scaffolding2/test/Microsoft.Framework.CodeGeneration.Core.FunctionalTest/project.json
    Unable to locate ModelTypesLocatorTestWebApp >= 1.0.0

On a side note, is this project basically supposed to replace the asp generator app that was created some time ago?  I started looking into this project as a means to hopefully generate a project stub and interact with the project through the command line vs having to use Visual Studio

**Comment by robbert229** [comment]
This issue is from a while ago, so the problem probably doesn't exist anymore for OSX. On Linux it builds fine as of the latest build. Does the issue still exist for you?

**Comment by TheDarkTrumpet** [comment]
Hi Robert,

I haven't tested this lately, but I'll try and test it either today or tomorrow and will respond here as soon as I do.

**Comment by robbert229** [comment]
Thanks

**Comment by robbert229** [comment]
Also, what version of OSX where you using then, and which when are you using now?

**Comment by robbert229** [comment]
Any update?

**Comment by TheDarkTrumpet** [comment]
Hi John,

Sorry about not getting back sooner, work has almost literally buried me lately.  Tomorrow night, I’ll send a few hours reworking this and will provide an update then.  Sorry about the wait on this.

To answer your previous question, I’m now on 10.11.1, which I’ve bene on 10.11 since it came out.

-David

**Comment by sayedihashimi** [comment]
I think the solution should build on mac/linux now so I'll close this.

If you are still having issues please open an issue in the https://github.com/aspnet/Tooling repo. It's monitored more often than this repo.
