### ISSUE TITLE
Add/New Scaffolded Item... missing from 2.2 projects Preview

### ISSUE THREAD

**Issue by Eilon** [aspnet/Scaffolding#860]
_From @damienbod on Wednesday, 22 August 2018 20:09:24_

When I create a new 2.2 ASP.NET Core MVC project with Identity, I cannot scaffold in the Identity Pages because the menu is missing in Visual Studio 

ASP.NET Core Preview 2.2:
 - MVC and Razor Pages: https://github.com/aspnet/Mvc

_Copied from original issue: aspnet/Home#3447_

**Comment by seancpeters** [comment]
@damienbod @Eilon - Scaffolding support for 2.2 projects will be available with the 15.9 Preview2 release of Visual Studio.

**Comment by jrb9249** [comment]
I installed 15.9.2 and am still having this issue.

**Comment by dumaisf** [comment]
I have the same issue with Visual Studio 2019 (16.0 Preview 1.1)

**Comment by seancpeters** [comment]
@dumaisf - are you also trying to scaffolding Identity on a .NET Core | ASP.NET Core 2.2 project? Or with a different configuration?

**Comment by dumaisf** [comment]
I was trying to scaffold from **ASP.NET Core 3.0 Preview 1**. I also tried to scaffold from **ASP.NET Core 2.2** _Latest stable version_ and the **New Scaffolding Item** menu item is back. I used Visual Studio 2019 (16.0 Preview 1.1), Visual Studio had nothing to do with the problem. See the [issue #10024](https://github.com/aspnet/Docs/issues/10024).
