### ISSUE TITLE
[Request] Add a command-line option to generate *all* "Identity" files

### ISSUE THREAD

**Issue by Phrohdoh** [aspnet/Scaffolding#872]
See https://github.com/aspnet/Docs/issues/8443.

---

Adding an option such as `--allFiles` that generated all files in the "Identity" generator (and updating the relevant doc page) would make this easy for `dotnet` CLI users.

**Comment by Rick-Anderson** [comment]
@seancpeters  an option would really help the docs.

**Comment by seancpeters** [comment]
@Phrohdoh @Rick-Anderson There isn't an explicit flag for selecting all files, but it is possible to scaffold all identity files without listing them. This is accomplished by not specifying the --files flag, and also not specifying the --useDefaultUI flag.

**Comment by Phrohdoh** [comment]
Would a small blurb detailing that be welcome on the linked document?
I'm willing to open a PR for that. :)

**Comment by seancpeters** [comment]
@Phrohdoh - Yes, this would be create to document, I hadn't thought about it before, but it's not intuitive.

@Rick-Anderson is probably the best person to coordinate with on this.

**Comment by Rick-Anderson** [comment]
@Phrohdoh a PR would be much appreciated.
