### ISSUE TITLE
Some template files in mvc are encoded in ASCII

### ISSUE THREAD

**Issue by leomurillo** [aspnet/Scaffolding#879]
Some template files in mvc are encoded in ASCII, let's convert to UTF8
When copying the Templates folder to the local project to customize templates, I get special characters transformed, like á or ñ. I found it is the encoding of the template files, some are in ASCII

## Steps to reproduce:
Copy the templates folder of microsoft.visualstudio.web.codegenerators.mvc package into the project to customize
Change Account.Manage.DeletePersonalData.cs.cshtml to include some unsual character, such as á
## Expected behavior:
The unsual character displays as expected, as we are supposed to be using UTF8 encoding
## Actual behavior:
The character is transformed during scaffolding because actually some template files as in ANSI/ASCII
### Target framework(s):
microsoft.visualstudio.web.codegenerators.mvc 2.1.3
### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:
2.1.3, microsoft.visualstudio.web.codegenerators.mvc

**Comment by seancpeters** [comment]
I've just made this PR #882 to add a BOM to all the scaffolding template files that didn't have a BOM.

**Comment by vijayrkn** [comment]
The PR is not relevant any more. Closing.
