### ISSUE TITLE
Reenable or remove disabled test

### ISSUE THREAD

**Issue by HaoK** [aspnet/Scaffolding#88]
https://github.com/aspnet/Scaffolding/blob/dev/test/Microsoft.Framework.CodeGeneration.Core.FunctionalTest/ModelTypesLocatorTests.cs#L76

I'm not sure what the right behavior of this test is, hosting engine has changed a bit so more types are showing up.  39 types now instead of 3...

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232572&fullScreen=false&_a=edit">232572</a>
