### ISSUE TITLE
Please shorten the name "aspnet-codegenerator" to something that doesn't take fifteen seconds to type

### ISSUE THREAD

**Issue by markrendle** [aspnet/Scaffolding#897]
## Steps to reproduce:

Install the global tool and the MVC package.
Type `dotnet aspnet-codegenerator controller ...`
Repeat.

## Expected behavior:

Change the calling name of the global tool to `aspnet`, then make the `codegenerator` bit just `g`.

So `aspnet g` or something.

You know, like `rails g`.

Remember Rails?

## Actual behavior:

Repetitive strain injury

### Target framework(s):

All of them

### Package version of Microsoft.AspNetCore.App or Microsoft.AspNetCore.All (if applicable):

All of them

### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:

All of them

**Comment by vijayrkn** [comment]
Any changes we make now would be a breaking change. This is just a dotnet global tool so you might be able to make an alias for this to use.
