### ISSUE TITLE
Please add a way to scaffold ALL Identity pages

### ISSUE THREAD

**Issue by markrendle** [aspnet/Scaffolding#898]
The Visual Studio experience for adding Identity UI overrides has a checkbox "Override all files".

It would be super if the CLI for `dotnet aspnet-codegenerator identity` had a corresponding flag.

I literally just downloaded a 5GB update to VS2017 15.9 Preview 2 so I could scaffold these pages.

**Comment by seancpeters** [comment]
Please see #872

**Comment by markrendle** [comment]
I submitted a PR to the Docs repo to make clear that this could be done already.
