### ISSUE TITLE
Dependency scaffolder error when adding controllers

### ISSUE THREAD

**Issue by Eilon** [aspnet/Scaffolding#917]
_From @adriaandavel on Thursday, 18 October 2018 11:49:02_

# Issue Title

Dependency scaffolder error when adding a controller

# General

I just loaded preview 3 hoping it would solve this error but it does not. I created a WebAPI project, and deleted the default values controller. When I try to add a new controller I get an error with message "Dependency scaffolder support the project runtime version". Google has not given me any usable alternatives

_Copied from original issue: dotnet/core#2005_

**Comment by Eilon** [comment]
_From @karelz on Thursday, 18 October 2018 16:33:59_

Is that an error from Visual Studio? If yes, then I would recommend to report it via VS Feedback (Send Feedback icon in VS or https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by Eilon** [comment]
_From @adriaandavel on Thursday, 18 October 2018 17:29:18_

Apologies for the omission, my VS version is 15.3.2. Is this a VS bug or a ASP.Net Core 2.2 project template issue?

**Comment by vijayrkn** [comment]
@adriaandavel ASP.NET Core 2.2 support is only available in 15.9 (which is currently in preview). Please update the VS version to 15.9 and try the scenario.

**Comment by vijayrkn** [comment]
Re-open if this is still an issue in the latest version.
