### ISSUE TITLE
Example how to add XML documentation as part of codegen

### ISSUE THREAD

**Issue by kant2002** [aspnet/Scaffolding#918]
## Steps to reproduce:

to ApiControllerWithContext.cshtml

add 
```
/// <summary>
/// Initializes a new instance of the <see cref="@(Model.ControllerName)"/> class.
/// </summary>
/// <param name="context">Database context to use.</param>
public @(Model.ControllerName)(@Model.ContextTypeName context)
{
    _context = context;
}
```

so the created constructor would be documented.

## Expected behavior:

a) Something more meaningful
b) maybe some example in the codebase how desired behavior could be obtained.

## Actual behavior:

![image](https://user-images.githubusercontent.com/4257079/47233132-92e82080-d3f3-11e8-90d3-e461c40c20b5.png)

### Package version of Microsoft.AspNetCore.App or Microsoft.AspNetCore.All (if applicable):
2.1.5

### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:
2.1.1

**Comment by seancpeters** [comment]
This issue was moved to aspnet/Razor#2664
