### ISSUE TITLE
2.2.0-preview3 not in Nuget

### ISSUE THREAD

**Issue by jfbleach** [aspnet/Scaffolding#919]
## Steps to reproduce:
Look on https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGeneration.Tools/
ver 2.1.4 is the newest
### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:
Having troubles with Version 2.2 Design because I can't get then matching version of Tools

**Comment by natemcmaster** [comment]
This package was deprecated in 2.0. See https://github.com/aspnet/Tooling/issues/1075 for details on how to upgrade to the new package.
