### ISSUE TITLE
dotnet tool aspnet-codegenerator looks for executable at wrong path

### ISSUE THREAD

**Issue by tbureck** [aspnet/Scaffolding#932]
I'm currently following [this guide](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=netcore-cli#scaffold-identity-into-an-empty-project) in order to scaffold Identity in my existing ASP.NET Core project. When trying to run the scaffolder command with the help option, though, I'm getting this error message:

```
> dotnet aspnet-codegenerator --help
The application to execute does not exist: 'C:\Users\Tim\.dotnet\tools\.store\dotnet-aspnet-codegenerator\2.2.0-rtm-35687\dotnet-aspnet-codegener
ator\2.2.0-rtm-35687\tools\netcoreapp2.1\any\dotnet-aspnet-codegenerator.dll'.
```

I've checked the .dotnet\tools\.store directory and the tool seems to be installed correctly. BUT, it is installed in a `2.2.0` directory instead of the `2.2.0-rtm-35687` directory, which dotnet tool is looking in.

I've opened [a thread on Stackoverflow](https://stackoverflow.com/questions/53676499/dotnet-tool-aspnet-codegenerator-looks-for-executable-at-wrong-path) as well and someone else seems to have the same issue, which is why I'm creating this issue.

Why is it that `dotnet tool` is looking in the `2.2.0-rtm-35687` sub directory instead of the `2.2.0` where it is actually installed?

Edit: my dotnet version is `2.2.100`

**Comment by maliming** [comment]
I also encountered the same problem.

**Comment by seancpeters** [comment]
This issue was moved to dotnet/cli#10459

**Comment by tbureck** [comment]
Since this was fixed in context of the issues linked above, I'm gonna close this issue. Thanks to everyone who has helped along the way! 💪
