### ISSUE TITLE
Could you set "Version" property to be in sync with "PackageVersion" to avoid tool invoke failure

### ISSUE THREAD

**Issue by wli3** [aspnet/Scaffolding#933]
I am sorry for this bug on SDK https://github.com/dotnet/sdk/issues/2698

That is the cause of  https://github.com/dotnet/cli/issues/10459#issuecomment-445940226

Do the following should mediate the problem:

Add in `<Version>$(PackageVersion)</Version>` to
 https://github.com/aspnet/Scaffolding/blob/master/src/dotnet-aspnet-codegenerator/dotnet-aspnet-codegenerator.csproj#L9

I will see if I can make a PR. And I will work on the code fix in SDK at the same time.

**Comment by vijayrkn** [comment]
Closing this in favor of https://github.com/aspnet/Scaffolding/issues/932
