### ISSUE TITLE
Identity UI Logout scaffolding

### ISSUE THREAD

**Issue by amafernandes** [aspnet/Scaffolding#937]
## Steps to reproduce:

- Start new project
```powershell
dotnet new razor -au Individual -uld

dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design

dotnet aspnet-codegenerator identity -fi Account.Logout

rm .\Areas\Identity\IdentityHostingStartup.cs

dotnet run
```
- Try register a new account.
- Apply EF migrations.
- Logout   

## Expected behavior:

![](https://raw.githubusercontent.com/amafernandes/assets/master/logout_expected.PNG)

## Actual behavior:

The username and Logout buttons are still visible after logout.

![](https://raw.githubusercontent.com/amafernandes/assets/master/logout_result.PNG)

## Details

The [scaffolding code](https://github.com/aspnet/Scaffolding/blob/master/src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/Pages/Account/Account.Logout.cs.cshtml#L58) uses `Page()`, while the [DefaultUI code](https://github.com/aspnet/AspNetCore/blob/5a64688d8e192cacffda9440e8725c1ed41a30cf/src/Identity/src/UI/Areas/Identity/Pages/V4/Account/Logout.cshtml.cs#L59) uses `RedirectToPage()`.

**Comment by Rick-Anderson** [comment]
More information in #965

**Comment by vphadnav** [comment]
can you try replacing

``<form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Page("/", new { area = "" })" method="post" >``

with

``<form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="/" method="post" >``

in the file ``/Pages/Shared/_LoginPartial.cshtml`` and see if it fixes the issue?

**Comment by vijayrkn** [comment]
@HaoK - Do you know if this is already addressed?

**Comment by Rick-Anderson** [comment]
I just tested and it's now working correctly.
```
dotnet --version
3.1.100-preview2-014569
```

I can test with 3.0 if you like.

**Comment by HaoK** [comment]
Awesome looks like its fixed then
