### ISSUE TITLE
Duplicate @using in ViewImports

### ISSUE THREAD

**Issue by patricka2** [aspnet/Scaffolding#939]
### Describe the bug
Identity code generator make duplicate `@using Microsoft.AspNetCore.Identity` in Areas\Identity\Pages\_ViewImports.cshtml

### Screenshots
![a](https://user-images.githubusercontent.com/46094177/50727841-7e9fef80-10d5-11e9-9834-fe619e0b17d5.png)

### Additional context
SDK Version 2.2.101
VS 2017 15.9.3

**Comment by vijayrkn** [comment]
This is an Identity content issue.

**Comment by HaoK** [comment]
Fixed by https://github.com/aspnet/Scaffolding/pull/1077
