### ISSUE TITLE
Make ValidationUtil class public

### ISSUE THREAD

**Issue by giggio** [aspnet/Scaffolding#94]
Right now `Microsoft.Framework.CodeGenerators.Mvc.ValidationUtil` is internal, but the work it is doing when validating model types is useful outside the `Microsoft.Framework.CodeGenerators.Mvc` assembly. It should be public.

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232573&fullScreen=false&_a=edit">232573</a>

**Comment by sayedihashimi** [comment]
@giggio sorry for the long delay here. I'm going to ask @prafullbhosale to investigate.
