### ISSUE TITLE
Scaffold Identity is generating wrong path

### ISSUE THREAD

**Issue by Eilon** [aspnet/Scaffolding#940]
_From @FellowsDevel on Thursday, 03 January 2019 16:54:50_

[https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=netcore-cli#scaffold-identity-into-a-razor-project-with-authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=netcore-cli#scaffold-identity-into-a-razor-project-with-authorization)

Following the upper tutorial, when you install the "**dotnet-aspnet-codegenerator**" it creates the path with the dotnetcore version, like:

C:\Users\XXXX\\.dotnet\tools\.store\dotnet-aspnet-codegenerator\2.2.0\dotnet-aspnet-codegenerator\2.2.0\tools\netcoreapp2.1\any........

But when you run the command "**dotnet aspnet-codegenerator identity -h**" 
We get an error:
C:\Users\XXXX\\.dotnet\tools\.store\dotnet-aspnet-codegenerator\**2.2.0-rtm-35687**\dotnet-aspnet-codegenerator\**2.2.0-rtm-35687**\tools\netcoreapp2.1\any\dotnet-aspnet-codegenerator.dll

Install output:
PS D:\devel\> dotnet tool install -g dotnet-aspnet-codegenerator

Welcome to .NET Core!
---------------------
Learn more about .NET Core: https://aka.ms/dotnet-docs
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by
setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

ASP.NET Core
------------
Successfully installed the ASP.NET Core HTTPS Development Certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
You can invoke the tool using the following command: dotnet-aspnet-codegenerator
Tool 'dotnet-aspnet-codegenerator' (**version '2.2.0'**) was successfully installed.

_Copied from original issue: dotnet/core#2200_

**Comment by seancpeters** [comment]
@Eilon @fellowsdevel
This is the same issue as discussed here dotnet/cli#10459 and #932

**Comment by Eilon** [comment]
Ah OK feel free to close as dup if it's the same.
