### ISSUE TITLE
Custom Templates folder not working with .NET Core 2.2

### ISSUE THREAD

**Issue by Iankodj** [aspnet/Scaffolding#959]
Upgrading a project from .NET Core 2.1 to 2.2 with custom scaffold Templates folder is generating output as if the native templates are read. 

## Steps to reproduce:
[TestingTemplates.zip](https://github.com/aspnet/Scaffolding/files/2904254/TestingTemplates.zip)

1. Generate a scaffold view
2. View is generated from the native templates and not by using the custom ones from the Templates folder.

## Expected behavior:

The custom view from the Templates folder to be used for the generated views.

## Actual behavior:

The native views are generated.

**Comment by EdCharbeneau** [comment]
I was able to reproduce this.

When using .NET Core 2.2 the /Templates folder seems to be ignored. Only the built in templates are used when the scaffolder is invoked.

**Comment by seancpeters** [comment]
@landodj @EdCharbeneau 

With the project you're attempting to scaffolding, is there an existing wwwroot directory with a bootstrap.js file? It would normally be found in `wwwroot\lib\bootstrap\dist\js\bootstrap.js`. If so, can you also look at the bootstrap.js file and let us know the bootstrap major version (should be 3 or 4)?

Scaffolding now contains content for both bootstrap 3 and bootstrap 4. The process attempts to discern the existing bootstrap version and provide appropriate content. If no bootstrap version is detected, the generated default content is for bootstrap 4.

To facilitate this, the scaffolding package carries 2 versions of the content. The bootstrap4 content is placed in the default location - the same place it was in the past, when there was only 1 version of the content. The bootstrap 3 content is placed in a slightly different location.

For the ViewGenerator:
The bootstrap4 content goes into a directory like this:
`Templates\ViewGenerator\`

The bootstrap 3 content goes into a directory like this:
`Templates\ViewGenerator_Versioned\Bootstrap3\`

**Comment by EdCharbeneau** [comment]
Worked perfectly, thanks for your support. @seancpeters
