### ISSUE TITLE
Provide infrastructure to show scaffoldings in Visual Studio with a GUI

### ISSUE THREAD

**Issue by giggio** [aspnet/Scaffolding#97]
Right now Scaffolding is only working with command line. If we write a new custom scaffolding we can use Visual Studio Extensibility APIs to extend Visual Studio and provide a GUI to these scaffoldings. But there is no clear path on how to connect the command line scaffolding to Visual Studio extensibility.
This issue addresses that.

There needs to exist an API we can use to directly invoke an scaffolding from Visual Studio, bootstrapping the whole dnx, passing in the current app and its context so that the scaffolding runs correctly.

A step further would be to provide some easy way to reflect upon a scaffolding and be able to understand what it expects as parameters. Right now we need to load dnx, load the type, look into method descriptors, etc.

An even further step would be to provide all of this directly into VS 2015, and let us register Scaffoldings simply by installing them from nuget, letting a custom form generator handle all the scaffolding parameters and create the GUI form to the user, so she/he can fill in the values. This is a bigger step, I can build my custom form, but it would be a "nice to have".

**Comment by barrytang** [comment]
This should be fixed with RC1.

**Comment by giggio** [comment]
I don't think this infrastructure is open source. Is it going to be?
