### ISSUE TITLE
"Failed to compile the project in memory" with c# 8.0 nullables

### ISSUE THREAD

**Issue by alexk8** [aspnet/Scaffolding#981]
I'm trying to use new features of c# 8.0 like nullable reference types, so I use 3.0-preview and opted in in project.csproj - 
```xml
    <NullableContextOptions>enable</NullableContextOptions>
    <LangVersion>8.0</LangVersion>
```
Scaffolding fails with message "Failed to compile the project in memory" because of nullables like "string?", etc in my code 
I think in-memory compilation should use projects-options to compile. 
Is there any temporary solution/workaround? (I'm trying to scaffold razor-identity-pages)

**Comment by seancpeters** [comment]
Thank you for the report on this issue. The problem is being tracked in #834
