### ISSUE TITLE
Add new scaffolded item error (Bug)

### ISSUE THREAD

**Issue by Yuant-tobing** [aspnet/Scaffolding#984]
Scaffolding items for:

- **API Controller with actions, using Entity Framework**
```
(Error : Method not found: System.Type.Microsoft.EntityFrameworkCore.Metadata.Iproperty.getClrType()'.')
```

- **MVC Controller with views, using Entity Framework**
```
(Error : Method not found: Boolean Microsoft.EntityFrameworkCore.Metadata.Iproperty.getlsShadowProperty'.')
```

## Steps to reproduce:
- Add new project
- Add context and etc..
- Add migration data by PMC command "Add-Migration ProjectInitialCreate"
- Update database by PMC command "Update-Database"
- Add new scaffolded items (ERROR)

### Target framework(s):
ASP.NET Core SDK v 3.0.0-preview4.19212.13

### Package version
```
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.3" />
```

**Comment by Duelbat** [comment]
Any news on this issue ? This error is occurring in core 3.0.0 preview 5 as well .

**Comment by BehzadA** [comment]
> Any news on this issue ? This error is occurring in core 3.0.0 preview 5 as well .

[https://github.com/aspnet/Scaffolding/issues/986#issuecomment-490594364](url)

**Comment by BehzadA** [comment]
> Any news on this issue ? This error is occurring in core 3.0.0 preview 5 as well .

https://github.com/aspnet/Scaffolding/issues/986#issuecomment-490594364

**Comment by crbeckman** [comment]
Still an issue.  Changed "<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.3" />" to "<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0-preview5-19264-04" />".  Using Visual Studio Community 2019 Version 16.0.4.  Scaffolding issues have been around for numerous preview builds and still an issue with 2019 16.0.4.

**Comment by crbeckman** [comment]
Sorry, it seems my package references were deleted.  they were codegeneration.Design version2.2.3 changed to version 3.0.0-preview5-19264-04.

**Comment by Rick-Anderson** [comment]
@seancpeters can we get an ETA on when this will be fixed. I can't update my tutorials for 3.0 until this is fixed. Do you have a work-around?
dotnet --version
3.0.100-preview7-012801
Error
```
dotnet aspnet-codegenerator razorpage -m Contact -udl -dc ApplicationDbContext -outDir Pages\Contacts --referenceScriptLibraries
Building project ...
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
Attempting to compile the application in memory.
Attempting to figure out the EntityFramework metadata for the model and DbContext: 'Contact'
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.0.0-preview7.19352.17 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Method not found: 'Boolean Microsoft.EntityFrameworkCore.Metadata.IProperty.get_IsShadowProperty()'.
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
```

**Comment by Rick-Anderson** [comment]
@seancpeters using the latest VS19 preview, I was able to scaffold so it's not urgent for me.

**Comment by vijayrkn** [comment]
This is fixed in the latest version.

**Comment by guilhermesoatto** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/24395958/74617935-6ee33f00-510e-11ea-860b-5501204cc81c.png)

using the last version
try to add scaffold item using netcore 3.1

**Comment by jrkcoder** [comment]
Just hit this using ASP.NET Core 5.
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
Tool 'dotnet-aspnet-codegenerator' (version '5.0.1') was successfully installed.
PM> aspnet-codegenerator razorpage -m Contact -udl -dc ApplicationDbContext -outDir Pages\Contacts --referenceScriptLibraries
aspnet-codegenerator : The term 'aspnet-codegenerator' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.
At line:1 char:1
+ aspnet-codegenerator razorpage -m Contact -udl -dc ApplicationDbConte ...
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (aspnet-codegenerator:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PM>

**Comment by jrkcoder** [comment]
........ was trying to work through example at
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-5.0#create-the-starter-app
