### ISSUE TITLE
Incomplete description for Identity scaffolder

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Scaffolding#985]
## Steps to reproduce:
1. Run `dotnet aspnet-codegenerator -h`
2. In the output, notice the description for the *identity* scaffolder is incomplete.

## Expected behavior:
The complete description should be displayed. Technically, this is working as designed. The description is truncated in https://github.com/aspnet/Scaffolding/blob/release/3.0/src/VS.Web.CG.Mvc/ParameterDefinitions/identity.json#L3.

## Actual behavior:
The description is incomplete.

### Package version of Microsoft.AspNetCore.App or Microsoft.AspNetCore.All (if applicable):
Microsoft.AspNetCore.App v2.2.3

### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:
2.2.3

**Comment by vijayrkn** [comment]
@scottaddie - Would it be possible for you to PR into master with the right description here? This will help us get this rectified much sooner.

**Comment by scottaddie** [comment]
@vijayrkn Yes. I'll add this task to my to-do list.

**Comment by vijayrkn** [comment]
Thank you!
