### ISSUE TITLE
Creating Controller  throws method not found

### ISSUE THREAD

**Issue by nadavbeno** [aspnet/Scaffolding#986]
I'm using the new EF core preview,
Trying to create a controller with Views, and get this error:
![image](https://user-images.githubusercontent.com/26343491/56565455-10fecd00-65b9-11e9-8b01-d321ec1e9af2.png)
Any ideas?
Thanks

**Comment by BehzadA** [comment]
Duplicate of # #984

**Comment by seancpeters** [comment]
A fix will be available in an upcoming release of Visual Studio. Until then, this will be broken with .Net Core 3.0 preview 5 or higher.

**Comment by vijayrkn** [comment]
This is fixed in the latest version.
