### ISSUE TITLE
scaffolding - generating controller in Asp.net core Issue

### ISSUE THREAD

**Issue by sashivakiti** [aspnet/Scaffolding#998]
## Steps to reproduce:
Try to generate model and context from Database.
Try generating controller from the class and model. We get error
![image](https://user-images.githubusercontent.com/1401177/58089352-e16ad100-7c07-11e9-87d0-3c90dae74887.png)

### Package version of Microsoft.AspNetCore.App or Microsoft.AspNetCore.All (if applicable):
Microsoft.AspNetCore.All (2.0.9)
### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:
Microsoft.VisualStudio.Web.CodeGeneration.Design (2.0.4)

###Package version of EntityFramework SqlServer and Tools:
Microsoft.EntityFrameworkCore.SqlServer (2.2.4)
Microsoft.EntityFrameworkCore.Tools (2.2.4)

**Comment by vijayrkn** [comment]
This should work with the latest version.
